// Mock Data for Inventory, Warehouse & Procurement System (Prompt 9)

import {
  WarehouseRecord,
  WarehouseZoneRecord,
  WarehouseRackRecord,
  InventoryItemRecord,
  InventoryStockRecord,
  InventoryMovementRecord,
  GoodsReceiptRecord,
  GoodsIssueRecord,
  StockTransferRecord,
  StockAdjustmentRecord,
  StockOpnameRecord,
  PurchaseRequestRecord,
  PurchaseOrderRecord,
  PurchaseInvoiceRecord,
  SupplierPerformanceRecord,
  InventoryForecastRecord,
  AiInventoryInsight,
  InventoryRestApiEndpoint,
} from './types';

export const INITIAL_WAREHOUSES: WarehouseRecord[] = [
  {
    id: 'wh-001',
    code: 'WH-CENTRAL-01',
    name: 'Gudang Utama Central Estate',
    companyId: 'COMP-PALM-01',
    companyName: 'PT Sawit Nusantara Mandiri',
    estateId: 'EST-01',
    estateName: 'Riau Central Estate',
    type: 'Gudang Utama Estate',
    address: 'Jl. Poros Kebun Raya Km 12, Kampar, Riau',
    picName: 'Hendra Saputra, S.T.',
    picPhone: '+62 812-3456-7890',
    areaSqm: 2400,
    capacityTon: 1500,
    usedCapacityTon: 920,
    latitude: 0.5071,
    longitude: 101.4478,
    status: 'Active',
    photoUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&auto=format&fit=crop&q=60',
    totalZones: 6,
    totalRacks: 48,
  },
  {
    id: 'wh-002',
    code: 'WH-CHEM-AFD1',
    name: 'Gudang Pupuk & Bahan Kimia Afdeling 1',
    companyId: 'COMP-PALM-01',
    companyName: 'PT Sawit Nusantara Mandiri',
    estateId: 'EST-01',
    estateName: 'Riau Central Estate',
    type: 'Gudang Chemical',
    address: 'Afdeling I, Sub-Division Central',
    picName: 'Budi Santoso',
    picPhone: '+62 813-9876-5432',
    areaSqm: 850,
    capacityTon: 600,
    usedCapacityTon: 480,
    latitude: 0.512,
    longitude: 101.453,
    status: 'Active',
    photoUrl: 'https://images.unsplash.com/photo-1578575437130-527eed3abbec?w=800&auto=format&fit=crop&q=60',
    totalZones: 3,
    totalRacks: 18,
  },
  {
    id: 'wh-003',
    code: 'WH-WORKSHOP-01',
    name: 'Gudang Sparepart & Workshop Alat Berat',
    companyId: 'COMP-PALM-01',
    companyName: 'PT Sawit Nusantara Mandiri',
    estateId: 'EST-01',
    estateName: 'Riau Central Estate',
    type: 'Gudang Workshop',
    address: 'Bengkel Kebun Utama, Zone 4',
    picName: 'Rudi Hermawan',
    picPhone: '+62 811-2233-4455',
    areaSqm: 1200,
    capacityTon: 400,
    usedCapacityTon: 280,
    latitude: 0.499,
    longitude: 101.441,
    status: 'Active',
    photoUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=60',
    totalZones: 4,
    totalRacks: 32,
  },
];

export const INITIAL_WAREHOUSE_ZONES: WarehouseZoneRecord[] = [
  {
    id: 'zone-01',
    code: 'ZONE-PUPUK-A',
    name: 'Zona Storage Pupuk Makro (Urea, NPK)',
    warehouseId: 'wh-001',
    warehouseName: 'Gudang Utama Central Estate',
    categoryAllowed: ['Pupuk', 'Bahan Kimia'],
    capacityUnit: 1000,
    usedUnit: 720,
    status: 'Active',
  },
  {
    id: 'zone-02',
    code: 'ZONE-HERBI-B',
    name: 'Zona Penyimpanan Herbisida & Agrochemical',
    warehouseId: 'wh-002',
    warehouseName: 'Gudang Pupuk & Bahan Kimia Afdeling 1',
    categoryAllowed: ['Pestisida', 'Herbisida'],
    capacityUnit: 500,
    usedUnit: 340,
    status: 'Active',
  },
  {
    id: 'zone-03',
    code: 'ZONE-TOOLS-C',
    name: 'Zona Alat Panen & Peralatan Kerja',
    warehouseId: 'wh-001',
    warehouseName: 'Gudang Utama Central Estate',
    categoryAllowed: ['Alat Panen', 'Alat Kerja', 'APD'],
    capacityUnit: 800,
    usedUnit: 410,
    status: 'Active',
  },
  {
    id: 'zone-04',
    code: 'ZONE-PARTS-D',
    name: 'Zona Suku Cadang Traktor & Fleet',
    warehouseId: 'wh-003',
    warehouseName: 'Gudang Sparepart & Workshop Alat Berat',
    categoryAllowed: ['Suku Cadang', 'Oli & Pelumas'],
    capacityUnit: 600,
    usedUnit: 480,
    status: 'Active',
  },
];

export const INITIAL_WAREHOUSE_RACKS: WarehouseRackRecord[] = [
  {
    id: 'rack-01',
    code: 'RACK-A01-L1',
    zoneId: 'zone-01',
    zoneName: 'Zona Storage Pupuk Makro (Urea, NPK)',
    warehouseName: 'Gudang Utama Central Estate',
    rowNumber: 1,
    columnNumber: 1,
    levelNumber: 1,
    maxCapacityKg: 50000,
    currentWeightKg: 42000,
    status: 'Available',
  },
  {
    id: 'rack-02',
    code: 'RACK-B04-L2',
    zoneId: 'zone-02',
    zoneName: 'Zona Penyimpanan Herbisida & Agrochemical',
    warehouseName: 'Gudang Pupuk & Bahan Kimia Afdeling 1',
    rowNumber: 2,
    columnNumber: 4,
    levelNumber: 2,
    maxCapacityKg: 20000,
    currentWeightKg: 18500,
    status: 'Available',
  },
  {
    id: 'rack-03',
    code: 'RACK-C02-L1',
    zoneId: 'zone-03',
    zoneName: 'Zona Alat Panen & Peralatan Kerja',
    warehouseName: 'Gudang Utama Central Estate',
    rowNumber: 3,
    columnNumber: 2,
    levelNumber: 1,
    maxCapacityKg: 15000,
    currentWeightKg: 9400,
    status: 'Available',
  },
];

export const INITIAL_INVENTORY_ITEMS: InventoryItemRecord[] = [
  {
    id: 'item-01',
    itemCode: 'ITEM-PPK-001',
    barcode: '8991002304918',
    qrCode: 'QR-ITEM-PPK-001-UREA',
    name: 'Pupuk Urea Subsidized Granular 50kg',
    category: 'Pupuk',
    brand: 'Pupuk Kaltim',
    specification: 'Kadar N min 46%, Granul Putih, Kemasan Karung Woven',
    unit: 'Karung',
    primarySupplierName: 'PT Pupuk Indonesia (Persero)',
    buyPrice: 185000,
    standardPrice: 195000,
    minStock: 200,
    maxStock: 2000,
    safetyStock: 300,
    leadTimeDays: 7,
    defaultWarehouseName: 'Gudang Utama Central Estate',
    defaultRackCode: 'RACK-A01-L1',
    status: 'Active',
    photoUrl: 'https://images.unsplash.com/photo-1595246140625-573b715d11dc?w=800&auto=format&fit=crop&q=60',
    lastRestockedDate: '2026-07-28',
  },
  {
    id: 'item-02',
    itemCode: 'ITEM-PPK-002',
    barcode: '8991002304925',
    qrCode: 'QR-ITEM-PPK-002-NPK',
    name: 'Pupuk NPK 13-6-27-4+B Sawit Premium 50kg',
    category: 'Pupuk',
    brand: 'Mahkota Fertilizers',
    specification: 'Kadar N 13%, P2O5 6%, K2O 27%, MgO 4%, Boron 0.5%',
    unit: 'Karung',
    primarySupplierName: 'PT Wilmar Nabati Indonesia',
    buyPrice: 385000,
    standardPrice: 400000,
    minStock: 150,
    maxStock: 1500,
    safetyStock: 200,
    leadTimeDays: 10,
    defaultWarehouseName: 'Gudang Utama Central Estate',
    defaultRackCode: 'RACK-A01-L1',
    status: 'Active',
    photoUrl: 'https://images.unsplash.com/photo-1628102491629-778571d893a3?w=800&auto=format&fit=crop&q=60',
    lastRestockedDate: '2026-07-25',
  },
  {
    id: 'item-03',
    itemCode: 'ITEM-HER-001',
    barcode: '8992001102931',
    qrCode: 'QR-ITEM-HER-001-GLYPH',
    name: 'Herbisida Sistemik Isopropilamina Glifosat 480 SL 20L',
    category: 'Herbisida',
    brand: 'Roundup PowerMax / Syngenta Touchdown',
    specification: 'Cairan Konsentrat 480 g/L, Kemasan Jerigen 20 Liter',
    unit: 'Jerigen',
    primarySupplierName: 'PT Syngenta Indonesia',
    buyPrice: 850000,
    standardPrice: 890000,
    minStock: 40,
    maxStock: 300,
    safetyStock: 50,
    leadTimeDays: 5,
    defaultWarehouseName: 'Gudang Pupuk & Bahan Kimia Afdeling 1',
    defaultRackCode: 'RACK-B04-L2',
    status: 'Active',
    photoUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&auto=format&fit=crop&q=60',
    lastRestockedDate: '2026-07-30',
  },
  {
    id: 'item-04',
    itemCode: 'ITEM-PAN-001',
    barcode: '8993004401928',
    qrCode: 'QR-ITEM-PAN-001-EGREK',
    name: 'Egrek Panen Sawit Super Sharp Spring Steel 333',
    category: 'Alat Panen',
    brand: 'KAPLUS Germany Steel',
    specification: 'Baja High Carbon Spring, Ketajaman Ultra High, Panjang 55cm',
    unit: 'Pcs',
    primarySupplierName: 'PT Plantation Tools Supply',
    buyPrice: 245000,
    standardPrice: 260000,
    minStock: 30,
    maxStock: 200,
    safetyStock: 40,
    leadTimeDays: 4,
    defaultWarehouseName: 'Gudang Utama Central Estate',
    defaultRackCode: 'RACK-C02-L1',
    status: 'Active',
    photoUrl: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=800&auto=format&fit=crop&q=60',
    lastRestockedDate: '2026-07-18',
  },
  {
    id: 'item-05',
    itemCode: 'ITEM-PAN-002',
    barcode: '8993004401935',
    qrCode: 'QR-ITEM-PAN-002-DODOS',
    name: 'Dodos Panen Sawit Low-Tree 12cm High Carbon',
    category: 'Alat Panen',
    brand: 'Cap Mata Malaysia',
    specification: 'Lebar Mata 12cm, khusus Pokok Rekomendasi TM-1 s/d TM-5',
    unit: 'Pcs',
    primarySupplierName: 'PT Plantation Tools Supply',
    buyPrice: 195000,
    standardPrice: 210000,
    minStock: 25,
    maxStock: 150,
    safetyStock: 30,
    leadTimeDays: 4,
    defaultWarehouseName: 'Gudang Utama Central Estate',
    defaultRackCode: 'RACK-C02-L1',
    status: 'Active',
    photoUrl: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=800&auto=format&fit=crop&q=60',
    lastRestockedDate: '2026-07-20',
  },
  {
    id: 'item-06',
    itemCode: 'ITEM-OLI-001',
    barcode: '8994005501811',
    qrCode: 'QR-ITEM-OLI-001-DIESEL',
    name: 'Oli Mesin Heavy Duty Diesel SAE 15W-40 Drum 200L',
    category: 'Oli & Pelumas',
    brand: 'Shell Rimula R4 X',
    specification: 'API CI-4/SL, Heavy Duty Tractor & Dump Truck Engine Oil',
    unit: 'Drum',
    primarySupplierName: 'PT Shell Indonesia Distributor',
    buyPrice: 7800000,
    standardPrice: 8200000,
    minStock: 5,
    maxStock: 30,
    safetyStock: 8,
    leadTimeDays: 6,
    defaultWarehouseName: 'Gudang Sparepart & Workshop Alat Berat',
    defaultRackCode: 'RACK-PARTS-D',
    status: 'Active',
    photoUrl: 'https://images.unsplash.com/photo-1615900119313-a4e9b97b0a33?w=800&auto=format&fit=crop&q=60',
    lastRestockedDate: '2026-07-15',
  },
  {
    id: 'item-07',
    itemCode: 'ITEM-BBM-001',
    barcode: '8994005501999',
    qrCode: 'QR-ITEM-BBM-SOLAR-IND',
    name: 'Solar B35 Industri High Quality Grade',
    category: 'BBM (Solar)',
    brand: 'Pertamina Patra Niaga',
    specification: 'Bio Solar B35 Non-Subsidi untuk Alat Berat & Genset PKS',
    unit: 'Liter',
    primarySupplierName: 'PT Pertamina Patra Niaga',
    buyPrice: 14200,
    standardPrice: 15000,
    minStock: 5000,
    maxStock: 40000,
    safetyStock: 8000,
    leadTimeDays: 3,
    defaultWarehouseName: 'Gudang Utama Central Estate',
    defaultRackCode: 'TANK-SOLAR-01',
    status: 'Active',
    photoUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?w=800&auto=format&fit=crop&q=60',
    lastRestockedDate: '2026-08-01',
  },
];

export const INITIAL_INVENTORY_STOCKS: InventoryStockRecord[] = [
  {
    id: 'stk-01',
    itemId: 'item-01',
    itemCode: 'ITEM-PPK-001',
    itemName: 'Pupuk Urea Subsidized Granular 50kg',
    category: 'Pupuk',
    unit: 'Karung',
    warehouseName: 'Gudang Utama Central Estate',
    rackCode: 'RACK-A01-L1',
    available: 840,
    reserved: 120,
    allocated: 50,
    inTransit: 200,
    damaged: 4,
    expired: 0,
    onOrder: 500,
    minStock: 200,
    maxStock: 2000,
    stockStatus: 'Normal',
    unitValue: 185000,
    totalValue: 155400000,
  },
  {
    id: 'stk-02',
    itemId: 'item-02',
    itemCode: 'ITEM-PPK-002',
    itemName: 'Pupuk NPK 13-6-27-4+B Sawit Premium 50kg',
    category: 'Pupuk',
    unit: 'Karung',
    warehouseName: 'Gudang Utama Central Estate',
    rackCode: 'RACK-A01-L1',
    available: 180,
    reserved: 100,
    allocated: 40,
    inTransit: 0,
    damaged: 2,
    expired: 0,
    onOrder: 300,
    minStock: 150,
    maxStock: 1500,
    stockStatus: 'Warning',
    unitValue: 385000,
    totalValue: 69300000,
  },
  {
    id: 'stk-03',
    itemId: 'item-03',
    itemCode: 'ITEM-HER-001',
    itemName: 'Herbisida Sistemik Isopropilamina Glifosat 480 SL 20L',
    category: 'Herbisida',
    unit: 'Jerigen',
    warehouseName: 'Gudang Pupuk & Bahan Kimia Afdeling 1',
    rackCode: 'RACK-B04-L2',
    available: 28,
    reserved: 15,
    allocated: 10,
    inTransit: 30,
    damaged: 0,
    expired: 0,
    onOrder: 100,
    minStock: 40,
    maxStock: 300,
    stockStatus: 'Critical',
    unitValue: 850000,
    totalValue: 23800000,
  },
  {
    id: 'stk-04',
    itemId: 'item-04',
    itemCode: 'ITEM-PAN-001',
    itemName: 'Egrek Panen Sawit Super Sharp Spring Steel 333',
    category: 'Alat Panen',
    unit: 'Pcs',
    warehouseName: 'Gudang Utama Central Estate',
    rackCode: 'RACK-C02-L1',
    available: 110,
    reserved: 20,
    allocated: 10,
    inTransit: 0,
    damaged: 1,
    expired: 0,
    onOrder: 0,
    minStock: 30,
    maxStock: 200,
    stockStatus: 'Normal',
    unitValue: 245000,
    totalValue: 26950000,
  },
  {
    id: 'stk-05',
    itemId: 'item-06',
    itemCode: 'ITEM-OLI-001',
    itemName: 'Oli Mesin Heavy Duty Diesel SAE 15W-40 Drum 200L',
    category: 'Oli & Pelumas',
    unit: 'Drum',
    warehouseName: 'Gudang Sparepart & Workshop Alat Berat',
    rackCode: 'RACK-PARTS-D',
    available: 14,
    reserved: 2,
    allocated: 1,
    inTransit: 5,
    damaged: 0,
    expired: 0,
    onOrder: 10,
    minStock: 5,
    maxStock: 30,
    stockStatus: 'Normal',
    unitValue: 7800000,
    totalValue: 109200000,
  },
  {
    id: 'stk-06',
    itemId: 'item-07',
    itemCode: 'ITEM-BBM-001',
    itemName: 'Solar B35 Industri High Quality Grade',
    category: 'BBM (Solar)',
    unit: 'Liter',
    warehouseName: 'Gudang Utama Central Estate',
    rackCode: 'TANK-SOLAR-01',
    available: 22400,
    reserved: 4000,
    allocated: 2000,
    inTransit: 10000,
    damaged: 0,
    expired: 0,
    onOrder: 15000,
    minStock: 5000,
    maxStock: 40000,
    stockStatus: 'Normal',
    unitValue: 14200,
    totalValue: 318080000,
  },
];

export const INITIAL_INVENTORY_MOVEMENTS: InventoryMovementRecord[] = [
  {
    id: 'mov-001',
    movementNumber: 'MOV-20260801-001',
    timestamp: '2026-08-01 08:30',
    movementType: 'Goods Receipt',
    itemId: 'item-01',
    itemCode: 'ITEM-PPK-001',
    itemName: 'Pupuk Urea Subsidized Granular 50kg',
    quantity: 300,
    unit: 'Karung',
    sourceLocation: 'PT Pupuk Indonesia (PO-2026-07-089)',
    destinationLocation: 'Gudang Utama Central Estate (RACK-A01-L1)',
    referenceNumber: 'GRN-2026-08-012',
    actorName: 'Hendra Saputra',
    notes: 'Penerimaan barang PO-2026-07-089 lunas, kondisi karung rapi.',
  },
  {
    id: 'mov-002',
    movementNumber: 'MOV-20260802-004',
    timestamp: '2026-08-02 10:15',
    movementType: 'Goods Issue',
    itemId: 'item-03',
    itemCode: 'ITEM-HER-001',
    itemName: 'Herbisida Sistemik Isopropilamina Glifosat 480 SL 20L',
    quantity: 12,
    unit: 'Jerigen',
    sourceLocation: 'Gudang Pupuk Afdeling 1',
    destinationLocation: 'Work Order WO-2026-08-045 (Chem Control Blok A12)',
    referenceNumber: 'GI-2026-08-045',
    actorName: 'Budi Santoso',
    notes: 'Pengeluaran bahan chem control semprot gulma piringan.',
  },
  {
    id: 'mov-003',
    movementNumber: 'MOV-20260802-009',
    timestamp: '2026-08-02 14:00',
    movementType: 'Stock Transfer',
    itemId: 'item-01',
    itemCode: 'ITEM-PPK-001',
    itemName: 'Pupuk Urea Subsidized Granular 50kg',
    quantity: 100,
    unit: 'Karung',
    sourceLocation: 'Gudang Utama Central Estate',
    destinationLocation: 'Gudang Pupuk & Bahan Kimia Afdeling 1',
    referenceNumber: 'TRF-2026-08-003',
    actorName: 'Rian Kurniawan',
    notes: 'Transfer stok antar gudang untuk pemupukan jadwal minggu ini.',
  },
];

export const INITIAL_GOODS_RECEIPTS: GoodsReceiptRecord[] = [
  {
    id: 'gr-01',
    grNumber: 'GRN-2026-08-012',
    poNumber: 'PO-2026-07-089',
    supplierName: 'PT Pupuk Indonesia (Persero)',
    date: '2026-08-01',
    warehouseName: 'Gudang Utama Central Estate',
    officerName: 'Hendra Saputra',
    itemCount: 1,
    totalQuantity: 300,
    conditionStatus: 'Pass QC',
    notes: 'Kondisi fisik segel utuh, lolos uji kadar moisture sampel.',
    status: 'Completed',
  },
  {
    id: 'gr-02',
    grNumber: 'GRN-2026-08-018',
    poNumber: 'PO-2026-07-094',
    supplierName: 'PT Syngenta Indonesia',
    date: '2026-08-02',
    warehouseName: 'Gudang Pupuk & Bahan Kimia Afdeling 1',
    officerName: 'Budi Santoso',
    itemCount: 2,
    totalQuantity: 45,
    conditionStatus: 'Pass QC',
    notes: 'Sudah diperiksa tanggal expired batch 2028.',
    status: 'Completed',
  },
];

export const INITIAL_GOODS_ISSUES: GoodsIssueRecord[] = [
  {
    id: 'gi-01',
    giNumber: 'GI-2026-08-045',
    date: '2026-08-02',
    warehouseName: 'Gudang Pupuk & Bahan Kimia Afdeling 1',
    destinationWorkOrder: 'WO-2026-08-045',
    fieldActivity: 'Pengendalian Gulma Chem Control Blok A12',
    requestorName: 'Mandor Supriadi',
    approverName: 'Asisten Afdeling Rahmat',
    itemName: 'Herbisida Glifosat 480 SL 20L',
    quantity: 12,
    unit: 'Jerigen',
    status: 'Issued',
  },
  {
    id: 'gi-02',
    giNumber: 'GI-2026-08-049',
    date: '2026-08-03',
    warehouseName: 'Gudang Sparepart & Workshop Alat Berat',
    destinationWorkOrder: 'WO-MNT-TRK-09',
    fieldActivity: 'Ganti Oli & Service Periodik Traktor John Deere',
    requestorName: 'Mekanik Anton',
    approverName: 'Kepala Workshop Herman',
    itemName: 'Oli Mesin Heavy Duty Diesel 15W-40 200L',
    quantity: 1,
    unit: 'Drum',
    status: 'Issued',
  },
];

export const INITIAL_STOCK_TRANSFERS: StockTransferRecord[] = [
  {
    id: 'trf-01',
    transferNumber: 'TRF-2026-08-003',
    date: '2026-08-02',
    sourceWarehouse: 'Gudang Utama Central Estate',
    destinationWarehouse: 'Gudang Pupuk & Bahan Kimia Afdeling 1',
    itemCode: 'ITEM-PPK-001',
    itemName: 'Pupuk Urea Subsidized Granular 50kg',
    quantity: 100,
    unit: 'Karung',
    status: 'In Transit',
    requestedBy: 'Asisten Afdeling 1',
    approvedBy: 'Estate Manager Sitorus',
  },
];

export const INITIAL_STOCK_ADJUSTMENTS: StockAdjustmentRecord[] = [
  {
    id: 'adj-01',
    adjustmentNumber: 'ADJ-2026-07-009',
    date: '2026-07-29',
    warehouseName: 'Gudang Utama Central Estate',
    itemName: 'Pupuk Urea Subsidized Granular 50kg',
    reason: 'Rusak',
    type: 'Deduction',
    quantity: 4,
    unit: 'Karung',
    conductedBy: 'Hendra Saputra',
    approvedBy: 'Head Warehouse Manager',
  },
];

export const INITIAL_STOCK_OPNAMES: StockOpnameRecord[] = [
  {
    id: 'opn-01',
    opnameNumber: 'OPN-2026-07-Q2',
    date: '2026-07-31',
    warehouseName: 'Gudang Utama Central Estate',
    zoneCode: 'ZONE-PUPUK-A',
    totalItemsScanned: 48,
    matchedCount: 46,
    discrepancyCount: 2,
    conductedBy: 'Tim Audit Stock Opname Internal',
    status: 'Approved & Synced',
  },
];

export const INITIAL_PURCHASE_REQUESTS: PurchaseRequestRecord[] = [
  {
    id: 'pr-01',
    prNumber: 'PR-2026-08-001',
    date: '2026-08-01',
    requestorName: 'Ir. Agus Wijaya',
    department: 'Agronomy Field Operations',
    workOrderRef: 'WO-FERT-AUG-01',
    priority: 'High',
    itemName: 'Pupuk NPK 13-6-27-4+B Sawit Premium 50kg',
    category: 'Pupuk',
    requestedQuantity: 500,
    unit: 'Karung',
    estimatedTotalCost: 192500000,
    justification: 'Stok mendekati batas critical warning; jadwal pemupukan semester II Blok A & B.',
    status: 'Approved',
    currentApproverLevel: 'Purchasing Manager (Cleared)',
  },
  {
    id: 'pr-02',
    prNumber: 'PR-2026-08-004',
    date: '2026-08-02',
    requestorName: 'Herman M.',
    department: 'Workshop & Maintenance Fleet',
    workOrderRef: 'WO-WORKSHOP-08',
    priority: 'Urgent',
    itemName: 'Oli Mesin Heavy Duty Diesel SAE 15W-40 Drum 200L',
    category: 'Oli & Pelumas',
    requestedQuantity: 10,
    unit: 'Drum',
    estimatedTotalCost: 78000000,
    justification: 'Persiapan overhaul 4 unit Dump Truck Hino pengangkut TBS PKS.',
    status: 'Submitted',
    currentApproverLevel: 'Approval Level 2: General Manager Estate',
  },
];

export const INITIAL_PURCHASE_ORDERS: PurchaseOrderRecord[] = [
  {
    id: 'po-01',
    poNumber: 'PO-2026-08-015',
    prReference: 'PR-2026-08-001',
    supplierName: 'PT Wilmar Nabati Indonesia',
    poDate: '2026-08-02',
    expectedDeliveryDate: '2026-08-10',
    itemName: 'Pupuk NPK 13-6-27-4+B Sawit Premium 50kg',
    quantity: 500,
    unit: 'Karung',
    unitPrice: 385000,
    discountPercentage: 2,
    vatPercentage: 11,
    totalAmount: 209425500,
    status: 'Issued',
  },
  {
    id: 'po-02',
    poNumber: 'PO-2026-07-089',
    prReference: 'PR-2026-07-042',
    supplierName: 'PT Pupuk Indonesia (Persero)',
    poDate: '2026-07-25',
    expectedDeliveryDate: '2026-08-01',
    itemName: 'Pupuk Urea Subsidized Granular 50kg',
    quantity: 300,
    unit: 'Karung',
    unitPrice: 185000,
    discountPercentage: 0,
    vatPercentage: 11,
    totalAmount: 61605000,
    status: 'Completed',
  },
];

export const INITIAL_PURCHASE_INVOICES: PurchaseInvoiceRecord[] = [
  {
    id: 'inv-01',
    invoiceNumber: 'INV-WNI-202608-091',
    supplierName: 'PT Wilmar Nabati Indonesia',
    invoiceDate: '2026-08-02',
    poNumber: 'PO-2026-08-015',
    grNumber: 'Pending GRN',
    amountTotal: 209425500,
    dueDate: '2026-09-02',
    paymentStatus: 'Unpaid',
  },
  {
    id: 'inv-02',
    invoiceNumber: 'INV-PI-202607-441',
    supplierName: 'PT Pupuk Indonesia (Persero)',
    invoiceDate: '2026-08-01',
    poNumber: 'PO-2026-07-089',
    grNumber: 'GRN-2026-08-012',
    amountTotal: 61605000,
    dueDate: '2026-08-31',
    paymentStatus: 'Paid',
  },
];

export const INITIAL_SUPPLIER_PERFORMANCE: SupplierPerformanceRecord[] = [
  {
    id: 'sup-01',
    supplierName: 'PT Pupuk Indonesia (Persero)',
    categoryProvided: 'Pupuk',
    onTimeDeliveryRate: 98.2,
    qualityPassRate: 99.5,
    competitivePriceScore: 94,
    responsivenessScore: 92,
    totalOrdersFulfilled: 34,
    totalComplaints: 1,
    kpiScore: 96.4,
    rankingGrade: 'A+ (Preferred)',
  },
  {
    id: 'sup-02',
    supplierName: 'PT Syngenta Indonesia',
    categoryProvided: 'Herbisida',
    onTimeDeliveryRate: 95.0,
    qualityPassRate: 100.0,
    competitivePriceScore: 88,
    responsivenessScore: 95,
    totalOrdersFulfilled: 22,
    totalComplaints: 0,
    kpiScore: 94.5,
    rankingGrade: 'A (Reliable)',
  },
  {
    id: 'sup-03',
    supplierName: 'PT Shell Indonesia Distributor',
    categoryProvided: 'Oli & Pelumas',
    onTimeDeliveryRate: 91.5,
    qualityPassRate: 98.0,
    competitivePriceScore: 85,
    responsivenessScore: 89,
    totalOrdersFulfilled: 18,
    totalComplaints: 2,
    kpiScore: 90.8,
    rankingGrade: 'A (Reliable)',
  },
  {
    id: 'sup-04',
    supplierName: 'PT Plantation Tools Supply',
    categoryProvided: 'Alat Panen',
    onTimeDeliveryRate: 86.0,
    qualityPassRate: 92.0,
    competitivePriceScore: 90,
    responsivenessScore: 82,
    totalOrdersFulfilled: 15,
    totalComplaints: 3,
    kpiScore: 87.5,
    rankingGrade: 'B (Acceptable)',
  },
];

export const INITIAL_INVENTORY_FORECASTS: InventoryForecastRecord[] = [
  {
    id: 'fc-01',
    itemCode: 'ITEM-PPK-001',
    itemName: 'Pupuk Urea Subsidized Granular 50kg',
    category: 'Pupuk',
    currentStock: 840,
    unit: 'Karung',
    forecastPeriod: '30 Hari',
    predictedConsumption: 620,
    recommendedOrderQuantity: 500,
    suggestedOrderDate: '2026-08-18',
    confidenceScore: 94.2,
  },
  {
    id: 'fc-02',
    itemCode: 'ITEM-HER-001',
    itemName: 'Herbisida Glifosat 480 SL 20L',
    category: 'Herbisida',
    currentStock: 28,
    unit: 'Jerigen',
    forecastPeriod: '30 Hari',
    predictedConsumption: 65,
    recommendedOrderQuantity: 100,
    suggestedOrderDate: '2026-08-04',
    confidenceScore: 96.8,
  },
  {
    id: 'fc-03',
    itemCode: 'ITEM-BBM-001',
    itemName: 'Solar B35 Industri High Quality Grade',
    category: 'BBM (Solar)',
    currentStock: 22400,
    unit: 'Liter',
    forecastPeriod: '7 Hari',
    predictedConsumption: 18500,
    recommendedOrderQuantity: 20000,
    suggestedOrderDate: '2026-08-06',
    confidenceScore: 98.1,
  },
];

export const INITIAL_AI_INVENTORY_INSIGHTS: AiInventoryInsight[] = [
  {
    id: 'ai-inv-01',
    title: 'Kritis: Herbisida Glifosat 480 SL Diprediksi Habis dalam 5 Hari',
    category: 'Reorder Alert',
    itemOrWarehouse: 'Gudang Pupuk Afdeling 1 (ITEM-HER-001)',
    insightText:
      'Laju pemakaian rata-rata saat ini 5.2 jerigen/hari untuk chem control Blok A & B. Dengan sisa 28 jerigen, stok akan habis sebelum PO biasa dapat tiba (lead time 5 hari).',
    recommendedAction: 'Terbitkan Purchase Order Emergency (PO Fast-Track) sejumlah 100 Jerigen hari ini.',
    impactEstimate: 'Mencegah penundaan rotasi chem control 240 Ha perkebunan.',
    confidenceScore: 97.4,
  },
  {
    id: 'ai-inv-02',
    title: 'Deteksi Slow-Moving & Dead Stock pada Sparepart Egrek Lama',
    category: 'Dead Stock Detection',
    itemOrWarehouse: 'Gudang Utama (RACK-C02-L1)',
    insightText:
      'Terdapat 45 unit Egrek Tipe Model-2021 yang tidak pernah dikeluarkan dari gudang selama >180 hari karena pemanen beralih ke Model KAPLUS 333.',
    recommendedAction: 'Lakukan redistribusi ke kebun Afdeling luar atau lelang pemutihan stok bernilai Rp 11.025.000.',
    impactEstimate: 'Penghematan ruang rak gudang & pemulihan modal kerja.',
    confidenceScore: 91.2,
  },
  {
    id: 'ai-inv-03',
    title: 'Optimasi Pembelian Massal Pupuk NPK (Volume Discount Opportunity)',
    category: 'Cost Optimization',
    itemOrWarehouse: 'PT Wilmar Nabati Indonesia',
    insightText:
      'Penggabungan PR Afdeling 1, 2, dan 3 untuk kebutuhan NPK Kuartal III mencapai 1,200 karung. Supplier menawarkan tambahan diskon 4% jika order > 1,000 karung sekaligus.',
    recommendedAction: 'Gabungkan PR-2026-08-001 dan PR-2026-08-005 menjadi satu PO Konsolidasi.',
    impactEstimate: 'Potensi hemat pengadaan Rp 18.480.000.',
    confidenceScore: 95.8,
  },
];

export const INVENTORY_REST_API_DOCS: InventoryRestApiEndpoint[] = [
  { method: 'GET', path: '/api/v1/inventory/items', description: 'Mendapatkan daftar seluruh item barang gudang beserta level stok & lokasi rak' },
  { method: 'POST', path: '/api/v1/inventory/items', description: 'Pendaftaran item barang baru lengkap dengan kode barcode/QR dan min-max stock' },
  { method: 'GET', path: '/api/v1/inventory/warehouses', description: 'Mendapatkan master data gudang, zona, rak, dan kapasitas daya tampung' },
  { method: 'POST', path: '/api/v1/inventory/goods-receipt', description: 'Pencatatan Goods Receipt (GRN) barang masuk dari PO atau supplier' },
  { method: 'POST', path: '/api/v1/inventory/goods-issue', description: 'Pengeluaran barang (GI) ke Work Order lapangan / pemeliharaan' },
  { method: 'POST', path: '/api/v1/inventory/stock-transfer', description: 'Permintaan dan pengiriman transfer stok antar gudang / afdeling' },
  { method: 'POST', path: '/api/v1/inventory/stock-opname', description: 'Submit hasil verifikasi fisik Stock Opname scanner barcode/QR' },
  { method: 'GET', path: '/api/v1/procurement/purchase-requests', description: 'Daftar Purchase Request (PR) beserta status approval multi-level' },
  { method: 'POST', path: '/api/v1/procurement/purchase-orders', description: 'Penerbitan PO resmi ke supplier terdaftar' },
  { method: 'GET', path: '/api/v1/procurement/supplier-performance', description: 'Skor KPI dan rangking supplier berdasarkan OTD, QC & harga' },
  { method: 'GET', path: '/api/v1/inventory/ai-insights', description: 'Rekomendasi AI untuk reorder alert, safety stock, dan dead stock detection' },
];

export const INVENTORY_DB_SCHEMA_DOCS = `-- PostgreSQL Schema Migration DDL for Inventory, Warehouse & Procurement System (Prompt 9)

CREATE TABLE warehouses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    company_id UUID NOT NULL,
    estate_id UUID NOT NULL,
    type VARCHAR(50) NOT NULL,
    address TEXT,
    pic_name VARCHAR(150),
    pic_phone VARCHAR(50),
    area_sqm NUMERIC(10,2),
    capacity_ton NUMERIC(10,2),
    used_capacity_ton NUMERIC(10,2) DEFAULT 0,
    latitude NUMERIC(10,6),
    longitude NUMERIC(10,6),
    status VARCHAR(30) DEFAULT 'Active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE warehouse_zones (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    warehouse_id UUID REFERENCES warehouses(id) ON DELETE CASCADE,
    capacity_unit INT DEFAULT 0,
    used_unit INT DEFAULT 0,
    status VARCHAR(30) DEFAULT 'Active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE warehouse_racks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code VARCHAR(50) NOT NULL,
    zone_id UUID REFERENCES warehouse_zones(id) ON DELETE CASCADE,
    row_number INT,
    column_number INT,
    level_number INT,
    max_capacity_kg NUMERIC(10,2),
    current_weight_kg NUMERIC(10,2) DEFAULT 0,
    status VARCHAR(30) DEFAULT 'Available'
);

CREATE TABLE inventory_categories (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL,
    description TEXT
);

CREATE TABLE inventory_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    item_code VARCHAR(50) UNIQUE NOT NULL,
    barcode VARCHAR(100) UNIQUE,
    qr_code VARCHAR(100) UNIQUE,
    name VARCHAR(255) NOT NULL,
    category_id UUID REFERENCES inventory_categories(id),
    brand VARCHAR(100),
    specification TEXT,
    unit VARCHAR(30) NOT NULL,
    primary_supplier_id UUID,
    buy_price NUMERIC(14,2),
    standard_price NUMERIC(14,2),
    min_stock INT DEFAULT 0,
    max_stock INT DEFAULT 0,
    safety_stock INT DEFAULT 0,
    lead_time_days INT DEFAULT 3,
    default_warehouse_id UUID REFERENCES warehouses(id),
    default_rack_id UUID REFERENCES warehouse_racks(id),
    status VARCHAR(30) DEFAULT 'Active',
    photo_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE inventory_stock (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    item_id UUID REFERENCES inventory_items(id) ON DELETE CASCADE,
    warehouse_id UUID REFERENCES warehouses(id) ON DELETE CASCADE,
    rack_id UUID REFERENCES warehouse_racks(id),
    available INT DEFAULT 0,
    reserved INT DEFAULT 0,
    allocated INT DEFAULT 0,
    in_transit INT DEFAULT 0,
    damaged INT DEFAULT 0,
    expired INT DEFAULT 0,
    on_order INT DEFAULT 0,
    stock_status VARCHAR(30) DEFAULT 'Normal',
    unit_value NUMERIC(14,2),
    total_value NUMERIC(16,2),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE inventory_movements (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    movement_number VARCHAR(100) UNIQUE NOT NULL,
    movement_type VARCHAR(50) NOT NULL,
    item_id UUID REFERENCES inventory_items(id),
    quantity INT NOT NULL,
    unit VARCHAR(30),
    source_location TEXT,
    destination_location TEXT,
    reference_number VARCHAR(100),
    actor_id UUID,
    actor_name VARCHAR(150),
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE purchase_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    pr_number VARCHAR(100) UNIQUE NOT NULL,
    requestor_id UUID NOT NULL,
    requestor_name VARCHAR(150),
    department VARCHAR(100),
    work_order_ref VARCHAR(100),
    priority VARCHAR(20) DEFAULT 'Normal',
    item_id UUID REFERENCES inventory_items(id),
    requested_quantity INT NOT NULL,
    estimated_total_cost NUMERIC(16,2),
    justification TEXT,
    status VARCHAR(30) DEFAULT 'Submitted',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE purchase_orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    po_number VARCHAR(100) UNIQUE NOT NULL,
    pr_id UUID REFERENCES purchase_requests(id),
    supplier_id UUID NOT NULL,
    supplier_name VARCHAR(255),
    po_date DATE NOT NULL,
    expected_delivery_date DATE,
    item_id UUID REFERENCES inventory_items(id),
    quantity INT NOT NULL,
    unit_price NUMERIC(14,2),
    total_amount NUMERIC(16,2),
    status VARCHAR(30) DEFAULT 'Issued',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE goods_receipts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    gr_number VARCHAR(100) UNIQUE NOT NULL,
    po_id UUID REFERENCES purchase_orders(id),
    warehouse_id UUID REFERENCES warehouses(id),
    officer_name VARCHAR(150),
    received_date DATE DEFAULT CURRENT_DATE,
    total_quantity INT,
    condition_status VARCHAR(50),
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
`;
