import {
  ChartOfAccount,
  JournalEntry,
  BankAccount,
  CashTransaction,
  SupplierInvoice,
  CustomerInvoice,
  BudgetCostCenter,
  FinancialRatioSummary,
  AiFinancialInsight,
} from './types';

export const INITIAL_COA: ChartOfAccount[] = [
  {
    id: 'coa-1',
    accountCode: '1101-001',
    accountName: 'Kas Kecil Estate (Petty Cash)',
    category: 'ASSET',
    level: 2,
    isParent: false,
    normalBalance: 'DEBIT',
    currentBalanceIdr: 45000000,
    costCenterCode: 'CC-EST-SEIRIAU',
    isActive: true,
  },
  {
    id: 'coa-2',
    accountCode: '1102-001',
    accountName: 'Bank Mandiri IDR - Rekening Operasional Kebun',
    category: 'ASSET',
    level: 2,
    isParent: false,
    normalBalance: 'DEBIT',
    currentBalanceIdr: 8450000000,
    costCenterCode: 'CC-HQ-FINANCE',
    isActive: true,
  },
  {
    id: 'coa-3',
    accountCode: '1102-002',
    accountName: 'Bank BRI IDR - Rekening Gaji & Payroll',
    category: 'ASSET',
    level: 2,
    isParent: false,
    normalBalance: 'DEBIT',
    currentBalanceIdr: 3120000000,
    costCenterCode: 'CC-HQ-HR',
    isActive: true,
  },
  {
    id: 'coa-4',
    accountCode: '1103-001',
    accountName: 'Piutang Penjualan CPO & PK (Refinery)',
    category: 'ASSET',
    level: 2,
    isParent: false,
    normalBalance: 'DEBIT',
    currentBalanceIdr: 4250000000,
    costCenterCode: 'CC-COMM-SALES',
    isActive: true,
  },
  {
    id: 'coa-5',
    accountCode: '1104-001',
    accountName: 'Persediaan Pupuk & Agrokimia Gudang Utama',
    category: 'ASSET',
    level: 2,
    isParent: false,
    normalBalance: 'DEBIT',
    currentBalanceIdr: 2180000000,
    costCenterCode: 'CC-WH-MAIN',
    isActive: true,
  },
  {
    id: 'coa-6',
    accountCode: '2101-001',
    accountName: 'Hutang Dagang Supplier Pupuk & Sparepart',
    category: 'LIABILITY',
    level: 2,
    isParent: false,
    normalBalance: 'CREDIT',
    currentBalanceIdr: 1850000000,
    costCenterCode: 'CC-PROCUREMENT',
    isActive: true,
  },
  {
    id: 'coa-7',
    accountCode: '2102-001',
    accountName: 'Hutang PPh 21 / 23 / PPN Kebun',
    category: 'LIABILITY',
    level: 2,
    isParent: false,
    normalBalance: 'CREDIT',
    currentBalanceIdr: 340000000,
    costCenterCode: 'CC-HQ-TAX',
    isActive: true,
  },
  {
    id: 'coa-8',
    accountCode: '3101-001',
    accountName: 'Modal Disetor PT Nusantara Palm Lestari',
    category: 'EQUITY',
    level: 1,
    isParent: false,
    normalBalance: 'CREDIT',
    currentBalanceIdr: 25000000000,
    costCenterCode: 'CC-HQ-EXEC',
    isActive: true,
  },
  {
    id: 'coa-9',
    accountCode: '4101-001',
    accountName: 'Pendapatan Penjualan CPO (Crude Palm Oil)',
    category: 'REVENUE',
    level: 1,
    isParent: false,
    normalBalance: 'CREDIT',
    currentBalanceIdr: 18200000000,
    costCenterCode: 'CC-MILL-SEIRIAU',
    isActive: true,
  },
  {
    id: 'coa-10',
    accountCode: '5101-001',
    accountName: 'Biaya Panen & Angkut TBS (Premi & Bensin)',
    category: 'COGS',
    level: 2,
    isParent: false,
    normalBalance: 'DEBIT',
    currentBalanceIdr: 4120000000,
    costCenterCode: 'CC-EST-HARVEST',
    isActive: true,
  },
];

export const INITIAL_JOURNALS: JournalEntry[] = [
  {
    id: 'jv-101',
    journalNo: 'JV-2026-08-001',
    transactionDate: '2026-08-01',
    sourceModule: 'HARVEST',
    referenceNo: 'TBS-DISPATCH-20260801-09',
    description: 'Automatic Posting: Penjualan TBS Panen Afdeling 1 ke PKS Mill',
    totalDebitIdr: 245000000,
    totalCreditIdr: 245000000,
    status: 'POSTED',
    createdBy: 'SYSTEM_HARVEST_INTEGRATION',
    approvedBy: 'Budi Rahardjo (Chief Accountant)',
    details: [
      {
        id: 'jvd-1',
        accountCode: '1103-001',
        accountName: 'Piutang Penjualan CPO & PK',
        debitAmountIdr: 245000000,
        creditAmountIdr: 0,
        costCenterCode: 'CC-MILL-SEIRIAU',
        memo: 'Penyerahan 182 Ton TBS Rendemen OER 22.4%',
      },
      {
        id: 'jvd-2',
        accountCode: '4101-001',
        accountName: 'Pendapatan Penjualan CPO',
        debitAmountIdr: 0,
        creditAmountIdr: 245000000,
        costCenterCode: 'CC-MILL-SEIRIAU',
        memo: 'Recognized TBS Sales Revenue',
      },
    ],
  },
  {
    id: 'jv-102',
    journalNo: 'JV-2026-08-002',
    transactionDate: '2026-08-02',
    sourceModule: 'PAYROLL',
    referenceNo: 'PAYROLL-JULY-2026-ALL',
    description: 'Automatic Posting: Gaji & Premi Pemanen BHL + BPJS Ketenagakerjaan',
    totalDebitIdr: 1120000000,
    totalCreditIdr: 1120000000,
    status: 'POSTED',
    createdBy: 'SYSTEM_HRM_PAYROLL',
    approvedBy: 'Budi Rahardjo (Chief Accountant)',
    details: [
      {
        id: 'jvd-3',
        accountCode: '5101-001',
        accountName: 'Biaya Panen & Angkut TBS',
        debitAmountIdr: 1120000000,
        creditAmountIdr: 0,
        costCenterCode: 'CC-EST-HARVEST',
        memo: 'Beban Gaji & Premi Panen Periode Juli 2026',
      },
      {
        id: 'jvd-4',
        accountCode: '1102-002',
        accountName: 'Bank BRI IDR - Rekening Gaji',
        debitAmountIdr: 0,
        creditAmountIdr: 1120000000,
        costCenterCode: 'CC-HQ-HR',
        memo: 'Transfer Direct Payroll Mandiri/BRI',
      },
    ],
  },
  {
    id: 'jv-103',
    journalNo: 'JV-2026-08-003',
    transactionDate: '2026-08-03',
    sourceModule: 'EAM_WORKSHOP',
    referenceNo: 'EAM-WO-SPAREPART-084',
    description: 'Posting Pemakaian Sparepart Heavy Fleet CAT 320D Excavator',
    totalDebitIdr: 85000000,
    totalCreditIdr: 85000000,
    status: 'DRAFT',
    createdBy: 'Ahmad Supardi (Workshop Manager)',
    details: [
      {
        id: 'jvd-5',
        accountCode: '5101-001',
        accountName: 'Biaya Maintenance Alat Berat',
        debitAmountIdr: 85000000,
        creditAmountIdr: 0,
        costCenterCode: 'CC-WORKSHOP',
        memo: 'Penggantian Filter Hydraulic & Oil Seal CAT 320D',
      },
      {
        id: 'jvd-6',
        accountCode: '1104-001',
        accountName: 'Persediaan Sparepart Gudang',
        debitAmountIdr: 0,
        creditAmountIdr: 85000000,
        costCenterCode: 'CC-WH-MAIN',
        memo: 'Pengeluaran Barang Bukti Outbound WO-084',
      },
    ],
  },
];

export const INITIAL_BANK_ACCOUNTS: BankAccount[] = [
  {
    id: 'bnk-1',
    bankName: 'Bank Mandiri (Persero) Tbk',
    branchName: 'KCP Pekanbaru Sudirman',
    accountNumber: '108-00-1928374-1',
    currency: 'IDR',
    balanceIdr: 8450000000,
    picName: 'Siti Rahmawati (Treasury Manager)',
    status: 'ACTIVE',
  },
  {
    id: 'bnk-2',
    bankName: 'Bank Rakyat Indonesia (BRI)',
    branchName: 'KCP Kandis Dumai',
    accountNumber: '0192-01-009823-50-8',
    currency: 'IDR',
    balanceIdr: 3120000000,
    picName: 'Rudi Hartono (Finance Staff Estate)',
    status: 'ACTIVE',
  },
];

export const INITIAL_CASH_TRANSACTIONS: CashTransaction[] = [
  {
    id: 'ctx-1',
    trxNo: 'CSH-IN-202608-01',
    trxType: 'CASH_IN',
    accountName: 'Kas Kecil Estate',
    categoryName: 'Pengisian Kembali Kas Kecil (Petty Cash)',
    amountIdr: 25000000,
    date: '2026-08-01',
    description: 'Reimbursement Petty Cash Operasional Kebun Kantor Afdeling',
    recipientOrSource: 'Bank Mandiri Treasury',
    status: 'COMPLETED',
  },
  {
    id: 'ctx-2',
    trxNo: 'CSH-OUT-202608-02',
    trxType: 'CASH_OUT',
    accountName: 'Kas Kecil Estate',
    categoryName: 'Operasional Transport & Solar Darurat',
    amountIdr: 4800000,
    date: '2026-08-02',
    description: 'Pembelian Solar Eceran Darurat Fleet Truck Dumptruck 04',
    recipientOrSource: 'SPBU SP3 Kandis',
    status: 'COMPLETED',
  },
];

export const INITIAL_SUPPLIER_INVOICES: SupplierInvoice[] = [
  {
    id: 'sinv-1',
    invoiceNo: 'INV-PETRO-2026-881',
    poReferenceNo: 'PO-2026-PUPUK-042',
    supplierName: 'PT Petrokimia Gresik / Distributor Riau',
    invoiceDate: '2026-07-20',
    dueDate: '2026-08-20',
    amountIdr: 1250000000,
    paidAmountIdr: 400000000,
    remainingAmountIdr: 850000000,
    status: 'PARTIAL',
  },
  {
    id: 'sinv-2',
    invoiceNo: 'INV-TRAKTOR-2026-019',
    poReferenceNo: 'PO-2026-SPAREPART-102',
    supplierName: 'PT United Tractors Tbk',
    invoiceDate: '2026-07-25',
    dueDate: '2026-08-10',
    amountIdr: 600000000,
    paidAmountIdr: 0,
    remainingAmountIdr: 600000000,
    status: 'UNPAID',
  },
];

export const INITIAL_CUSTOMER_INVOICES: CustomerInvoice[] = [
  {
    id: 'cinv-1',
    invoiceNo: 'INV-WILMAR-2026-004',
    contractReferenceNo: 'CTR-CPO-2026-WILMAR-01',
    customerName: 'PT Wilmar Bioenergi Indonesia (Refinery Dumai)',
    productType: 'CPO_CRUDE_PALM_OIL',
    quantityTons: 850,
    invoiceDate: '2026-07-28',
    dueDate: '2026-08-15',
    amountIdr: 10625000000, // 850 ton * Rp 12.500/kg
    paidAmountIdr: 6375000000,
    remainingAmountIdr: 4250000000,
    status: 'PARTIAL',
  },
  {
    id: 'cinv-2',
    invoiceNo: 'INV-GAR-2026-012',
    contractReferenceNo: 'CTR-PK-2026-GAR-03',
    customerName: 'PT Golden Agri Resources (GAR)',
    productType: 'PK_PALM_KERNEL',
    quantityTons: 210,
    invoiceDate: '2026-08-01',
    dueDate: '2026-08-25',
    amountIdr: 1890000000,
    paidAmountIdr: 1890000000,
    remainingAmountIdr: 0,
    status: 'PAID',
  },
];

export const INITIAL_BUDGET_COST_CENTERS: BudgetCostCenter[] = [
  {
    id: 'bcc-1',
    costCenterCode: 'CC-EST-HARVEST',
    costCenterName: 'Biaya Panen & Angkut TBS (Estate Sei Riau)',
    annualBudgetIdr: 12000000000,
    ytdActualCostIdr: 7120000000,
    utilizationPercent: 59.3,
    costPerHectareIdr: 2848000,
    costPerTonTbsIdr: 142400,
    status: 'NORMAL',
  },
  {
    id: 'bcc-2',
    costCenterCode: 'CC-EST-FERTILIZER',
    costCenterName: 'Pemupukan NPK & Organik (Estate Sei Riau)',
    annualBudgetIdr: 8500000000,
    ytdActualCostIdr: 6800000000,
    utilizationPercent: 80.0,
    costPerHectareIdr: 2720000,
    costPerTonTbsIdr: 136000,
    status: 'WARNING_NEAR_LIMIT',
  },
  {
    id: 'bcc-3',
    costCenterCode: 'CC-MILL-OER-COST',
    costCenterName: 'Operasional Pabrik PKS (Pengolahan TBS to CPO)',
    annualBudgetIdr: 15000000000,
    ytdActualCostIdr: 8400000000,
    utilizationPercent: 56.0,
    costPerHectareIdr: 3360000,
    costPerTonTbsIdr: 168000,
    status: 'NORMAL',
  },
];

export const INITIAL_FINANCIAL_RATIOS: FinancialRatioSummary = {
  currentRatio: 2.85,
  quickRatio: 2.12,
  debtToEquityRatio: 0.38,
  grossProfitMarginPercent: 32.4,
  netProfitMarginPercent: 18.6,
  costPerTonCpoIdr: 8250000,
  costPerHectareHaIdr: 8920000,
};

export const INITIAL_AI_FINANCIAL_INSIGHTS: AiFinancialInsight[] = [
  {
    id: 'afi-1',
    metricType: 'CASH_FLOW_PREDICTION',
    summary: 'Proyeksi Cash Inflow Rp 12.5 Miliar dalam 14 hari dari Pelunasan Customer Invoice PT Wilmar Bioenergi.',
    confidencePercent: 94.2,
    recommendation: 'Alokasikan Rp 2.5 Miliar untuk pembayaran awal pupuk Petrokimia guna mendapatkan diskon termin early-payment 3%.',
    severity: 'LOW',
  },
  {
    id: 'afi-2',
    metricType: 'COST_OPTIMIZATION',
    summary: 'Anomali Biaya BBM Solar Workshop Dumptruck 04 naik +18% dibandingkan rata-rata fleet Afdeling 2.',
    confidencePercent: 91.8,
    recommendation: 'Periksa kalibrasi injektor solar & rute pengangkutan TBS dari TPH Afdeling 2 ke Timbangan PKS.',
    severity: 'HIGH',
  },
  {
    id: 'afi-3',
    metricType: 'TAX_RECOMMENDATION',
    summary: 'Restitusi PPN Kurang Bayar Masa Juli 2026 telah diverifikasi siap diajukan ke Kantor Pajak Pekanbaru.',
    confidencePercent: 98.0,
    recommendation: 'Lakukan finalisasi e-Faktur PPN Masa sebelum tanggal 10 bulan berjalan.',
    severity: 'MEDIUM',
  },
];
