import {
  HarvestPlanRecord,
  HarvestScheduleRecord,
  HarvestTeamRecord,
  HarvestAssignmentRecord,
  HarvestExecutionRecord,
  HarvestCollectionPointRecord,
  HarvestGradingRecord,
  HarvestQcRecord,
  WeighbridgeRecord,
  TransportDispatchRecord,
  MillDeliveryRecord,
  HarvestProductivityRecord,
  HarvestLossRecord,
  HarvestForecastRecord,
  HarvestTimelineEvent,
  HarvestGalleryItem,
  QrBarcodeRegistryItem,
  AiHarvestInsight,
} from './types';

// Mock Plans
export const INITIAL_HARVEST_PLANS: HarvestPlanRecord[] = [
  {
    id: 'hp-001',
    planCode: 'PLN-2026-H01',
    programName: 'Program Panen Puncak Rotasi 1',
    companyName: 'PT Sawit Nusantara Mandiri',
    estateName: 'Nusa Indah Estate',
    divisionName: 'Division 1 - Agronomi',
    afdelingName: 'Afdeling A',
    blockCode: 'BLK-A12',
    subBlockCode: 'A12-North',
    harvestDate: '2026-08-04',
    estimatedBunches: 1850,
    estimatedTonnageTon: 33.3,
    estimatedBjrKg: 18.0,
    priority: 'High',
    picName: 'Ahmad Subagyo (Assistant Afdeling)',
    status: 'In Progress',
    notes: 'Prioritas rotasi 8 hari, tingkat kerapatan matang panen 85%.',
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'hp-002',
    planCode: 'PLN-2026-H02',
    programName: 'Rotasi Rutin 9 Hari',
    companyName: 'PT Sawit Nusantara Mandiri',
    estateName: 'Nusa Indah Estate',
    divisionName: 'Division 1 - Agronomi',
    afdelingName: 'Afdeling B',
    blockCode: 'BLK-B04',
    subBlockCode: 'B04-East',
    harvestDate: '2026-08-04',
    estimatedBunches: 1420,
    estimatedTonnageTon: 26.27,
    estimatedBjrKg: 18.5,
    priority: 'Medium',
    picName: 'Budi Santoso (Assistant Afdeling)',
    status: 'Scheduled',
    notes: 'Kondisi pasar pikul bersih, siap angkong.',
    createdAt: '2026-08-02T09:15:00Z',
  },
  {
    id: 'hp-003',
    planCode: 'PLN-2026-H03',
    programName: 'Panen Sapu Bersih Restan',
    companyName: 'PT Sawit Nusantara Mandiri',
    estateName: 'Sejahtera Estate',
    divisionName: 'Division 2 - Operasional',
    afdelingName: 'Afdeling C',
    blockCode: 'BLK-C08',
    subBlockCode: 'C08-South',
    harvestDate: '2026-08-05',
    estimatedBunches: 2100,
    estimatedTonnageTon: 40.95,
    estimatedBjrKg: 19.5,
    priority: 'Urgent',
    picName: 'Chandra Wijaya (Mandor Utama)',
    status: 'Planned',
    notes: 'Kawasan rawan restan, tambah armada truk pengangkut.',
    createdAt: '2026-08-03T07:30:00Z',
  },
];

// Mock Schedules
export const INITIAL_HARVEST_SCHEDULES: HarvestScheduleRecord[] = [
  {
    id: 'hs-101',
    scheduleCode: 'SCH-ROT-01',
    blockCode: 'BLK-A12',
    estateName: 'Nusa Indah Estate',
    afdelingName: 'Afdeling A',
    frequency: 'Rotation (7-10 Days)',
    startDate: '2026-08-01',
    endDate: '2026-08-31',
    assignedTeamName: 'Regu Panen Harimau 1',
    targetTonnageTon: 180.0,
    status: 'Active',
  },
  {
    id: 'hs-102',
    scheduleCode: 'SCH-ROT-02',
    blockCode: 'BLK-B04',
    estateName: 'Nusa Indah Estate',
    afdelingName: 'Afdeling B',
    frequency: 'Rotation (7-10 Days)',
    startDate: '2026-08-02',
    endDate: '2026-08-31',
    assignedTeamName: 'Regu Panen Rajawali 2',
    targetTonnageTon: 155.0,
    status: 'Active',
  },
];

// Mock Teams
export const INITIAL_HARVEST_TEAMS: HarvestTeamRecord[] = [
  {
    id: 'ht-01',
    teamCode: 'TM-HRM-01',
    teamName: 'Regu Panen Harimau 1',
    mandorName: 'Mandor Suparno',
    supervisorName: 'Spv. Bambang Haryono',
    harvestersCount: 12,
    looseFruitPickersCount: 6,
    helpersCount: 2,
    assignedTruckNo: 'BK 8492 C',
    equipmentSummary: '12 Egrek, 12 Angkong, 6 Tojok, 24 Karung Brondolan',
    status: 'On Duty',
  },
  {
    id: 'ht-02',
    teamCode: 'TM-RJW-02',
    teamName: 'Regu Panen Rajawali 2',
    mandorName: 'Mandor Wawan',
    supervisorName: 'Spv. Bambang Haryono',
    harvestersCount: 10,
    looseFruitPickersCount: 5,
    helpersCount: 2,
    assignedTruckNo: 'BK 9102 FB',
    equipmentSummary: '10 Dodos/Egrek, 10 Angkong, 5 Tojok',
    status: 'On Duty',
  },
  {
    id: 'ht-03',
    teamCode: 'TM-GDR-03',
    teamName: 'Regu Panen Garuda 3',
    mandorName: 'Mandor Agus',
    supervisorName: 'Spv. Triyadi',
    harvestersCount: 14,
    looseFruitPickersCount: 7,
    helpersCount: 3,
    assignedTruckNo: 'BK 7721 XX',
    equipmentSummary: '14 Egrek Teleskopik, 14 Angkong Heavy Duty',
    status: 'Active',
  },
];

// Mock Assignments
export const INITIAL_HARVEST_ASSIGNMENTS: HarvestAssignmentRecord[] = [
  {
    id: 'ha-01',
    assignmentCode: 'ASN-PAN-881',
    teamName: 'Regu Panen Harimau 1',
    mandorName: 'Mandor Suparno',
    assignmentType: 'Single Block',
    blockCodes: ['BLK-A12'],
    targetBunches: 1850,
    targetTonnageTon: 33.3,
    dateAssigned: '2026-08-04',
    gpsTargetLat: 2.9102,
    gpsTargetLng: 99.1234,
    status: 'In Execution',
  },
  {
    id: 'ha-02',
    assignmentCode: 'ASN-PAN-882',
    teamName: 'Regu Panen Rajawali 2',
    mandorName: 'Mandor Wawan',
    assignmentType: 'Multiple Block',
    blockCodes: ['BLK-B04', 'BLK-B05'],
    targetBunches: 2100,
    targetTonnageTon: 38.8,
    dateAssigned: '2026-08-04',
    gpsTargetLat: 2.9155,
    gpsTargetLng: 99.1288,
    status: 'In Execution',
  },
];

// Mock Executions
export const INITIAL_HARVEST_EXECUTIONS: HarvestExecutionRecord[] = [
  {
    id: 'he-001',
    executionCode: 'HEX-88101',
    date: '2026-08-04',
    time: '07:45 AM',
    companyName: 'PT Sawit Nusantara Mandiri',
    estateName: 'Nusa Indah Estate',
    divisionName: 'Division 1 - Agronomi',
    afdelingName: 'Afdeling A',
    blockCode: 'BLK-A12',
    subBlockCode: 'A12-North',
    teamName: 'Regu Panen Harimau 1',
    harvesterName: 'Sugianto (Pemanen 04)',
    ancakNo: 'Ancak #08',
    bunchesCount: 145,
    estimatedWeightKg: 2610,
    calculatedBjrKg: 18.0,
    looseFruitKg: 120,
    qualityGrade: 'A (Mature)',
    photoUrl: 'https://images.unsplash.com/photo-1595246140625-573b715d11dc?auto=format&fit=crop&w=600&q=80',
    gpsLat: 2.9102,
    gpsLng: 99.1234,
    notes: 'Buah matang sempurna, tangkai dipotong pendek berbentuk cangkram.',
  },
  {
    id: 'he-002',
    executionCode: 'HEX-88102',
    date: '2026-08-04',
    time: '08:30 AM',
    companyName: 'PT Sawit Nusantara Mandiri',
    estateName: 'Nusa Indah Estate',
    divisionName: 'Division 1 - Agronomi',
    afdelingName: 'Afdeling A',
    blockCode: 'BLK-A12',
    subBlockCode: 'A12-North',
    teamName: 'Regu Panen Harimau 1',
    harvesterName: 'Joko Susilo (Pemanen 09)',
    ancakNo: 'Ancak #09',
    bunchesCount: 160,
    estimatedWeightKg: 2880,
    calculatedBjrKg: 18.0,
    looseFruitKg: 140,
    qualityGrade: 'A (Mature)',
    photoUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=600&q=80',
    gpsLat: 2.9105,
    gpsLng: 99.1238,
    notes: 'Terdapat 3 janjang agak mentah tapi masuk toleransi.',
  },
  {
    id: 'he-003',
    executionCode: 'HEX-88201',
    date: '2026-08-04',
    time: '09:10 AM',
    companyName: 'PT Sawit Nusantara Mandiri',
    estateName: 'Nusa Indah Estate',
    divisionName: 'Division 1 - Agronomi',
    afdelingName: 'Afdeling B',
    blockCode: 'BLK-B04',
    subBlockCode: 'B04-East',
    teamName: 'Regu Panen Rajawali 2',
    harvesterName: 'Rudi Hartono (Pemanen 02)',
    ancakNo: 'Ancak #01',
    bunchesCount: 130,
    estimatedWeightKg: 2405,
    calculatedBjrKg: 18.5,
    looseFruitKg: 95,
    qualityGrade: 'A (Mature)',
    photoUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=600&q=80',
    gpsLat: 2.9155,
    gpsLng: 99.1288,
    notes: 'Pasar pikul bersih, brondolan terkutip rapat.',
  },
];

// Mock Collections (TPH)
export const INITIAL_HARVEST_COLLECTIONS: HarvestCollectionPointRecord[] = [
  {
    id: 'hcp-01',
    collectionPointCode: 'TPH-A12-01',
    blockCode: 'BLK-A12',
    totalBunchesCount: 305,
    totalLooseFruitKg: 260,
    pickupTime: '10:15 AM',
    assignedTruckNo: 'BK 8492 C',
    status: 'Loaded & Dispatched',
    photoUrl: 'https://images.unsplash.com/photo-1595246140625-573b715d11dc?auto=format&fit=crop&w=600&q=80',
    gpsLat: 2.9102,
    gpsLng: 99.1234,
  },
  {
    id: 'hcp-02',
    collectionPointCode: 'TPH-A12-02',
    blockCode: 'BLK-A12',
    totalBunchesCount: 280,
    totalLooseFruitKg: 210,
    pickupTime: '11:00 AM',
    assignedTruckNo: 'BK 8492 C',
    status: 'In Loading',
    photoUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=600&q=80',
    gpsLat: 2.9108,
    gpsLng: 99.1240,
  },
  {
    id: 'hcp-03',
    collectionPointCode: 'TPH-B04-01',
    blockCode: 'BLK-B04',
    totalBunchesCount: 420,
    totalLooseFruitKg: 350,
    pickupTime: undefined,
    assignedTruckNo: 'BK 9102 FB',
    status: 'Waiting Pickup',
    photoUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=600&q=80',
    gpsLat: 2.9155,
    gpsLng: 99.1288,
  },
];

// Mock Gradings
export const INITIAL_HARVEST_GRADINGS: HarvestGradingRecord[] = [
  {
    id: 'hg-01',
    gradingCode: 'GRD-TPH-A12-01',
    tphCode: 'TPH-A12-01',
    blockCode: 'BLK-A12',
    graderName: 'QC Inspector Hendra',
    date: '2026-08-04',
    rawPct: 1.2,
    underRipePct: 3.5,
    ripePct: 91.8,
    overRipePct: 2.5,
    rottenPct: 0.5,
    emptyBunchesPct: 0.0,
    abnormalPct: 0.5,
    longStalkPct: 1.0,
    notes: 'Kualitas TBS sangat memuaskan, kematangan standar Pabrik PKS 91%+',
    photoUrl: 'https://images.unsplash.com/photo-1595246140625-573b715d11dc?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'hg-02',
    gradingCode: 'GRD-TPH-B04-01',
    tphCode: 'TPH-B04-01',
    blockCode: 'BLK-B04',
    graderName: 'QC Inspector Hendra',
    date: '2026-08-04',
    rawPct: 2.8,
    underRipePct: 5.2,
    ripePct: 88.0,
    overRipePct: 3.0,
    rottenPct: 0.8,
    emptyBunchesPct: 0.2,
    abnormalPct: 0.0,
    longStalkPct: 2.5,
    notes: 'Ditemukan beberapa tangkai panjang > 2.5 cm, perlu perapihan oleh pemanen.',
    photoUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=600&q=80',
  },
];

// Mock QC Records
export const INITIAL_HARVEST_QC: HarvestQcRecord[] = [
  {
    id: 'hqc-01',
    qcCode: 'QC-BLK-A12-AUG04',
    blockCode: 'BLK-A12',
    inspectorName: 'Asisten QC Ir. Rahmad',
    date: '2026-08-04',
    fruitQualityScore: 94,
    leftoverBunchesCount: 2,
    leftoverLooseFruitScore: 92,
    frondPruningScore: 96,
    ancakQualityScore: 95,
    overallScore: 94.2,
    status: 'Passed',
    photoUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=600&q=80',
    gpsLat: 2.9102,
    gpsLng: 99.1234,
  },
];

// Mock Weighbridge Transactions
export const INITIAL_WEIGHBRIDGE_RECORDS: WeighbridgeRecord[] = [
  {
    id: 'wb-9001',
    weighTicketNo: 'WB-PKS1-20260804-001',
    date: '2026-08-04',
    timeIn: '10:45 AM',
    timeOut: '11:15 AM',
    truckNo: 'BK 8492 C',
    driverName: 'Sujono (Driver 01)',
    grossWeightKg: 24850,
    tareWeightKg: 8200,
    netWeightKg: 16650,
    supplierEstate: 'Nusa Indah Estate (Afdeling A)',
    millName: 'PKS PalmVision Central Mill',
    status: 'Completed',
    qrCodeTicket: 'QR-WB-PKS1-20260804-001',
  },
  {
    id: 'wb-9002',
    weighTicketNo: 'WB-PKS1-20260804-002',
    date: '2026-08-04',
    timeIn: '11:30 AM',
    timeOut: undefined,
    truckNo: 'BK 9102 FB',
    driverName: 'Eko Prasetyo (Driver 03)',
    grossWeightKg: 26100,
    tareWeightKg: 0,
    netWeightKg: 0,
    supplierEstate: 'Nusa Indah Estate (Afdeling B)',
    millName: 'PKS PalmVision Central Mill',
    status: 'First Weighing (Bruto)',
    qrCodeTicket: 'QR-WB-PKS1-20260804-002',
  },
];

// Mock Transport Dispatches
export const INITIAL_TRANSPORT_DISPATCHES: TransportDispatchRecord[] = [
  {
    id: 'td-501',
    dispatchNo: 'DO-TBS-20260804-01',
    truckNo: 'BK 8492 C',
    driverName: 'Sujono',
    loaderTeamName: 'Tim Muat TPH 01',
    tphCollectionPoints: ['TPH-A12-01', 'TPH-A12-02'],
    destinationMill: 'PKS PalmVision Central Mill',
    estimatedTonnageTon: 16.5,
    departureTime: '10:20 AM',
    arrivalTimeEstimate: '10:45 AM',
    gpsRouteStatus: 'Arrived',
    status: 'Weighed',
  },
  {
    id: 'td-502',
    dispatchNo: 'DO-TBS-20260804-02',
    truckNo: 'BK 9102 FB',
    driverName: 'Eko Prasetyo',
    loaderTeamName: 'Tim Muat TPH 02',
    tphCollectionPoints: ['TPH-B04-01'],
    destinationMill: 'PKS PalmVision Central Mill',
    estimatedTonnageTon: 18.2,
    departureTime: '11:10 AM',
    arrivalTimeEstimate: '11:35 AM',
    gpsRouteStatus: 'On Schedule',
    status: 'In Transit',
  },
];

// Mock Deliveries to Mill
export const INITIAL_MILL_DELIVERIES: MillDeliveryRecord[] = [
  {
    id: 'md-301',
    deliveryCode: 'DEL-PKS-001',
    millName: 'PKS PalmVision Central Mill',
    deliveryDate: '2026-08-04',
    truckNo: 'BK 8492 C',
    weighTicketNo: 'WB-PKS1-20260804-001',
    netWeightTon: 16.65,
    cpoExtractionRatePct: 22.8,
    kernelExtractionRatePct: 5.4,
    documentStatus: 'Verified',
    photoUrl: 'https://images.unsplash.com/photo-1595246140625-573b715d11dc?auto=format&fit=crop&w=600&q=80',
  },
];

// Mock Productivity
export const INITIAL_HARVEST_PRODUCTIVITY: HarvestProductivityRecord[] = [
  {
    id: 'hp-prod-01',
    entityName: 'BLK-A12',
    entityType: 'Block',
    period: '2026-08',
    tonnageProducedTon: 124.5,
    bunchesCount: 6916,
    avgBjrKg: 18.0,
    productivityPerHarvesterTon: 1.85,
    achievementVsTargetPct: 104.2,
  },
  {
    id: 'hp-prod-02',
    entityName: 'Regu Panen Harimau 1',
    entityType: 'Team',
    period: '2026-08',
    tonnageProducedTon: 184.5,
    bunchesCount: 10250,
    avgBjrKg: 18.0,
    productivityPerHarvesterTon: 2.15,
    achievementVsTargetPct: 108.5,
  },
  {
    id: 'hp-prod-03',
    entityName: 'Nusa Indah Estate',
    entityType: 'Estate',
    period: '2026-08',
    tonnageProducedTon: 485.0,
    bunchesCount: 26500,
    avgBjrKg: 18.3,
    productivityPerHarvesterTon: 1.92,
    achievementVsTargetPct: 98.4,
  },
];

// Mock Harvest Losses
export const INITIAL_HARVEST_LOSSES: HarvestLossRecord[] = [
  {
    id: 'hl-101',
    lossCode: 'LSS-202608-01',
    blockCode: 'BLK-A12',
    date: '2026-08-03',
    category: 'Buah Tinggal',
    estimatedLossKg: 180,
    estimatedFinancialLossIdr: 450000,
    rootCause: 'Egrek pemanen patah di ujung ancak, 2 pohon tidak terjangkau.',
    correctiveAction: 'Sapu ancak ulang oleh helper regu sore hari.',
  },
  {
    id: 'hl-102',
    lossCode: 'LSS-202608-02',
    blockCode: 'BLK-B04',
    date: '2026-08-03',
    category: 'Brondolan Tinggal',
    estimatedLossKg: 95,
    estimatedFinancialLossIdr: 237500,
    rootCause: 'Pengutip brondolan terburu-buru mengejar target TPH.',
    correctiveAction: 'Pemberian instruksi ulang oleh Mandor Wawan & pengutipan sapu bersih.',
  },
];

// Mock Forecasts
export const INITIAL_HARVEST_FORECASTS: HarvestForecastRecord[] = [
  {
    id: 'fc-01',
    forecastPeriod: '7 Days',
    estateName: 'Nusa Indah Estate',
    predictedTonnageTon: 245.0,
    predictedBunches: 13600,
    confidenceScorePct: 94.5,
    harvestReadinessIndex: 'Peak',
  },
  {
    id: 'fc-02',
    forecastPeriod: '30 Days',
    estateName: 'Nusa Indah Estate',
    predictedTonnageTon: 980.0,
    predictedBunches: 54400,
    confidenceScorePct: 91.2,
    harvestReadinessIndex: 'Optimal',
  },
];

// Mock Timelines
export const INITIAL_HARVEST_TIMELINE: HarvestTimelineEvent[] = [
  {
    id: 'htl-01',
    stage: 'Planning',
    title: 'Perencanaan Panen Rotasi 1 Disetujui',
    timestamp: '2026-08-01 08:00',
    actorName: 'Ir. Rahmad (Estate Manager)',
    blockOrEntity: 'BLK-A12',
    details: 'Target produksi 33.3 Ton disetujui dengan rotasi 8 hari.',
    statusBadge: 'Planned',
  },
  {
    id: 'htl-02',
    stage: 'Assignment',
    title: 'Penugasan Regu Panen Harimau 1',
    timestamp: '2026-08-04 06:30',
    actorName: 'Mandor Suparno',
    blockOrEntity: 'BLK-A12',
    details: '12 Pemanen & 6 Pengutip Brondolan dikerahkan ke ancak #01 - #12.',
    statusBadge: 'Assigned',
  },
  {
    id: 'htl-03',
    stage: 'Harvest',
    title: 'Pemanenan TBS & Brondolan Selesai',
    timestamp: '2026-08-04 09:45',
    actorName: 'Regu Panen Harimau 1',
    blockOrEntity: 'BLK-A12',
    details: 'Total 585 Janjang dipanen & diangkong ke TPH-A12-01 & 02.',
    statusBadge: 'Harvested',
  },
  {
    id: 'htl-04',
    stage: 'Grading',
    title: 'Inspeksi Digital Grading TPH',
    timestamp: '2026-08-04 10:00',
    actorName: 'QC Inspector Hendra',
    blockOrEntity: 'TPH-A12-01',
    details: '91.8% Matang Sempurna, 3.5% Kurang Matang, 0% Kosong.',
    statusBadge: 'Graded',
  },
  {
    id: 'htl-05',
    stage: 'Transport',
    title: 'Pemuatan Truk & Surat Pengantar Tandan (SPT)',
    timestamp: '2026-08-04 10:20',
    actorName: 'Sujono (Driver BK 8492 C)',
    blockOrEntity: 'TPH-A12-01',
    details: 'Delivery Order DO-TBS-20260804-01 diterbitkan menuju PKS.',
    statusBadge: 'Dispatched',
  },
  {
    id: 'htl-06',
    stage: 'Weighing',
    title: 'Penimbangan Jembatan Timbang PKS (Gross/Netto)',
    timestamp: '2026-08-04 11:15',
    actorName: 'Petugas Timbang PKS',
    blockOrEntity: 'PKS Central Mill',
    details: 'Bruto 24,850 Kg - Tara 8,200 Kg = Netto 16,650 Kg TBS Valid.',
    statusBadge: 'Weighed',
  },
];

// Mock Gallery
export const INITIAL_HARVEST_GALLERY: HarvestGalleryItem[] = [
  {
    id: 'gal-01',
    title: 'Tumpukan TBS Segar Hasil Panen Blok A12',
    category: 'TPH Collection',
    photoUrl: 'https://images.unsplash.com/photo-1595246140625-573b715d11dc?auto=format&fit=crop&w=600&q=80',
    date: '2026-08-04',
    time: '09:50 AM',
    blockCode: 'BLK-A12',
    capturedBy: 'QC Inspector Hendra',
    gpsLat: 2.9102,
    gpsLng: 99.1234,
    tags: ['TBS Matang', 'TPH A12-01', 'Grading A'],
  },
  {
    id: 'gal-02',
    title: 'Proses Pemuatan TBS ke Truk BK 8492 C',
    category: 'Transport Dispatch',
    photoUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=600&q=80',
    date: '2026-08-04',
    time: '10:15 AM',
    blockCode: 'BLK-A12',
    capturedBy: 'Driver Sujono',
    gpsLat: 2.9105,
    gpsLng: 99.1238,
    tags: ['Pemuatan Truk', 'Tojok TBS', 'Pengangkutan'],
  },
  {
    id: 'gal-03',
    title: 'Penimbangan Truk di Jembatan Timbang PKS',
    category: 'Weighbridge',
    photoUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=600&q=80',
    date: '2026-08-04',
    time: '10:50 AM',
    blockCode: 'PKS Mill',
    capturedBy: 'Operator Timbang PKS',
    gpsLat: 2.9210,
    gpsLng: 99.1450,
    tags: ['Weighbridge', 'Netto 16.65 Ton', 'PKS Central'],
  },
];

// Mock QR / Barcodes
export const INITIAL_QR_BARCODES: QrBarcodeRegistryItem[] = [
  {
    id: 'qr-01',
    codeType: 'Harvest Ticket',
    codeValue: 'HT-20260804-BLK-A12-01',
    qrDataUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=HT-20260804-BLK-A12-01',
    associatedEntity: 'Harvest Execution HEX-88101 (Blok A12)',
    issuedAt: '2026-08-04 07:45 AM',
    status: 'Valid',
  },
  {
    id: 'qr-02',
    codeType: 'Collection Ticket',
    codeValue: 'TPH-A12-01-QR',
    qrDataUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=TPH-A12-01-QR',
    associatedEntity: 'Tempat Pengumpulan Hasil TPH-A12-01',
    issuedAt: '2026-08-04 09:30 AM',
    status: 'Valid',
  },
  {
    id: 'qr-03',
    codeType: 'Weighbridge Ticket',
    codeValue: 'WB-PKS1-20260804-001',
    qrDataUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=WB-PKS1-20260804-001',
    associatedEntity: 'Slip Timbang BK 8492 C (Netto 16.65 Ton)',
    issuedAt: '2026-08-04 11:15 AM',
    status: 'Scanned & Closed',
  },
];

// Mock AI Harvest Insights
export const INITIAL_AI_HARVEST_INSIGHTS: AiHarvestInsight[] = [
  {
    id: 'ai-h-01',
    title: 'Prediksi Puncak Panen (Harvest Peak Optimization)',
    category: 'Harvest Readiness',
    blockCode: 'BLK-A12',
    confidenceScore: 96.4,
    insightText: 'Data spasial NDVI & akumulasi suhu harian menunjukkan Blok A12 memasuki puncak panen rotasi ke-3 dengan estimasi peningkatan tonase +18.5%.',
    recommendedAction: 'Tambah 2 tim pemanen cadangan dan alokasikan 1 unit truk ekstra pada rotasi berikutnya tanggal 12 Agustus.',
    severity: 'Success',
  },
  {
    id: 'ai-h-02',
    title: 'Deteksi Potensi Restan & Hambatan Pengangkutan',
    category: 'Transport Routing',
    blockCode: 'BLK-C08',
    confidenceScore: 91.8,
    insightText: 'Aktivitas hujan lokal diprediksi sore ini pukul 15:00 WIB di Afdeling C, yang dapat memperlambat truk melintasi jalan tanah Blok C08.',
    recommendedAction: 'Dahulukan pengangkutan TBS di TPH C08 sebelum pukul 13:30 WIB untuk mencegah restan buah di TPH.',
    severity: 'Warning',
  },
  {
    id: 'ai-h-03',
    title: 'Prediksi Antrian Jembatan Timbang PKS (Mill Queue Alert)',
    category: 'Mill Queue Prediction',
    blockCode: 'PKS Mill Central',
    confidenceScore: 93.1,
    insightText: 'Puncak kedatangan truk pengangkut TBS dari 3 Estate diperkirakan terjadi antara pukul 11:30 - 13:00 WIB (8-10 truk antri).',
    recommendedAction: 'Gunakan Jalur Express Weighbridge 2 bagi truk internal perusahaan dan atur jadwal kirim bergelombang.',
    severity: 'Info',
  },
];

// REST API Documentation
export const HARVEST_REST_API_DOCS = [
  { method: 'GET', path: '/api/v1/harvest/plans', description: 'Mengambil daftar perencanaan panen TBS per Blok / Afdeling' },
  { method: 'POST', path: '/api/v1/harvest/plans', description: 'Membuat program perencanaan panen baru' },
  { method: 'GET', path: '/api/v1/harvest/teams', description: 'Daftar regu pemanen, mandor, dan alokasi peralatan' },
  { method: 'POST', path: '/api/v1/harvest/executions', description: 'Input data eksekusi panen harian dari mobile mandor (Offline-sync friendly)' },
  { method: 'GET', path: '/api/v1/harvest/collections/tph', description: 'Daftar pengumpulan TBS di TPH (Tempat Pengumpulan Hasil)' },
  { method: 'POST', path: '/api/v1/harvest/gradings', description: 'Submit hasil inspeksi digital grading TBS di TPH' },
  { method: 'POST', path: '/api/v1/weighbridge/transactions', description: 'Record transaksi timbang bruto & tara truk TBS di PKS' },
  { method: 'GET', path: '/api/v1/transport/dispatches', description: 'Monitoring Surat Pengantar Tandan (SPT) & armada truk' },
  { method: 'GET', path: '/api/v1/harvest/analytics/productivity', description: 'Laporan pencapaian tonase, BJR, dan produktivitas pemanen' },
  { method: 'GET', path: '/api/v1/harvest/ai/forecast', description: 'Mengambil estimasi produksi panen berbasis AI Intelligence' },
];

// PostgreSQL Schema Documentation DDL
export const HARVEST_DB_SCHEMA_DOCS = `-- PostgreSQL Schema for Enterprise Harvest Management System (Prompt 8)

CREATE TABLE harvest_plans (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL,
  estate_id UUID NOT NULL,
  division_id UUID NOT NULL,
  afdeling_id UUID NOT NULL,
  block_id UUID NOT NULL,
  plan_code VARCHAR(50) UNIQUE NOT NULL,
  program_name VARCHAR(100) NOT NULL,
  harvest_date DATE NOT NULL,
  estimated_bunches INT DEFAULT 0,
  estimated_tonnage_ton NUMERIC(10,2) DEFAULT 0,
  estimated_bjr_kg NUMERIC(6,2) DEFAULT 0,
  priority VARCHAR(20) DEFAULT 'Medium',
  pic_name VARCHAR(100),
  status VARCHAR(30) DEFAULT 'Planned',
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE harvest_teams (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL,
  estate_id UUID NOT NULL,
  team_code VARCHAR(50) UNIQUE NOT NULL,
  team_name VARCHAR(100) NOT NULL,
  mandor_id UUID NOT NULL,
  supervisor_id UUID,
  harvesters_count INT DEFAULT 0,
  loose_fruit_pickers_count INT DEFAULT 0,
  helpers_count INT DEFAULT 0,
  equipment_summary TEXT,
  status VARCHAR(30) DEFAULT 'Active',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE harvest_executions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  block_id UUID NOT NULL,
  team_id UUID NOT NULL,
  execution_code VARCHAR(50) UNIQUE NOT NULL,
  date DATE NOT NULL,
  time TIME NOT NULL,
  harvester_name VARCHAR(100) NOT NULL,
  ancak_no VARCHAR(50),
  bunches_count INT DEFAULT 0,
  estimated_weight_kg NUMERIC(10,2) DEFAULT 0,
  calculated_bjr_kg NUMERIC(6,2) DEFAULT 0,
  loose_fruit_kg NUMERIC(8,2) DEFAULT 0,
  quality_grade VARCHAR(20) DEFAULT 'A (Mature)',
  photo_url TEXT,
  gps_lat NUMERIC(10,7),
  gps_lng NUMERIC(10,7),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE weighbridge_transactions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  weigh_ticket_no VARCHAR(50) UNIQUE NOT NULL,
  date DATE NOT NULL,
  time_in TIMESTAMP WITH TIME ZONE NOT NULL,
  time_out TIMESTAMP WITH TIME ZONE,
  truck_no VARCHAR(20) NOT NULL,
  driver_name VARCHAR(100) NOT NULL,
  gross_weight_kg NUMERIC(10,2) DEFAULT 0,
  tare_weight_kg NUMERIC(10,2) DEFAULT 0,
  net_weight_kg NUMERIC(10,2) DEFAULT 0,
  supplier_estate VARCHAR(100),
  mill_name VARCHAR(100),
  status VARCHAR(30) DEFAULT 'First Weighing',
  qr_code_ticket VARCHAR(100),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
`;
