import {
  Employee,
  OrganizationDepartment,
  JobVacancy,
  Applicant,
  OnboardingChecklist,
  AttendanceRecord,
  AttendanceCorrection,
  ShiftRoster,
  LeaveRequest,
  OvertimeRequest,
  PayrollPeriod,
  PayslipItem,
  BpjsConfigSummary,
  EmployeeLoan,
  TrainingProgram,
  EmployeeCertification,
  PerformanceKpi,
  VisitorLog,
  EmploymentContract,
  MedicalCheckupRecord,
  UniformDistribution,
  AiWorkforceInsight,
} from './types';

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-001',
    employeeId: 'EMP-2024-0101',
    nik: '1401021988050001',
    npwp: '84.192.304.1-213.000',
    bpjsKesehatan: '000192837482',
    bpjsKetenagakerjaan: '19028471928',
    name: 'Budi Santoso',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    gender: 'L',
    birthPlace: 'Pekanbaru',
    birthDate: '1988-05-12',
    religion: 'Islam',
    maritalStatus: 'MARRIED_K2',
    address: 'Perumahan Afdeling 1, Estate Sei Riau, Kampar',
    phone: '0812-7482-9102',
    email: 'budi.santoso@palmvision.ai',
    education: 'SMA Sederajat',
    bloodType: 'O',
    emergencyContact: {
      name: 'Siti Rahma',
      relationship: 'Istri',
      phone: '0813-9821-4019',
    },
    companyName: 'PT Nusantara Palm Lestari',
    estateName: 'Estate Sei Riau',
    divisionName: 'Afdeling I',
    departmentName: 'Panen & TPH (Harvesting)',
    positionTitle: 'Mandor Panen Utama',
    supervisorName: 'Ir. Ahmad Zulkarnain',
    employmentStatus: 'PERMANENT_SKU',
    joinDate: '2019-03-15',
    basicSalary: 4850000,
    bankAccount: {
      bankName: 'Bank Mandiri',
      accountNumber: '1080019283741',
      accountHolder: 'Budi Santoso',
    },
    activeStatus: 'ACTIVE',
  },
  {
    id: 'emp-002',
    employeeId: 'EMP-2025-0214',
    nik: '1401022001090004',
    npwp: '91.823.401.9-213.000',
    bpjsKesehatan: '000293847102',
    bpjsKetenagakerjaan: '20193847192',
    name: 'Joko Widodo (Pemanen)',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    gender: 'L',
    birthPlace: 'Bangkinang',
    birthDate: '2001-09-20',
    religion: 'Islam',
    maritalStatus: 'SINGLE',
    address: 'Mess Karyawan Blok B4, Estate Sei Riau',
    phone: '0821-8839-1029',
    email: 'joko.harvest@palmvision.ai',
    education: 'SMP',
    bloodType: 'A',
    emergencyContact: {
      name: 'Paimin',
      relationship: 'Ayah',
      phone: '0852-9182-3049',
    },
    companyName: 'PT Nusantara Palm Lestari',
    estateName: 'Estate Sei Riau',
    divisionName: 'Afdeling I',
    departmentName: 'Panen & TPH (Harvesting)',
    positionTitle: 'Pemanen TBS Senior (SKU-H)',
    supervisorName: 'Budi Santoso',
    employmentStatus: 'PERMANENT_SKU',
    joinDate: '2022-06-01',
    basicSalary: 3950000,
    bankAccount: {
      bankName: 'BRI',
      accountNumber: '0019283746192',
      accountHolder: 'Joko Widodo',
    },
    activeStatus: 'ACTIVE',
  },
  {
    id: 'emp-003',
    employeeId: 'EMP-2026-0309',
    nik: '1401051995110008',
    npwp: '73.918.234.1-213.000',
    bpjsKesehatan: '000394819203',
    bpjsKetenagakerjaan: '21029384710',
    name: 'Dewi Lestari',
    photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    gender: 'P',
    birthPlace: 'Medan',
    birthDate: '1995-11-08',
    religion: 'Kristen',
    maritalStatus: 'MARRIED_K0',
    address: 'Housing Perum PKS Blok A1, Kampar',
    phone: '0813-7728-1920',
    email: 'dewi.lestari@palmvision.ai',
    education: 'S1 Teknik Kimia',
    bloodType: 'B',
    emergencyContact: {
      name: 'Hendrik Simanjuntak',
      relationship: 'Suami',
      phone: '0812-9018-2938',
    },
    companyName: 'PT Nusantara Palm Lestari',
    estateName: 'PKS Kampar Mill',
    divisionName: 'Laboratorium PKS',
    departmentName: 'Processing & Quality Control',
    positionTitle: 'Quality Assurance Chemist',
    supervisorName: 'Ir. Hendra Wijaya',
    employmentStatus: 'PERMANENT_SKU',
    joinDate: '2021-01-10',
    basicSalary: 6750000,
    bankAccount: {
      bankName: 'Bank Mandiri',
      accountNumber: '1080098765432',
      accountHolder: 'Dewi Lestari',
    },
    activeStatus: 'ACTIVE',
  },
  {
    id: 'emp-004',
    employeeId: 'EMP-2026-0412',
    nik: '1401021992030005',
    npwp: '62.918.203.4-213.000',
    bpjsKesehatan: '000492819203',
    bpjsKetenagakerjaan: '22019283746',
    name: 'Rahmat Hidayat',
    photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
    gender: 'L',
    birthPlace: 'Dumai',
    birthDate: '1992-03-14',
    religion: 'Islam',
    maritalStatus: 'MARRIED_K1',
    address: 'Afdeling II Mess B, Estate Sei Riau',
    phone: '0853-9182-3019',
    email: 'rahmat.heavyop@palmvision.ai',
    education: 'SMK Otomotif',
    bloodType: 'O',
    emergencyContact: {
      name: 'Rina Karlina',
      relationship: 'Istri',
      phone: '0852-1928-3049',
    },
    companyName: 'PT Nusantara Palm Lestari',
    estateName: 'Estate Sei Riau',
    divisionName: 'Workshop & Alat Berat',
    departmentName: 'Enterprise Asset Management',
    positionTitle: 'Operator Excavator CAT 320',
    supervisorName: 'Agus Setiawan',
    employmentStatus: 'CONTRACT_BHL',
    joinDate: '2023-08-15',
    contractEndDate: '2026-08-14',
    basicSalary: 4200000,
    bankAccount: {
      bankName: 'BNI',
      accountNumber: '0394819203',
      accountHolder: 'Rahmat Hidayat',
    },
    activeStatus: 'ACTIVE',
  },
  {
    id: 'emp-005',
    employeeId: 'EMP-2026-0501',
    nik: '1401021999080002',
    npwp: '95.102.938.1-213.000',
    bpjsKesehatan: '000592819204',
    bpjsKetenagakerjaan: '23019283747',
    name: 'Sari Rahmayanti',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
    gender: 'P',
    birthPlace: 'Pekanbaru',
    birthDate: '1999-08-04',
    religion: 'Islam',
    maritalStatus: 'SINGLE',
    address: 'Jl. Sudirman No 42 Pekanbaru (Head Office)',
    phone: '0812-3049-1928',
    email: 'sari.hr@palmvision.ai',
    education: 'S1 Psikologi',
    bloodType: 'AB',
    emergencyContact: {
      name: 'Nurlaila',
      relationship: 'Ibu',
      phone: '0813-9182-4019',
    },
    companyName: 'PT Nusantara Palm Lestari',
    estateName: 'Head Office Pekanbaru',
    divisionName: 'Human Capital',
    departmentName: 'Human Resource & Payroll',
    positionTitle: 'HR Payroll & BPJS Specialist',
    supervisorName: 'Dra. Maya Indah',
    employmentStatus: 'PERMANENT_SKU',
    joinDate: '2022-02-01',
    basicSalary: 6200000,
    bankAccount: {
      bankName: 'BCA',
      accountNumber: '8291029384',
      accountHolder: 'Sari Rahmayanti',
    },
    activeStatus: 'ACTIVE',
  },
];

export const INITIAL_DEPARTMENTS: OrganizationDepartment[] = [
  {
    id: 'dept-01',
    name: 'Panen & TPH (Harvesting)',
    code: 'DEPT-HARVEST',
    headOfDepartment: 'Ir. Ahmad Zulkarnain',
    totalEmployees: 480,
    subDepartments: ['Divisi Panen Afdeling 1', 'Divisi Panen Afdeling 2', 'Grading TPH'],
  },
  {
    id: 'dept-02',
    name: 'Perawatan & Rawat Tanaman (Maintenance)',
    code: 'DEPT-RAWAT',
    headOfDepartment: 'Agus Pranoto, S.P.',
    totalEmployees: 260,
    subDepartments: ['Pemupukan', 'Semprot Herbisida', 'Kastrasi & Pruning'],
  },
  {
    id: 'dept-03',
    name: 'PKS Processing (Mill Operation)',
    code: 'DEPT-MILL',
    headOfDepartment: 'Ir. Hendra Wijaya',
    totalEmployees: 145,
    subDepartments: ['Stasiun Sterilizer', 'Pressing & Clarification', 'Laboratorium QMS'],
  },
  {
    id: 'dept-04',
    name: 'Enterprise Asset & Workshop (EAM)',
    code: 'DEPT-EAM',
    headOfDepartment: 'Ir. Bambang Trihatmoko',
    totalEmployees: 90,
    subDepartments: ['Bengkel Alat Berat', 'Mekanik Heavy Fleet', 'Logistik Bahan Bakar'],
  },
  {
    id: 'dept-05',
    name: 'Human Capital & General Affair (HRGA)',
    code: 'DEPT-HRGA',
    headOfDepartment: 'Dra. Maya Indah',
    totalEmployees: 35,
    subDepartments: ['Payroll & Compliance', 'Recruitment', 'Safety K3 & Clinic'],
  },
];

export const INITIAL_JOB_VACANCIES: JobVacancy[] = [
  {
    id: 'vac-101',
    title: 'Mandor Panen Afdeling III',
    department: 'Panen & TPH (Harvesting)',
    estate: 'Estate Sei Riau',
    positionsCount: 3,
    status: 'OPEN',
    postedDate: '2026-07-10',
    applicantsCount: 14,
  },
  {
    id: 'vac-102',
    title: 'Operator Boiler PKS License Kelas 1',
    department: 'PKS Processing (Mill Operation)',
    estate: 'Kampar Mill',
    positionsCount: 2,
    status: 'INTERVIEWING',
    postedDate: '2026-07-02',
    applicantsCount: 8,
  },
  {
    id: 'vac-103',
    title: 'Assistant Agronomy Estate (Fresh Graduate)',
    department: 'Perawatan & Rawat Tanaman',
    estate: 'Estate Landak Kalbar',
    positionsCount: 5,
    status: 'OPEN',
    postedDate: '2026-07-15',
    applicantsCount: 42,
  },
];

export const INITIAL_APPLICANTS: Applicant[] = [
  {
    id: 'app-01',
    vacancyId: 'vac-101',
    vacancyTitle: 'Mandor Panen Afdeling III',
    candidateName: 'Doni Pratama',
    email: 'doni.pratama@gmail.com',
    phone: '0812-9901-2291',
    lastEducation: 'D3 Budidaya Perkebunan',
    stage: 'INTERVIEW',
    appliedDate: '2026-07-12',
    scorePercent: 88,
  },
  {
    id: 'app-02',
    vacancyId: 'vac-101',
    vacancyTitle: 'Mandor Panen Afdeling III',
    candidateName: 'Eko Sulistyo',
    email: 'eko.sulistyo@yahoo.com',
    phone: '0853-1192-3049',
    lastEducation: 'SMA',
    stage: 'SCREENING',
    appliedDate: '2026-07-14',
    scorePercent: 74,
  },
  {
    id: 'app-03',
    vacancyId: 'vac-102',
    vacancyTitle: 'Operator Boiler PKS License Kelas 1',
    candidateName: 'Hendra Saputra',
    email: 'hendra.boiler@gmail.com',
    phone: '0813-8829-1029',
    lastEducation: 'SMK Teknik Mesin',
    stage: 'MEDICAL',
    appliedDate: '2026-07-05',
    scorePercent: 94,
  },
];

export const INITIAL_ONBOARDING: OnboardingChecklist[] = [
  {
    id: 'onb-01',
    employeeName: 'Hendra Saputra',
    position: 'Operator Boiler PKS',
    startDate: '2026-08-01',
    documentsVerified: true,
    trainingCompleted: true,
    uniformIssued: true,
    idCardIssued: true,
    emailCreated: false,
    bpjsEnrolled: true,
    overallPercent: 83,
  },
  {
    id: 'onb-02',
    employeeName: 'Doni Pratama',
    position: 'Mandor Panen III',
    startDate: '2026-08-05',
    documentsVerified: true,
    trainingCompleted: false,
    uniformIssued: true,
    idCardIssued: false,
    emailCreated: false,
    bpjsEnrolled: false,
    overallPercent: 33,
  },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'att-1001',
    employeeId: 'emp-001',
    employeeName: 'Budi Santoso',
    department: 'Panen & TPH',
    date: '2026-08-03',
    shiftName: 'PAGI_HARVEST (06:00 - 14:00)',
    clockIn: '05:48 AM',
    clockOut: '02:15 PM',
    status: 'PRESENT',
    method: 'GPS_SELFIE',
    gpsLocation: { lat: 0.5071, lng: 101.4478, locationName: 'TPH 12 Afdeling I Sei Riau' },
    photoVerificationUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
  },
  {
    id: 'att-1002',
    employeeId: 'emp-002',
    employeeName: 'Joko Widodo (Pemanen)',
    department: 'Panen & TPH',
    date: '2026-08-03',
    shiftName: 'PAGI_HARVEST (06:00 - 14:00)',
    clockIn: '05:52 AM',
    clockOut: '02:00 PM',
    status: 'PRESENT',
    method: 'FACE_RECOGNITION',
    gpsLocation: { lat: 0.508, lng: 101.449, locationName: 'Block C14 Harvesting Zone' },
  },
  {
    id: 'att-1003',
    employeeId: 'emp-004',
    employeeName: 'Rahmat Hidayat',
    department: 'Enterprise Asset Management',
    date: '2026-08-03',
    shiftName: 'PAGI_WORKSHOP (07:00 - 16:00)',
    clockIn: '07:15 AM',
    clockOut: '04:05 PM',
    status: 'LATE',
    method: 'FINGERPRINT',
    gpsLocation: { lat: 0.512, lng: 101.451, locationName: 'Central Workshop Station' },
  },
];

export const INITIAL_ATTENDANCE_CORRECTIONS: AttendanceCorrection[] = [
  {
    id: 'att-corr-01',
    employeeName: 'Rahmat Hidayat',
    date: '2026-08-03',
    originalClockIn: '07:15 AM',
    proposedClockIn: '07:00 AM',
    originalClockOut: '04:05 PM',
    proposedClockOut: '04:05 PM',
    reason: 'Faktor kerusakan alat fingerprint di pos workshop pada pukul 06.55 WIB',
    status: 'PENDING',
    approverName: 'Dra. Maya Indah',
  },
];

export const INITIAL_SHIFTS: ShiftRoster[] = [
  {
    id: 'sft-01',
    estate: 'Estate Sei Riau',
    division: 'Afdeling I',
    shiftName: 'PAGI_HARVEST',
    startTime: '06:00 WIB',
    endTime: '14:00 WIB',
    assignedCount: 140,
  },
  {
    id: 'sft-02',
    estate: 'Kampar Mill PKS',
    division: 'Stasiun Pressing',
    shiftName: 'SIANG_PKS',
    startTime: '14:00 WIB',
    endTime: '22:00 WIB',
    assignedCount: 45,
  },
  {
    id: 'sft-03',
    estate: 'Estate Sei Riau',
    division: 'Keamanan / Security',
    shiftName: 'MALAM_SECURITY',
    startTime: '22:00 WIB',
    endTime: '06:00 WIB',
    assignedCount: 22,
  },
];

export const INITIAL_LEAVE_REQUESTS: LeaveRequest[] = [
  {
    id: 'lve-101',
    employeeName: 'Dewi Lestari',
    employeeId: 'EMP-2026-0309',
    leaveType: 'CUTI_TAHUNAN',
    startDate: '2026-08-10',
    endDate: '2026-08-14',
    totalDays: 5,
    reason: 'Acara pernikahan keluarga di Medan',
    status: 'APPROVED',
  },
  {
    id: 'lve-102',
    employeeName: 'Joko Widodo (Pemanen)',
    employeeId: 'EMP-2025-0214',
    leaveType: 'CUTI_SAKIT',
    startDate: '2026-07-28',
    endDate: '2026-07-29',
    totalDays: 2,
    reason: 'Demam tinggi terkonfirmasi Klinik Estate',
    status: 'APPROVED',
    attachmentUrl: 'Surat_Keterangan_Dokter_Klinik.pdf',
  },
];

export const INITIAL_OVERTIMES: OvertimeRequest[] = [
  {
    id: 'ovt-01',
    employeeName: 'Rahmat Hidayat',
    date: '2026-08-02',
    startTime: '16:00',
    endTime: '19:00',
    hours: 3,
    activityDescription: 'Perbaikan darurat rantai conveyor PKS Kampar Mill',
    calculatedCostIdr: 125000,
    status: 'APPROVED',
  },
];

export const INITIAL_PAYROLL_PERIODS: PayrollPeriod[] = [
  {
    id: 'pay-2026-07',
    periodName: 'Payroll Periode Juli 2026',
    startDate: '2026-07-01',
    endDate: '2026-07-31',
    totalEmployeesProcessed: 1010,
    totalGrossPayrollIdr: 4850000000,
    totalBpjsPaidIdr: 420000000,
    totalPph21Idr: 185000000,
    totalNettPayrollIdr: 4245000000,
    status: 'APPROVED',
  },
  {
    id: 'pay-2026-08',
    periodName: 'Payroll Periode Agustus 2026 (Drafting)',
    startDate: '2026-08-01',
    endDate: '2026-08-31',
    totalEmployeesProcessed: 1015,
    totalGrossPayrollIdr: 4920000000,
    totalBpjsPaidIdr: 430000000,
    totalPph21Idr: 190000000,
    totalNettPayrollIdr: 4300000000,
    status: 'CALCULATED',
  },
];

export const INITIAL_PAYSLIPS: PayslipItem[] = [
  {
    id: 'ps-001',
    employeeId: 'EMP-2024-0101',
    employeeName: 'Budi Santoso',
    positionTitle: 'Mandor Panen Utama',
    nik: '1401021988050001',
    department: 'Panen & TPH',
    basicSalary: 4850000,
    harvestIncentivePremi: 1850000,
    overtimePay: 450000,
    allowances: 650000,
    grossSalary: 7800000,
    bpjsKesEmployeeDeduction: 48500,
    bpjsTkEmployeeDeduction: 145500,
    pph21TERDeduction: 156000,
    loanDeduction: 250000,
    totalDeductions: 600000,
    nettSalary: 7200000,
    paymentStatus: 'PAID',
  },
  {
    id: 'ps-002',
    employeeId: 'EMP-2025-0214',
    employeeName: 'Joko Widodo (Pemanen)',
    positionTitle: 'Pemanen TBS Senior',
    nik: '1401022001090004',
    department: 'Panen & TPH',
    basicSalary: 3950000,
    harvestIncentivePremi: 2600000, // Tonase tinggi
    overtimePay: 200000,
    allowances: 400000,
    grossSalary: 7150000,
    bpjsKesEmployeeDeduction: 39500,
    bpjsTkEmployeeDeduction: 118500,
    pph21TERDeduction: 107250,
    loanDeduction: 0,
    totalDeductions: 265250,
    nettSalary: 6884750,
    paymentStatus: 'PAID',
  },
];

export const INITIAL_BPJS_CONFIG: BpjsConfigSummary = {
  bpjsKesCompanyPercent: 4.0,
  bpjsKesEmployeePercent: 1.0,
  bpjsTkJhtCompanyPercent: 3.7,
  bpjsTkJhtEmployeePercent: 2.0,
  bpjsTkJkmCompanyPercent: 0.3,
  bpjsTkJkkCompanyPercent: 0.89, // Resiko tinggi perkebunan
  bpjsTkJpCompanyPercent: 2.0,
  bpjsTkJpEmployeePercent: 1.0,
};

export const INITIAL_LOANS: EmployeeLoan[] = [
  {
    id: 'loan-01',
    employeeName: 'Budi Santoso',
    loanType: 'PINJAMAN_MOTOR',
    totalLoanAmountIdr: 6000000,
    remainingAmountIdr: 2250000,
    monthlyInstallmentIdr: 250000,
    status: 'ACTIVE',
  },
  {
    id: 'loan-02',
    employeeName: 'Rahmat Hidayat',
    loanType: 'KASBON_DARURAT',
    totalLoanAmountIdr: 1000000,
    remainingAmountIdr: 0,
    monthlyInstallmentIdr: 500000,
    status: 'PAID_OFF',
  },
];

export const INITIAL_TRAINING_PROGRAMS: TrainingProgram[] = [
  {
    id: 'trn-01',
    title: 'Sertifikasi Compliance ISPO & RSPO Mandatori Perkebunan',
    category: 'ISPO_RSPO_COMPLIANCE',
    trainer: 'Auditor Utama Sustainability RSPO',
    scheduleDate: '2026-08-18',
    totalParticipants: 45,
    completedParticipants: 0,
    status: 'SCHEDULED',
  },
  {
    id: 'trn-02',
    title: 'Pelatihan K3 & Keselamatan Kerja Stasiun Boiler PKS',
    category: 'SAFETY_K3_PKS',
    trainer: 'Disnaker Riau & HSE Manager',
    scheduleDate: '2026-07-20',
    totalParticipants: 30,
    completedParticipants: 30,
    status: 'COMPLETED',
  },
];

export const INITIAL_CERTIFICATIONS: EmployeeCertification[] = [
  {
    id: 'cert-01',
    employeeName: 'Hendra Saputra',
    certificateName: 'SIO Operator Boiler Kelas 1 (Kemenaker)',
    issuingBody: 'Kemenaker RI',
    issuedDate: '2024-09-01',
    expiryDate: '2026-08-30',
    daysRemaining: 27,
    status: 'EXPIRING_SOON',
  },
  {
    id: 'cert-02',
    employeeName: 'Rahmat Hidayat',
    certificateName: 'SIO Alat Berat Excavator (K3)',
    issuingBody: 'Disnaker Riau',
    issuedDate: '2023-01-15',
    expiryDate: '2028-01-14',
    daysRemaining: 530,
    status: 'VALID',
  },
];

export const INITIAL_KPIS: PerformanceKpi[] = [
  {
    id: 'kpi-01',
    employeeName: 'Joko Widodo (Pemanen)',
    department: 'Panen & TPH',
    kpiCategory: 'HARVEST_TONNAGE',
    targetScore: 2.2, // Ton per hari
    actualScore: 2.45,
    achievementPercent: 111,
    period: 'Q2 2026',
  },
  {
    id: 'kpi-02',
    employeeName: 'Dewi Lestari',
    department: 'Processing & Quality Control',
    kpiCategory: 'MILL_OER_TARGET',
    targetScore: 23.5, // % OER
    actualScore: 23.8,
    achievementPercent: 101,
    period: 'Q2 2026',
  },
];

export const INITIAL_VISITORS: VisitorLog[] = [
  {
    id: 'vis-01',
    visitorName: 'Bambang Sudjipto',
    companyOrigin: 'PT RSPO Compliance Auditor',
    hostEmployeeName: 'Dra. Maya Indah',
    purpose: 'Survei Lapangan Sertifikasi RSPO Estate Sei Riau',
    checkInTime: '2026-08-03 08:30 WIB',
    qrBadgeCode: 'V-88192',
  },
];

export const INITIAL_CONTRACTS: EmploymentContract[] = [
  {
    id: 'cnt-01',
    employeeName: 'Rahmat Hidayat',
    contractType: 'PKWT_1_YEAR',
    startDate: '2025-08-15',
    endDate: '2026-08-14',
    daysToExpiry: 11,
    status: 'WARNING_14_DAYS',
  },
];

export const INITIAL_MEDICAL_RECORDS: MedicalCheckupRecord[] = [
  {
    id: 'mcu-01',
    employeeName: 'Hendra Saputra',
    position: 'Operator Boiler PKS',
    mcuDate: '2026-06-12',
    healthResult: 'FIT_TO_WORK',
    nextMcuDueDate: '2027-06-12',
  },
];

export const INITIAL_UNIFORMS: UniformDistribution[] = [
  {
    id: 'unf-01',
    employeeName: 'Joko Widodo (Pemanen)',
    itemType: 'SERAGAM_PANEN_SLA',
    size: 'L',
    quantity: 2,
    distributedDate: '2026-01-10',
  },
];

export const INITIAL_AI_WORKFORCE_INSIGHTS: AiWorkforceInsight[] = [
  {
    id: 'ai-hr-01',
    metricType: 'HARVESTER_PRODUCTIVITY',
    predictionSummary: 'Produktivitas Pemanen Afdeling I diperkirakan naik 14% di minggu ke-2 Agustus akibat kematangan puncak TBS.',
    confidenceScorePercent: 94,
    actionableRecommendation: 'Tingkatkan alokasi unit armada dump truck di TPH Blok C10 - C18 untuk mencegah buah restan.',
    impactLevel: 'HIGH',
  },
  {
    id: 'ai-hr-02',
    metricType: 'TURNOVER_RISK',
    predictionSummary: 'Risiko absensi & potensi turnover 8% pada tenaga kerja harian lepas (BHL) saat memasuki musim kemarau.',
    confidenceScorePercent: 89,
    actionableRecommendation: 'Pertimbangkan insentif kehadiran insidental dan penyesuaian fasilitas air di housing divisi.',
    impactLevel: 'MEDIUM',
  },
];
