import {
  MasterCompanyItem,
  MasterEstateItem,
  MasterDivisionItem,
  MasterAfdelingItem,
  MasterBlockItem,
  MasterSubBlockItem,
  MasterSoilItem,
  MasterTopographyItem,
  MasterVarietyItem,
  MasterLandOwnershipItem,
  MasterInfrastructureItem,
  MasterFertilizerItem,
  MasterPesticideItem,
  MasterEquipmentItem,
  MasterVehicleItem,
  MasterDepartmentItem,
  MasterPositionItem,
  MasterPartnerItem,
  MasterWeatherStationItem,
  MasterIotDeviceItem,
  MasterDroneDeviceItem,
  MasterDocCategoryItem,
  MasterAiConfigItem,
} from './types';

export const INITIAL_COMPANIES: MasterCompanyItem[] = [
  {
    id: 'comp-01',
    code: 'SNJ-HOLDING',
    name: 'PT Sawit Nusantara Jaya',
    legalName: 'PT Sawit Nusantara Jaya Tbk',
    nib: '9120003910291',
    npwp: '01.392.810.4-012.000',
    address: 'Jl. Jend. Sudirman No. 88, Jakarta Selatan',
    phone: '+62 21 5592 1000',
    email: 'corporate@sawitnusantara.co.id',
    website: 'https://sawitnusantara.co.id',
    picName: 'Ir. Hendra Gunawan',
    picPhone: '+62 811 908 112',
    brandColor: '#059669',
    timezone: 'Asia/Jakarta (WIB)',
    currency: 'IDR (Rp)',
    estatesCount: 8,
    status: 'ACTIVE',
    createdAt: '2024-01-15 08:00',
    updatedAt: '2026-07-20 10:30',
    createdBy: 'System SuperAdmin',
    updatedBy: 'Hendra Gunawan',
  },
  {
    id: 'comp-02',
    code: 'AGRO-PALM',
    name: 'PT Agropalma Sejahtera',
    legalName: 'PT Agropalma Sejahtera Estate',
    nib: '8192001928310',
    npwp: '02.441.901.8-045.000',
    address: 'Jl. Ahmad Yani No. 45, Pekanbaru, Riau',
    phone: '+62 761 889 123',
    email: 'info@agropalma.co.id',
    website: 'https://agropalma.co.id',
    picName: 'Drs. Budi Santoso',
    picPhone: '+62 812 771 909',
    brandColor: '#10b981',
    timezone: 'Asia/Jakarta (WIB)',
    currency: 'IDR (Rp)',
    estatesCount: 4,
    status: 'ACTIVE',
    createdAt: '2024-03-10 09:15',
    updatedAt: '2026-06-12 14:00',
    createdBy: 'System SuperAdmin',
    updatedBy: 'Budi Santoso',
  },
];

export const INITIAL_ESTATES: MasterEstateItem[] = [
  {
    id: 'est-01',
    code: 'EST-TLD',
    name: 'Estate Teluk Dalam',
    companyName: 'PT Sawit Nusantara Jaya',
    managerName: 'Ir. Ahmad Subagyo',
    totalHectares: 4850.5,
    latitude: 0.8912,
    longitude: 101.4421,
    operationalDate: '2012-05-10',
    divisionsCount: 3,
    afdelingsCount: 6,
    blocksCount: 48,
    status: 'ACTIVE',
    createdAt: '2024-01-20 10:00',
    updatedAt: '2026-07-15 11:20',
    createdBy: 'Hendra Gunawan',
    updatedBy: 'Ahmad Subagyo',
  },
  {
    id: 'est-02',
    code: 'EST-KPR',
    name: 'Estate Kampar Raya',
    companyName: 'PT Sawit Nusantara Jaya',
    managerName: 'H. Suryadi M.Sc',
    totalHectares: 6200.0,
    latitude: 0.3512,
    longitude: 101.1205,
    operationalDate: '2014-08-22',
    divisionsCount: 4,
    afdelingsCount: 8,
    blocksCount: 64,
    status: 'ACTIVE',
    createdAt: '2024-02-01 09:30',
    updatedAt: '2026-07-10 16:45',
    createdBy: 'Hendra Gunawan',
    updatedBy: 'Suryadi',
  },
  {
    id: 'est-03',
    code: 'EST-SIAK',
    name: 'Estate Siak Perdana',
    companyName: 'PT Agropalma Sejahtera',
    managerName: 'Bambang Trihatmoko',
    totalHectares: 3800.25,
    latitude: 0.7201,
    longitude: 102.0192,
    operationalDate: '2016-11-05',
    divisionsCount: 2,
    afdelingsCount: 4,
    blocksCount: 32,
    status: 'ACTIVE',
    createdAt: '2024-04-12 11:00',
    updatedAt: '2026-05-30 08:15',
    createdBy: 'Budi Santoso',
    updatedBy: 'Bambang Trihatmoko',
  },
];

export const INITIAL_DIVISIONS: MasterDivisionItem[] = [
  {
    id: 'div-01',
    code: 'DIV-I',
    name: 'Divisi I Teluk Dalam',
    estateName: 'Estate Teluk Dalam',
    supervisorName: 'Rian Hidayat S.P.',
    totalHectares: 1620.0,
    afdelingsCount: 2,
    status: 'ACTIVE',
    createdAt: '2024-01-22 08:30',
    updatedAt: '2026-07-01 09:00',
    createdBy: 'Ahmad Subagyo',
    updatedBy: 'Rian Hidayat',
  },
  {
    id: 'div-02',
    code: 'DIV-II',
    name: 'Divisi II Teluk Dalam',
    estateName: 'Estate Teluk Dalam',
    supervisorName: 'Dedi Kurniawan',
    totalHectares: 1580.5,
    afdelingsCount: 2,
    status: 'ACTIVE',
    createdAt: '2024-01-22 08:45',
    updatedAt: '2026-07-02 10:15',
    createdBy: 'Ahmad Subagyo',
    updatedBy: 'Dedi Kurniawan',
  },
  {
    id: 'div-03',
    code: 'DIV-III',
    name: 'Divisi III Teluk Dalam',
    estateName: 'Estate Teluk Dalam',
    supervisorName: 'Ferry Pratama',
    totalHectares: 1650.0,
    afdelingsCount: 2,
    status: 'ACTIVE',
    createdAt: '2024-01-22 09:00',
    updatedAt: '2026-07-03 14:20',
    createdBy: 'Ahmad Subagyo',
    updatedBy: 'Ferry Pratama',
  },
];

export const INITIAL_AFDELINGS: MasterAfdelingItem[] = [
  {
    id: 'afd-01',
    code: 'AFD-ALPHA',
    name: 'Afdeling Alpha',
    estateName: 'Estate Teluk Dalam',
    divisionName: 'Divisi I Teluk Dalam',
    mandorName: 'Mandor Supardi',
    totalHectares: 810.0,
    totalTrees: 109350,
    blocksCount: 8,
    status: 'ACTIVE',
    createdAt: '2024-01-25 10:00',
    updatedAt: '2026-07-18 13:00',
    createdBy: 'Rian Hidayat',
    updatedBy: 'Supardi',
  },
  {
    id: 'afd-02',
    code: 'AFD-BETA',
    name: 'Afdeling Beta',
    estateName: 'Estate Teluk Dalam',
    divisionName: 'Divisi I Teluk Dalam',
    mandorName: 'Mandor Wawan S.',
    totalHectares: 810.0,
    totalTrees: 109350,
    blocksCount: 8,
    status: 'ACTIVE',
    createdAt: '2024-01-25 10:30',
    updatedAt: '2026-07-18 13:30',
    createdBy: 'Rian Hidayat',
    updatedBy: 'Wawan S.',
  },
  {
    id: 'afd-03',
    code: 'AFD-GAMMA',
    name: 'Afdeling Gamma',
    estateName: 'Estate Teluk Dalam',
    divisionName: 'Divisi II Teluk Dalam',
    mandorName: 'Mandor Taufik',
    totalHectares: 790.25,
    totalTrees: 106680,
    blocksCount: 8,
    status: 'ACTIVE',
    createdAt: '2024-01-25 11:00',
    updatedAt: '2026-07-10 09:15',
    createdBy: 'Dedi Kurniawan',
    updatedBy: 'Taufik',
  },
];

export const INITIAL_BLOCKS: MasterBlockItem[] = [
  {
    id: 'blk-b12',
    code: 'B12',
    name: 'Blok B12 (TM-2018)',
    estateName: 'Estate Teluk Dalam',
    divisionName: 'Divisi I Teluk Dalam',
    afdelingName: 'Afdeling Alpha',
    hectares: 32.5,
    totalTrees: 4387,
    plantingYear: 2018,
    plantAge: 8,
    soilType: 'Mineral Alluvial',
    topography: 'Datar (0-3%)',
    variety: 'DxP Socfindo Premier',
    sph: 135,
    lat: 0.8915,
    lng: 101.4425,
    status: 'ACTIVE',
    createdAt: '2024-02-01 08:00',
    updatedAt: '2026-07-25 10:00',
    createdBy: 'Rian Hidayat',
    updatedBy: 'Rian Hidayat',
    notes: 'Kondisi panen sangat produktif, BJR rata-rata 18.5 kg.',
  },
  {
    id: 'blk-b13',
    code: 'B13',
    name: 'Blok B13 (TM-2019)',
    estateName: 'Estate Teluk Dalam',
    divisionName: 'Divisi I Teluk Dalam',
    afdelingName: 'Afdeling Alpha',
    hectares: 30.0,
    totalTrees: 4050,
    plantingYear: 2019,
    plantAge: 7,
    soilType: 'Gambut Dangkal',
    topography: 'Datar (0-3%)',
    variety: 'Marihat DxP',
    sph: 135,
    lat: 0.8920,
    lng: 101.4460,
    status: 'ACTIVE',
    createdAt: '2024-02-01 08:30',
    updatedAt: '2026-07-24 11:15',
    createdBy: 'Rian Hidayat',
    updatedBy: 'Rian Hidayat',
    notes: 'Gambut terkontrol dengan water gate level 60cm.',
  },
  {
    id: 'blk-c04',
    code: 'C04',
    name: 'Blok C04 (TM-2015)',
    estateName: 'Estate Teluk Dalam',
    divisionName: 'Divisi I Teluk Dalam',
    afdelingName: 'Afdeling Beta',
    hectares: 35.0,
    totalTrees: 4725,
    plantingYear: 2015,
    plantAge: 11,
    soilType: 'Mineral Liat Red-Yellow Podsolic',
    topography: 'Bergelombang (3-8%)',
    variety: 'Lonsum BLRS',
    sph: 135,
    lat: 0.8980,
    lng: 101.4510,
    status: 'ACTIVE',
    createdAt: '2024-02-01 09:00',
    updatedAt: '2026-07-22 15:30',
    createdBy: 'Wawan S.',
    updatedBy: 'Wawan S.',
    notes: 'Sudah dilakukan pemupukan NPK rotasi II.',
  },
];

export const INITIAL_SUBBLOCKS: MasterSubBlockItem[] = [
  {
    id: 'sub-b12-a',
    code: 'B12-A',
    name: 'Sub Blok B12 Utara',
    blockCode: 'B12',
    hectares: 16.25,
    totalTrees: 2193,
    plantingYear: 2018,
    status: 'ACTIVE',
    createdAt: '2024-02-05 09:00',
    updatedAt: '2026-06-10 10:00',
    createdBy: 'Rian Hidayat',
    updatedBy: 'Rian Hidayat',
  },
  {
    id: 'sub-b12-b',
    code: 'B12-B',
    name: 'Sub Blok B12 Selatan',
    blockCode: 'B12',
    hectares: 16.25,
    totalTrees: 2194,
    plantingYear: 2018,
    status: 'ACTIVE',
    createdAt: '2024-02-05 09:15',
    updatedAt: '2026-06-10 10:15',
    createdBy: 'Rian Hidayat',
    updatedBy: 'Rian Hidayat',
  },
];

export const INITIAL_SOILS: MasterSoilItem[] = [
  {
    id: 'soil-01',
    code: 'SOIL-GMB',
    name: 'Gambut Dangkal Saprik',
    soilCategory: 'Gambut',
    description: 'Tanah gambut dengan ketebalan 1-2 meter, tingkat pematangan saprik.',
    pHRange: '3.8 - 4.5',
    organicContentPct: 65.0,
    aiFertilizerRecommendation: 'Dosis Cu, Zn, dan Borate ditingkatkan 15%. Jaga muka air tanah 50-60 cm.',
    status: 'ACTIVE',
    createdAt: '2024-01-10 09:00',
    updatedAt: '2026-07-01 10:00',
    createdBy: 'Agronomist Lead',
    updatedBy: 'Agronomist Lead',
  },
  {
    id: 'soil-02',
    code: 'SOIL-ALV',
    name: 'Alluvial Sungai Mineral',
    soilCategory: 'Aluvial',
    description: 'Tanah endapan sungai kaya hara, kation tinggi, cocok untuk sawit produktivitas tinggi.',
    pHRange: '5.2 - 6.0',
    organicContentPct: 4.8,
    aiFertilizerRecommendation: 'Dosis standar NPK 13-6-27 + Dolomit 1.5 kg/pokok.',
    status: 'ACTIVE',
    createdAt: '2024-01-10 09:30',
    updatedAt: '2026-07-01 10:30',
    createdBy: 'Agronomist Lead',
    updatedBy: 'Agronomist Lead',
  },
];

export const INITIAL_TOPOGRAPHIES: MasterTopographyItem[] = [
  {
    id: 'topo-01',
    code: 'TOPO-FLAT',
    name: 'Datar Lahan Mineral & Gambut',
    slopeCategory: 'Datar (0-3%)',
    mechanizationSuitability: 'Sangat Tinggi (Cocok untuk mekanisasi panen & traktor)',
    erosionRisk: 'Rendah',
    status: 'ACTIVE',
    createdAt: '2024-01-10 11:00',
    updatedAt: '2026-06-01 09:00',
    createdBy: 'GIS Specialist',
    updatedBy: 'GIS Specialist',
  },
  {
    id: 'topo-02',
    code: 'TOPO-WAVY',
    name: 'Bergelombang Terassering',
    slopeCategory: 'Bergelombang (3-8%)',
    mechanizationSuitability: 'Sedang (Memerlukan pembuatan benteng/teras kontur)',
    erosionRisk: 'Sedang',
    status: 'ACTIVE',
    createdAt: '2024-01-10 11:30',
    updatedAt: '2026-06-01 09:30',
    createdBy: 'GIS Specialist',
    updatedBy: 'GIS Specialist',
  },
];

export const INITIAL_VARIETIES: MasterVarietyItem[] = [
  {
    id: 'var-01',
    code: 'VAR-SOC-PRM',
    name: 'DxP Socfindo Premier',
    producer: 'PT Socfin Indonesia',
    releaseYear: 2017,
    yieldPotentialTonsPerHa: 32.5,
    bjrTargetKg: 22.0,
    oilExtractionPct: 26.8,
    description: 'Bibit unggul respon pupuk tinggi, pertumbuhan meninggi relatif lambat.',
    status: 'ACTIVE',
    createdAt: '2024-01-12 10:00',
    updatedAt: '2026-07-15 14:00',
    createdBy: 'Head Agronomy',
    updatedBy: 'Head Agronomy',
  },
  {
    id: 'var-02',
    code: 'VAR-MRH-DXP',
    name: 'DxP PPKS Marihat',
    producer: 'Pusat Penelitian Kelapa Sawit (PPKS)',
    releaseYear: 2014,
    yieldPotentialTonsPerHa: 28.0,
    bjrTargetKg: 19.5,
    oilExtractionPct: 24.5,
    description: 'Daya adaptasi luas di berbagai jenis tanah mineral & gambut.',
    status: 'ACTIVE',
    createdAt: '2024-01-12 10:30',
    updatedAt: '2026-07-15 14:30',
    createdBy: 'Head Agronomy',
    updatedBy: 'Head Agronomy',
  },
];

export const INITIAL_LAND_OWNERSHIPS: MasterLandOwnershipItem[] = [
  {
    id: 'land-01',
    code: 'HGU-2012-091',
    name: 'HGU Kebun Teluk Dalam Utama',
    type: 'HGU',
    certificateNumber: 'BPN-HGU-0912/Riau/2012',
    issueDate: '2012-04-10',
    expiryDate: '2042-04-10',
    hectares: 4850.5,
    location: 'Kec. Siak Kecil, Kab. Bengkalis, Riau',
    holderName: 'PT Sawit Nusantara Jaya',
    status: 'ACTIVE',
    createdAt: '2024-01-15 14:00',
    updatedAt: '2026-05-10 09:00',
    createdBy: 'Legal Department',
    updatedBy: 'Legal Department',
  },
];

export const INITIAL_INFRASTRUCTURES: MasterInfrastructureItem[] = [
  {
    id: 'infra-01',
    code: 'INF-JLN-MAIN',
    name: 'Jalan Main Road Afdeling Alpha',
    category: 'Jalan Utama',
    locationEstate: 'Estate Teluk Dalam',
    condition: 'Baik',
    gpsCoordinates: '0.8912, 101.4421',
    status: 'ACTIVE',
    createdAt: '2024-02-10 08:00',
    updatedAt: '2026-07-20 11:00',
    createdBy: 'Civil Maintenance',
    updatedBy: 'Civil Maintenance',
    notes: 'Perkerasan batu gamping sepanjang 12.5 KM.',
  },
  {
    id: 'infra-02',
    code: 'INF-JBT-01',
    name: 'Jembatan Gelagats Beton Sungai Kampar',
    category: 'Jembatan',
    locationEstate: 'Estate Kampar Raya',
    condition: 'Sangat Baik',
    gpsCoordinates: '0.3512, 101.1205',
    status: 'ACTIVE',
    createdAt: '2024-02-12 09:00',
    updatedAt: '2026-07-20 11:30',
    createdBy: 'Civil Maintenance',
    updatedBy: 'Civil Maintenance',
    notes: 'Kapasitas tonase maksimum 30 Ton dump truck.',
  },
  {
    id: 'infra-03',
    code: 'INF-PKS-60T',
    name: 'Pabrik Kelapa Sawit (PKS) 60 Ton/Jam',
    category: 'Pabrik Kelapa Sawit (PKS)',
    locationEstate: 'Estate Teluk Dalam Central',
    condition: 'Sangat Baik',
    gpsCoordinates: '0.8950, 101.4480',
    status: 'ACTIVE',
    createdAt: '2024-02-15 10:00',
    updatedAt: '2026-07-25 16:00',
    createdBy: 'Mill Manager',
    updatedBy: 'Mill Manager',
  },
];

export const INITIAL_FERTILIZERS: MasterFertilizerItem[] = [
  {
    id: 'fert-01',
    code: 'FERT-NPK-13-6-27',
    name: 'Pupuk NPK Mahkota 13-6-27-4+B',
    type: 'Majemuk NPK',
    npkRatio: '13:6:27:4+B',
    unit: 'Kg',
    supplierName: 'PT Pupuk Wilmar Nusantara',
    defaultPricePerUnit: 14500,
    dosageRecommendation: '2.5 kg/pokok/rotasi (2x setahun)',
    status: 'ACTIVE',
    createdAt: '2024-01-18 09:00',
    updatedAt: '2026-07-10 10:00',
    createdBy: 'Procurement Officer',
    updatedBy: 'Procurement Officer',
  },
  {
    id: 'fert-02',
    code: 'FERT-UREA-PKT',
    name: 'Pupuk Urea Prill Kaltim',
    type: 'Anorganik Tunggal',
    npkRatio: '46:0:0',
    unit: 'Kg',
    supplierName: 'PT Pupuk Kaltim Tbk',
    defaultPricePerUnit: 9800,
    dosageRecommendation: '1.8 kg/pokok/rotasi',
    status: 'ACTIVE',
    createdAt: '2024-01-18 09:30',
    updatedAt: '2026-07-10 10:30',
    createdBy: 'Procurement Officer',
    updatedBy: 'Procurement Officer',
  },
];

export const INITIAL_PESTICIDES: MasterPesticideItem[] = [
  {
    id: 'pest-01',
    code: 'PEST-HERB-GLY',
    name: 'Roundup Powermax 486 SL',
    category: 'Herbisida',
    activeIngredient: 'Isopropilamina Glifosat 486 g/l',
    formulation: 'Soluble Liquid (SL)',
    unit: 'Liter',
    targetPest: 'Gulma Berdaun Lebar & Rumput Belulang',
    supplierName: 'PT Bayer Indonesia',
    safetyClass: 'Kelas II (Beracun)',
    status: 'ACTIVE',
    createdAt: '2024-01-20 11:00',
    updatedAt: '2026-06-15 09:00',
    createdBy: 'Plant Protection Specialist',
    updatedBy: 'Plant Protection Specialist',
  },
];

export const INITIAL_EQUIPMENTS: MasterEquipmentItem[] = [
  {
    id: 'eq-01',
    code: 'EQ-DRONE-MAT',
    name: 'Drone DJI Matrice 300 RTK + Multispectral',
    category: 'Drone Thermal',
    brandModel: 'DJI Matrice 300 RTK',
    serialNumber: '1Z3AB901239102',
    purchaseDate: '2024-05-10',
    condition: 'Bekerja Baik',
    assignedTo: 'Pilot Drone Syahrul',
    status: 'ACTIVE',
    createdAt: '2024-05-12 10:00',
    updatedAt: '2026-07-20 14:00',
    createdBy: 'IT Asset Officer',
    updatedBy: 'Syahrul',
  },
  {
    id: 'eq-02',
    code: 'EQ-SPRAY-ELEK',
    name: 'Sprayer Elektrik Solo 425 16L',
    category: 'Sprayer Elektrik',
    brandModel: 'Solo 425 Pro',
    serialNumber: 'SL-90812-44',
    purchaseDate: '2025-01-15',
    condition: 'Baru',
    assignedTo: 'Tim Semprot Afdeling Alpha',
    status: 'ACTIVE',
    createdAt: '2025-01-16 09:00',
    updatedAt: '2026-06-01 10:00',
    createdBy: 'Warehouse Officer',
    updatedBy: 'Warehouse Officer',
  },
];

export const INITIAL_VEHICLES: MasterVehicleItem[] = [
  {
    id: 'veh-dt-08',
    code: 'DT-08',
    name: 'Dump Truck Mitsubishi Fuso Canter 125 PS',
    type: 'Truk Dump',
    plateNumber: 'BM 8912 SK',
    chassisNumber: 'MHMFE74P3C012391',
    engineNumber: '4D34-C90812',
    year: 2022,
    fuelType: 'Biosolar',
    assignedEstate: 'Estate Teluk Dalam',
    status: 'ACTIVE',
    createdAt: '2024-02-01 09:00',
    updatedAt: '2026-07-28 08:30',
    createdBy: 'Fleet Logistics Manager',
    updatedBy: 'Fleet Logistics Manager',
  },
  {
    id: 'veh-exc-01',
    code: 'EXC-01',
    name: 'Excavator Komatsu PC200-8',
    type: 'Excavator',
    plateNumber: 'HE-PC200-01',
    chassisNumber: 'KMTPC200-8-908123',
    engineNumber: 'SAA6D107E-1',
    year: 2021,
    fuelType: 'Solar Dex',
    assignedEstate: 'Estate Kampar Raya',
    status: 'ACTIVE',
    createdAt: '2024-02-01 10:00',
    updatedAt: '2026-07-28 09:00',
    createdBy: 'Fleet Logistics Manager',
    updatedBy: 'Fleet Logistics Manager',
  },
];

export const INITIAL_DEPARTMENTS: MasterDepartmentItem[] = [
  {
    id: 'dept-01',
    code: 'DEPT-OPS',
    name: 'Departemen Operasional & Tanaman',
    managerName: 'Ir. Hendra Gunawan',
    headCount: 1420,
    budgetAllocation: 25000000000,
    status: 'ACTIVE',
    createdAt: '2024-01-05 08:00',
    updatedAt: '2026-07-01 09:00',
    createdBy: 'HR Director',
    updatedBy: 'HR Director',
  },
  {
    id: 'dept-02',
    code: 'DEPT-MILL',
    name: 'Departemen Pabrik & Pengolahan (PKS)',
    managerName: 'Ir. Sutrisno S.T.',
    headCount: 210,
    budgetAllocation: 18000000000,
    status: 'ACTIVE',
    createdAt: '2024-01-05 08:30',
    updatedAt: '2026-07-01 09:30',
    createdBy: 'HR Director',
    updatedBy: 'HR Director',
  },
];

export const INITIAL_POSITIONS: MasterPositionItem[] = [
  {
    id: 'pos-01',
    code: 'POS-EM',
    name: 'Estate Manager (EM)',
    departmentName: 'Departemen Operasional & Tanaman',
    level: 'Managerial',
    basicSalaryRange: 'Rp 25.000.000 - Rp 40.000.000',
    status: 'ACTIVE',
    createdAt: '2024-01-05 10:00',
    updatedAt: '2026-06-01 11:00',
    createdBy: 'HR Officer',
    updatedBy: 'HR Officer',
  },
  {
    id: 'pos-02',
    code: 'POS-MND',
    name: 'Mandor Panen TBS',
    departmentName: 'Departemen Operasional & Tanaman',
    level: 'Field Mandor',
    basicSalaryRange: 'Rp 5.500.000 - Rp 8.000.000',
    status: 'ACTIVE',
    createdAt: '2024-01-05 10:30',
    updatedAt: '2026-06-01 11:30',
    createdBy: 'HR Officer',
    updatedBy: 'HR Officer',
  },
];

export const INITIAL_PARTNERS: MasterPartnerItem[] = [
  {
    id: 'part-01',
    code: 'VND-WLM-01',
    name: 'PT Wilmar Chemical Indonesia',
    partnerType: 'SUPPLIER',
    nibNpwp: '01.293.810.2-012.000',
    address: 'Kawasan Industri Dumai, Riau',
    picName: 'Rudy Wijaya',
    picPhone: '+62 811 770 991',
    picEmail: 'sales@wilmar-chem.co.id',
    bankName: 'Bank Mandiri Tbk',
    bankAccountNumber: '108-00-1928301-9',
    ratingScore: 4.9,
    status: 'ACTIVE',
    createdAt: '2024-01-10 11:00',
    updatedAt: '2026-07-20 15:00',
    createdBy: 'Procurement Head',
    updatedBy: 'Procurement Head',
  },
  {
    id: 'part-02',
    code: 'KTR-CIVIL-01',
    name: 'CV Kampar Construction Road',
    partnerType: 'CONTRACTOR',
    nibNpwp: '03.891.201.5-045.000',
    address: 'Jl. Riau No. 120, Pekanbaru',
    picName: 'H. Rozak S.T.',
    picPhone: '+62 813 6512 0912',
    picEmail: 'cv.kamparconst@gmail.com',
    bankName: 'Bank Riau Kepri',
    bankAccountNumber: '101-20-89102-1',
    ratingScore: 4.7,
    status: 'ACTIVE',
    createdAt: '2024-02-01 09:00',
    updatedAt: '2026-07-15 10:00',
    createdBy: 'Civil Dept',
    updatedBy: 'Civil Dept',
  },
];

export const INITIAL_WEATHER_STATIONS: MasterWeatherStationItem[] = [
  {
    id: 'ws-01',
    code: 'WS-TLD-01',
    name: 'Weather Station Telemetry Afdeling Alpha',
    estateName: 'Estate Teluk Dalam',
    gpsCoordinates: '0.8912, 101.4421',
    sensorTypes: 'Rain Gauge 0.1mm, Anemometer, Solar Radiation, Hygrometer, Soil Temp',
    solarPanelBatteryPct: 98,
    lastTelemetryPing: '5 menit yang lalu',
    status: 'ACTIVE',
    createdAt: '2024-03-01 10:00',
    updatedAt: '2026-08-03 01:30',
    createdBy: 'IoT Support Lead',
    updatedBy: 'System AutoPing',
  },
];

export const INITIAL_IOT_DEVICES: MasterIotDeviceItem[] = [
  {
    id: 'iot-01',
    code: 'IOT-SM-B12',
    name: 'Soil Moisture & pH Sensor Node B12',
    deviceType: 'Soil Moisture',
    serialNumber: 'SN-IOT-SM-90812',
    assignedLocation: 'Blok B12 (TM-2018)',
    firmwareVersion: 'v2.4.1-LoraWAN',
    batteryPct: 92,
    pingStatus: 'ONLINE',
    status: 'ACTIVE',
    createdAt: '2024-04-10 09:00',
    updatedAt: '2026-08-03 01:35',
    createdBy: 'IoT Support Lead',
    updatedBy: 'LoraWAN Gateway',
  },
  {
    id: 'iot-02',
    code: 'IOT-FUEL-DT08',
    name: 'Smart Ultrasonic Fuel Sensor DT-08',
    deviceType: 'Fuel Tank Meter',
    serialNumber: 'SN-FL-89102',
    assignedLocation: 'Dump Truck DT-08',
    firmwareVersion: 'v1.8.0-CANBus',
    batteryPct: 100,
    pingStatus: 'ONLINE',
    status: 'ACTIVE',
    createdAt: '2024-06-01 11:00',
    updatedAt: '2026-08-03 01:40',
    createdBy: 'IoT Support Lead',
    updatedBy: 'CANBus Telemetry',
  },
];

export const INITIAL_DRONES: MasterDroneDeviceItem[] = [
  {
    id: 'drn-01',
    code: 'DRN-AGRO-01',
    name: 'Drone DJI Mavic 3 Enterprise Multispectral',
    modelName: 'DJI Mavic 3M',
    serialNumber: '1Z3AB90128910',
    cameraType: 'Multispectral NDVI',
    certifiedPilotName: 'Irwan Setiawan S.P.',
    flightHoursTotal: 340.5,
    status: 'ACTIVE',
    createdAt: '2024-03-15 10:00',
    updatedAt: '2026-07-28 16:00',
    createdBy: 'GIS Manager',
    updatedBy: 'Irwan Setiawan',
  },
];

export const INITIAL_DOC_CATEGORIES: MasterDocCategoryItem[] = [
  {
    id: 'doc-cat-01',
    code: 'DOC-CAT-LEGAL',
    name: 'Dokumen Legalitas & Sertifikat HGU',
    allowedFileTypes: 'PDF, PNG, JPG',
    maxSizeMb: 50,
    retentionYears: 30,
    status: 'ACTIVE',
    createdAt: '2024-01-05 09:00',
    updatedAt: '2026-05-01 10:00',
    createdBy: 'Legal Department',
    updatedBy: 'Legal Department',
  },
  {
    id: 'doc-cat-02',
    code: 'DOC-CAT-HARVEST',
    name: 'Lampiran BKM Panen & Nota Timbang PKS',
    allowedFileTypes: 'PDF, XLSX, CSV, JPG',
    maxSizeMb: 20,
    retentionYears: 10,
    status: 'ACTIVE',
    createdAt: '2024-01-05 09:30',
    updatedAt: '2026-05-01 10:30',
    createdBy: 'Audit Department',
    updatedBy: 'Audit Department',
  },
];

export const INITIAL_AI_CONFIGS: MasterAiConfigItem[] = [
  {
    id: 'aif-01',
    code: 'AI-CONF-YIELD',
    name: 'Model Gemini 2.5 Yield Prediction Confidence Threshold',
    parameterKey: 'YIELD_PREDICTION_MIN_CONFIDENCE',
    parameterValue: '0.85',
    datatype: 'NUMBER',
    confidenceThreshold: 0.85,
    description: 'Batas minimal ambang kepastian prediksi panen TBS tonase per blok.',
    status: 'ACTIVE',
    createdAt: '2024-06-01 08:00',
    updatedAt: '2026-07-30 11:00',
    createdBy: 'AI Systems Architect',
    updatedBy: 'AI Systems Architect',
  },
  {
    id: 'aif-02',
    code: 'AI-CONF-ANOMALY',
    name: 'Fuel Anomaly Sensitivity Factor',
    parameterKey: 'FUEL_DISCREPANCY_ALERT_LITERS',
    parameterValue: '15.0',
    datatype: 'NUMBER',
    confidenceThreshold: 0.90,
    description: 'Deviasi pengisian solar (Liter) di atas batas wajar sebelum alert dikirim.',
    status: 'ACTIVE',
    createdAt: '2024-06-01 08:30',
    updatedAt: '2026-07-30 11:30',
    createdBy: 'AI Systems Architect',
    updatedBy: 'AI Systems Architect',
  },
];
