import React from 'react';
import {
  Rocket,
  CheckCircle2,
  Sparkles,
  ShieldCheck,
  Globe,
  Zap,
  Code,
  Smartphone,
  Layers,
  FileText,
  Lock,
  Cpu,
  BarChart,
  Package
} from 'lucide-react';

export const Prompt16RoadmapView: React.FC = () => {
  return (
    <div className="space-y-6">
      {/* Top Banner */}
      <div className="p-6 rounded-2xl bg-gradient-to-r from-emerald-950 via-slate-900 to-indigo-950 border border-emerald-500/30 shadow-2xl space-y-3">
        <div className="flex items-center gap-2">
          <Rocket className="h-6 w-6 text-emerald-400" />
          <span className="px-2.5 py-0.5 rounded-full bg-emerald-500/20 text-emerald-300 border border-emerald-500/30 text-[10px] font-bold uppercase tracking-wider">
            Final Milestone Checklist
          </span>
        </div>
        <h2 className="text-xl font-bold text-white">
          Prompt 16 Roadmap: Final Polish, Production Hardening & Global Release v1.0
        </h2>
        <p className="text-xs text-slate-300 max-w-3xl leading-relaxed">
          Prompt 16 represents the culmination of PalmVision AI — refining UI/UX polish, WCAG accessibility, i18n localization (Bahasa Indonesia & English), PWA offline caching, OpenAPI Swagger specs, and full production deployment manifests.
        </p>
      </div>

      {/* Grid of Planned Deliverables for Prompt 16 */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {[
          {
            title: 'Enterprise UI/UX Polish',
            desc: 'Refine micro-interactions, responsive padding, color contrast consistency, and seamless page route transitions.',
            icon: Sparkles,
            color: 'text-emerald-400'
          },
          {
            title: 'Internationalization (i18n)',
            desc: 'Full bilingual translation matrix (Bahasa Indonesia & English) for all 15 modules with localized currency formats.',
            icon: Globe,
            color: 'text-teal-400'
          },
          {
            title: 'PWA & Offline-First Enhancements',
            desc: 'Service worker background sync for field mandor harvest logs, weighing data cache, and local IndexedDB queueing.',
            icon: Smartphone,
            color: 'text-cyan-400'
          },
          {
            title: 'OpenAPI / Swagger Specs & SDKs',
            desc: 'Autogenerated REST API documentation for external enterprise integrations, webhooks, and Python/TS client SDKs.',
            icon: Code,
            color: 'text-indigo-400'
          },
          {
            title: 'OWASP Security Hardening',
            desc: 'Container penetration testing, CSP headers, CORS policies, XSS filtering, and rate-limiting stress testing.',
            icon: ShieldCheck,
            color: 'text-purple-400'
          },
          {
            title: 'Kubernetes & Docker Manifests',
            desc: 'Helm charts, Docker Compose, Terraform Cloud Run scripts, and on-premise air-gapped installation packages.',
            icon: Package,
            color: 'text-amber-400'
          }
        ].map(item => (
          <div key={item.title} className="p-5 rounded-2xl bg-slate-800/90 border border-slate-700/80 shadow-md space-y-3">
            <div className="flex items-center gap-3">
              <div className="p-2.5 rounded-xl bg-slate-900 border border-slate-700">
                <item.icon className={`h-5 w-5 ${item.color}`} />
              </div>
              <h3 className="text-sm font-bold text-white">{item.title}</h3>
            </div>
            <p className="text-xs text-slate-300 leading-relaxed">{item.desc}</p>
          </div>
        ))}
      </div>
    </div>
  );
};
