import { NavigationItem } from '../types';

export const NAVIGATION_ITEMS: NavigationItem[] = [
  // CORE
  {
    id: 'dashboard',
    label: 'Dashboard Enterprise',
    labelEn: 'Enterprise Dashboard',
    iconName: 'LayoutDashboard',
    category: 'core',
    description: 'Wireframe Executive Dashboard & Key Operations Monitor',
  },
  {
    id: 'master-data',
    label: 'Master Data Enterprise',
    labelEn: 'Master Data Management',
    iconName: 'Database',
    category: 'core',
    badge: 'Core MDM',
    description: 'Master Data Company, Estate, Divisi, Afdeling, Blok, Tanah, Varietas, Armada & IoT',
  },
  {
    id: 'plantation',
    label: 'Plantation Hierarchy',
    labelEn: 'Plantation Structure',
    iconName: 'Trees',
    category: 'core',
    description: 'Multi-level Company, Estate, Division, Afdeling & Block Management',
    badge: 'Core',
  },
  {
    id: 'gis',
    label: 'GIS & Spatial Mapping',
    labelEn: 'GIS & Mapping',
    iconName: 'Map',
    category: 'core',
    badge: 'Spatial',
    description: 'Digital Plantation Map, Polygon Blok, Live GPS Armada, Layer Telemetri IoT & AI Spatial',
  },

  // OPERATIONS
  {
    id: 'harvest',
    label: 'Harvest (Panen TBS)',
    labelEn: 'Harvest Operations',
    iconName: 'Wheat',
    category: 'operations',
    description: 'TBS Harvest Recording, BJR Calculation & Mandor Penalty System',
  },
  {
    id: 'field-activity',
    label: 'Field Activity (Kegiatan Kebun)',
    labelEn: 'Field Operations',
    iconName: 'Pickaxe',
    category: 'operations',
    description: 'Tunas, Pemupukan, Piringan, Weed Control & Plant Protection',
  },
  {
    id: 'transport',
    label: 'Transport & Delivery (SPB)',
    labelEn: 'Transport & Logistics',
    iconName: 'Truck',
    category: 'operations',
    description: 'Surat Pengantar Buah (SPB), Ramp Control & Mill Delivery Tracking',
  },
  {
    id: 'fuel',
    label: 'Fuel & BBM Control',
    labelEn: 'Fuel Consumption',
    iconName: 'Fuel',
    category: 'operations',
    description: 'Solar Monitoring, Anomaly Alert & Heavy Machinery Refueling Logs',
  },
  {
    id: 'workshop',
    label: 'Workshop & Bengkel',
    labelEn: 'Fleet Maintenance',
    iconName: 'Wrench',
    category: 'operations',
    description: 'Tractor, Dump Truck & Heavy Equipment Maintenance Order',
  },

  // RESOURCES
  {
    id: 'inventory',
    label: 'Inventory & Stock',
    labelEn: 'Inventory Management',
    iconName: 'Boxes',
    category: 'resources',
    description: 'Agrochemicals, Fertilizer, Spareparts & Safety Equipment Items',
  },
  {
    id: 'warehouse',
    label: 'Warehouse Gudang',
    labelEn: 'Warehouse System',
    iconName: 'Warehouse',
    category: 'resources',
    description: 'Gudang Central, Gudang Estate, Stock Transfer & Requisition',
  },
  {
    id: 'hr',
    label: 'HR & Ketenagakerjaan',
    labelEn: 'Human Resources',
    iconName: 'Users',
    category: 'resources',
    description: 'Mandor Attendance, BKM Piece-Rate Pay, Worker Housing & Payroll',
  },
  {
    id: 'asset',
    label: 'Asset Management',
    labelEn: 'Asset Registry',
    iconName: 'Building2',
    category: 'resources',
    description: 'Land Titles, Buildings, Heavy Machinery & Fleet Life Cycle',
  },
  {
    id: 'procurement',
    label: 'Procurement & PR/PO',
    labelEn: 'Procurement',
    iconName: 'ShoppingCart',
    category: 'resources',
    description: 'Purchase Request, Purchase Order, Goods Receive Note & Tender',
  },
  {
    id: 'supplier',
    label: 'Supplier & Vendor',
    labelEn: 'Vendor Management',
    iconName: 'Contact2',
    category: 'resources',
    description: 'Fertilizer & Chemical Suppliers, Contractor SLAs & Performance',
  },

  // INTELLIGENCE & ANALYTICS
  {
    id: 'ai-center',
    label: 'AI Center & Assistant',
    labelEn: 'AI Intelligence Suite',
    iconName: 'Sparkles',
    category: 'intelligence',
    badge: 'AI Engine',
    description: 'Gemini-Powered Yield Prediction, OCR Receipts & Anomaly Sentinel',
  },
  {
    id: 'analytics',
    label: 'Analytics & Yield BI',
    labelEn: 'Analytics & BI',
    iconName: 'TrendingUp',
    category: 'intelligence',
    description: 'Ton/Ha Productivity, Cost/Ha Benchmark & Weather Correlation',
  },
  {
    id: 'reports',
    label: 'Executive Reports',
    labelEn: 'Executive Reports',
    iconName: 'FileSpreadsheet',
    category: 'intelligence',
    description: 'Laporan Oprasional Bulanan (LOB), Cost Analysis & Director Summary',
  },

  // SYSTEM & FOUNDATION BLUEPRINTS
  {
    id: 'user-management',
    label: 'User Directory & 2FA',
    labelEn: 'User Directory & 2FA',
    iconName: 'Users',
    category: 'system',
    badge: 'RBAC',
    description: 'Manajemen Pengguna Perkebunan, Role Context, Fingerprint & 2FA',
  },
  {
    id: 'rbac-matrix',
    label: 'Matriks RBAC (17 Roles)',
    labelEn: 'RBAC Matrix (17 Roles)',
    iconName: 'Shield',
    category: 'system',
    description: 'Matriks Otoritas Granular Peran Pengguna Perkebunan',
  },
  {
    id: 'hierarchy-view',
    label: 'Struktur 5-Tier Hierarchy',
    labelEn: '5-Tier Organization Tree',
    iconName: 'Layers',
    category: 'system',
    description: 'Company → Estate → Division → Afdeling → Block Tree',
  },
  {
    id: 'company-profile',
    label: 'Profil Perusahaan Holding',
    labelEn: 'Company & Holding Profile',
    iconName: 'Building2',
    category: 'system',
    description: 'Identitas Perusahaan, Legal NIB, NPWP & Kontak Holding',
  },
  {
    id: 'white-label',
    label: 'White Label & Custom Brand',
    labelEn: 'White Labeling',
    iconName: 'Palette',
    category: 'system',
    description: 'Kustomisasi Nama Aplikasi, Logo, Warna & Custom Domain',
  },
  {
    id: 'license-dashboard',
    label: 'Lisensi & Device Binding',
    labelEn: 'License & HWID Binding',
    iconName: 'Key',
    category: 'system',
    badge: 'License',
    description: 'Manajemen Lisensi Produk, Fingerprint HWID & Grace Period',
  },
  {
    id: 'session-management',
    label: 'Session Control & Remote Logout',
    labelEn: 'Session Management',
    iconName: 'Monitor',
    category: 'system',
    description: 'Monitoring Sesi Aktif, Remote Logout & IP Control',
  },
  {
    id: 'audit-trail',
    label: 'Audit Trail & Immutable Logs',
    labelEn: 'Audit Trail Logs',
    iconName: 'FileText',
    category: 'system',
    description: 'Jejak Rekam Aktivitas Transaksi dan Keamanan System',
  },
  {
    id: 'system-settings',
    label: 'System & Sync Settings',
    labelEn: 'System Settings',
    iconName: 'Settings',
    category: 'system',
    description: 'Konfigurasi Field Engine Offline, Auto Sync & Ambang AI',
  },
  {
    id: 'theme-engine',
    label: 'Theme Engine & Aksesibilitas',
    labelEn: 'Theme Engine & Styling',
    iconName: 'Sliders',
    category: 'system',
    badge: 'Theme',
    description: 'Kustomisasi Realtime Mode Tampilan, Aksentasi Warna & Transparansi',
  },
  {
    id: 'roadmap-prompt4',
    label: 'Roadmap Prompt 4 (Master Data)',
    labelEn: 'Prompt 4 Master Data Plan',
    iconName: 'CheckCircle2',
    category: 'system',
    badge: 'Done',
    description: 'Rancangan Modul Master Data Perkebunan & Single Source of Truth',
  },
  {
    id: 'roadmap-prompt5',
    label: 'Roadmap Prompt 5 (GIS & Map)',
    labelEn: 'Prompt 5 GIS Spatial Plan',
    iconName: 'Map',
    category: 'system',
    badge: 'Done',
    description: 'Peta Spasial Interaktif, Drone Orthomosaic, Live GPS & Polygon Blok',
  },
  {
    id: 'roadmap-prompt6',
    label: 'Roadmap Prompt 6 (Plantation Lifecycle)',
    labelEn: 'Prompt 6 Lifecycle Plan',
    iconName: 'Trees',
    category: 'system',
    badge: 'Next',
    description: 'Manajemen Siklus Hidup Tanaman, Sensus Pohon, SPH & AI Health Monitoring',
  },
  {
    id: 'design-system',
    label: 'Design System Kit',
    labelEn: 'UI/UX Design System',
    iconName: 'Palette',
    category: 'system',
    badge: 'UIKit',
    description: 'Live Interactive Enterprise UI Components & Color Tokens',
  },
  {
    id: 'architecture-blueprints',
    label: 'Arsitektur & Blueprint',
    labelEn: 'Architecture Blueprint',
    iconName: 'Layers',
    category: 'system',
    badge: '12-Poin',
    description: '12 Structural Blueprints: DB, Security, API, AI & License System',
  },
  {
    id: 'license',
    label: 'License & Activation',
    labelEn: 'License Management',
    iconName: 'Key',
    category: 'system',
    description: 'Product Key Activation, HWID Binding & Serial Number Generator',
  },
  {
    id: 'settings',
    label: 'Settings & Security',
    labelEn: 'System Settings',
    iconName: 'Settings',
    category: 'system',
    description: 'RBAC Roles, Audit Logs, JWT Refresh Policy & Company Profile',
  },
  {
    id: 'help-center',
    label: 'Help & Documentation',
    labelEn: 'Help & Docs',
    iconName: 'HelpCircle',
    category: 'system',
    description: 'Standard Operating Procedures (SOP) & System Manuals',
  },
];
