import {
  AiModel,
  AiProvider,
  PromptItem,
  KnowledgeDocument,
  VectorIndexConfig,
  AiWorkflowRule,
  AiRecommendationItem,
  AiForecastItem,
  AiVisionOcrLog,
  AiChatSession,
  AiUsageLog,
} from './types';

export const INITIAL_AI_MODELS: AiModel[] = [
  {
    id: 'mdl-1',
    modelCode: 'gemini-3.6-flash',
    modelName: 'Google Gemini 3.6 Flash',
    providerId: 'prv-1',
    providerName: 'Google Gemini',
    version: '3.6.0',
    status: 'ACTIVE',
    contextWindowTokens: 1048576,
    defaultTemperature: 0.7,
    maxTokens: 8192,
    capabilities: { text: true, vision: true, ocr: true, audio: true, reasoning: true, embedding: false },
    latencyMs: 140,
    costPer1kInputTokenUsd: 0.0001,
    costPer1kOutputTokenUsd: 0.0004,
    usageCount24h: 14250,
  },
  {
    id: 'mdl-2',
    modelCode: 'gemini-3.1-pro-preview',
    modelName: 'Google Gemini 3.1 Pro Enterprise',
    providerId: 'prv-1',
    providerName: 'Google Gemini',
    version: '3.1.0-preview',
    status: 'ACTIVE',
    contextWindowTokens: 2097152,
    defaultTemperature: 0.3,
    maxTokens: 16384,
    capabilities: { text: true, vision: true, ocr: true, audio: true, reasoning: true, embedding: false },
    latencyMs: 420,
    costPer1kInputTokenUsd: 0.00125,
    costPer1kOutputTokenUsd: 0.005,
    usageCount24h: 3120,
  },
  {
    id: 'mdl-3',
    modelCode: 'deepseek-r1-local',
    modelName: 'DeepSeek R1 Reasoning (On-Premise)',
    providerId: 'prv-6',
    providerName: 'DeepSeek',
    version: 'R1-V3.2',
    status: 'ACTIVE',
    contextWindowTokens: 128000,
    defaultTemperature: 0.2,
    maxTokens: 8192,
    capabilities: { text: true, vision: false, ocr: false, audio: false, reasoning: true, embedding: false },
    latencyMs: 380,
    costPer1kInputTokenUsd: 0.00005,
    costPer1kOutputTokenUsd: 0.0002,
    usageCount24h: 5890,
  },
  {
    id: 'mdl-4',
    modelCode: 'gpt-4o-enterprise',
    modelName: 'OpenAI GPT-4o Omni Enterprise',
    providerId: 'prv-2',
    providerName: 'OpenAI',
    version: '4o-2026-05',
    status: 'ACTIVE',
    contextWindowTokens: 128000,
    defaultTemperature: 0.5,
    maxTokens: 4096,
    capabilities: { text: true, vision: true, ocr: true, audio: true, reasoning: true, embedding: false },
    latencyMs: 310,
    costPer1kInputTokenUsd: 0.0025,
    costPer1kOutputTokenUsd: 0.01,
    usageCount24h: 1980,
  },
  {
    id: 'mdl-5',
    modelCode: 'gemini-embedding-2',
    modelName: 'Gemini Embedding 2 Vector Engine',
    providerId: 'prv-1',
    providerName: 'Google Gemini',
    version: '2.0.0',
    status: 'ACTIVE',
    contextWindowTokens: 8192,
    defaultTemperature: 0,
    maxTokens: 768,
    capabilities: { text: true, vision: false, ocr: false, audio: false, reasoning: false, embedding: true },
    latencyMs: 45,
    costPer1kInputTokenUsd: 0.00002,
    costPer1kOutputTokenUsd: 0,
    usageCount24h: 48900,
  },
];

export const INITIAL_AI_PROVIDERS: AiProvider[] = [
  {
    id: 'prv-1',
    providerName: 'Google Gemini',
    type: 'CLOUD',
    baseUrl: 'https://generativelanguage.googleapis.com',
    apiKeyMasked: 'AIzaSy********************',
    status: 'ONLINE',
    priorityOrder: 1,
    rateLimitPerMin: 1200,
    authHeaderType: 'BEARER',
  },
  {
    id: 'prv-2',
    providerName: 'OpenAI',
    type: 'CLOUD',
    baseUrl: 'https://api.openai.com/v1',
    apiKeyMasked: 'sk-proj-********************',
    status: 'ONLINE',
    priorityOrder: 2,
    rateLimitPerMin: 600,
    authHeaderType: 'BEARER',
  },
  {
    id: 'prv-3',
    providerName: 'Ollama (Local)',
    type: 'ON_PREMISE',
    baseUrl: 'http://192.168.10.50:11434',
    apiKeyMasked: 'ON_PREM_NO_KEY_REQUIRED',
    status: 'ONLINE',
    priorityOrder: 3,
    rateLimitPerMin: 3000,
    authHeaderType: 'CUSTOM',
  },
  {
    id: 'prv-6',
    providerName: 'DeepSeek',
    type: 'HYBRID',
    baseUrl: 'https://api.deepseek.com/v1',
    apiKeyMasked: 'sk-ds-********************',
    status: 'ONLINE',
    priorityOrder: 4,
    rateLimitPerMin: 1000,
    authHeaderType: 'BEARER',
  },
];

export const INITIAL_PROMPTS: PromptItem[] = [
  {
    id: 'prm-1',
    promptCode: 'PRM-HARVEST-YIELD-ANALYSIS',
    promptName: 'Analisis Variansi Yield Panen TBS Kebun',
    category: 'HARVEST',
    description: 'Instruksi AI untuk menganalisis penurunan produktivitas tonase TBS per hektar di afdeling tertentu.',
    systemInstruction: 'Anda adalah Senior Palm Agronomist AI Consultant di PT Nusantara Palm Lestari.',
    templateContent: 'Analisis data panen TBS Afdeling {{afdeling}} periode {{period}}. Biji matang rata-rata: {{biji_matang}}, Biji mentah: {{biji_mentah}}. Rekomendasikan tindakan korektif untuk Mandor & Asisten.',
    variables: ['{{afdeling}}', '{{period}}', '{{biji_matang}}', '{{biji_mentah}}'],
    version: 'v2.1',
    status: 'PUBLISHED',
    author: 'Ir. Hendra Gunawan',
    updatedAt: '2026-08-01',
  },
  {
    id: 'prm-2',
    promptCode: 'PRM-FIN-COGS-OPTIMIZER',
    promptName: 'Rekomendasi Efisiensi Biaya HPP Panen & PKS',
    category: 'FINANCE',
    description: 'Instruksi AI untuk membandingkan budget vs realisasi biaya solar, pupuk, & sparepart.',
    systemInstruction: 'Anda adalah Enterprise Palm CFO Financial Advisor.',
    templateContent: 'Evaluasi pengeluaran kas cost center {{cost_center}} dengan budget {{budget_idr}} IDR. Deteksi anomali biaya solar fleet dan usulkan efisiensi.',
    variables: ['{{cost_center}}', '{{budget_idr}}'],
    version: 'v1.4',
    status: 'PUBLISHED',
    author: 'Siti Aminah, SE',
    updatedAt: '2026-07-28',
  },
  {
    id: 'prm-3',
    promptCode: 'PRM-EAM-PREDICTIVE-MAINT',
    promptName: 'Prediksi Kerusakan Alat Berat Excavator & Truck',
    category: 'ASSET',
    description: 'Instruksi AI untuk jadwal preventive maintenance excavator berdasarkan jam kerja (HM) & konsumsi oli.',
    systemInstruction: 'Anda adalah Lead Heavy Equipment Reliability Engineer.',
    templateContent: 'Analisis log HM unit {{unit_code}} jam kerja {{hm_hours}}. Evaluasi gejala kebocoran hidrolik dan tentukan urgency WO maintenance.',
    variables: ['{{unit_code}}', '{{hm_hours}}'],
    version: 'v3.0',
    status: 'PUBLISHED',
    author: 'Budi Santoso, ST',
    updatedAt: '2026-08-02',
  },
];

export const INITIAL_KNOWLEDGE_DOCUMENTS: KnowledgeDocument[] = [
  {
    id: 'kdoc-1',
    docCode: 'KDOC-SOP-AGRO-001',
    title: 'SOP Standar Pemupukan NPK 13-6-27 & Agrokimia Kebun Kelapa Sawit',
    category: 'SOP',
    fileType: 'PDF',
    fileSizeMb: 4.8,
    folderPath: '/Agronomy/SOP_Pemupukan',
    tags: ['SOP', 'Pemupukan', 'NPK', 'Agrokimia', 'Afdeling'],
    version: 'v4.0',
    approvalStatus: 'APPROVED',
    indexedInVectorDb: true,
    totalChunks: 142,
    uploadedBy: 'Head Agronomy',
    uploadedAt: '2026-06-15',
  },
  {
    id: 'kdoc-2',
    docCode: 'KDOC-RSPO-MANUAL-2026',
    title: 'Manual Sertifikasi RSPO Principles & Criteria 2026 & Konservasi HCV/HCS',
    category: 'REGULATION',
    fileType: 'PDF',
    fileSizeMb: 12.4,
    folderPath: '/Compliance/RSPO_ISPO',
    tags: ['RSPO', 'ISPO', 'Sustainability', 'HCV', 'K3'],
    version: 'v2026.1',
    approvalStatus: 'APPROVED',
    indexedInVectorDb: true,
    totalChunks: 380,
    uploadedBy: 'ESG Compliance Team',
    uploadedAt: '2026-07-02',
  },
  {
    id: 'kdoc-3',
    docCode: 'KDOC-MANUAL-CAT320D',
    title: 'Manual Troubleshooting System Hydraulics Excavator CAT 320D',
    category: 'MANUAL',
    fileType: 'PDF',
    fileSizeMb: 18.2,
    folderPath: '/Workshop/EAM_Manuals',
    tags: ['Excavator', 'CAT320D', 'Hydraulic', 'Engine', 'Repair'],
    version: 'v2.0',
    approvalStatus: 'APPROVED',
    indexedInVectorDb: true,
    totalChunks: 410,
    uploadedBy: 'Workshop Chief',
    uploadedAt: '2026-05-10',
  },
];

export const INITIAL_VECTOR_INDEXES: VectorIndexConfig[] = [
  {
    id: 'vec-1',
    provider: 'pgvector',
    indexName: 'palmvision_rag_embeddings_v1',
    dimension: 768,
    metric: 'cosine',
    status: 'ACTIVE',
    totalVectors: 28400,
    chunkSize: 512,
    chunkOverlap: 64,
    embeddingModel: 'gemini-embedding-2',
    lastIndexedAt: '2026-08-03 08:30:00',
  },
  {
    id: 'vec-2',
    provider: 'Qdrant',
    indexName: 'palmvision_agronomy_vectors',
    dimension: 1536,
    metric: 'cosine',
    status: 'ACTIVE',
    totalVectors: 14200,
    chunkSize: 1024,
    chunkOverlap: 128,
    embeddingModel: 'text-embedding-3-large',
    lastIndexedAt: '2026-08-02 18:00:00',
  },
];

export const INITIAL_AI_WORKFLOWS: AiWorkflowRule[] = [
  {
    id: 'wf-1',
    ruleNo: 'WFR-AUTO-01',
    ruleName: 'AI Recommendation Restock Pupuk NPK Saat Stok Minimum',
    triggerEvent: 'MINIMUM_FERTILIZER_STOCK',
    condition: 'stock_kg <= reorder_level_kg',
    aiAction: 'GENERATE_PO_RECOMMENDATION',
    actionType: 'RECOMMENDATION',
    status: 'ACTIVE',
    executionCount: 24,
    lastExecutedAt: '2026-08-03 07:15',
  },
  {
    id: 'wf-2',
    ruleNo: 'WFR-AUTO-02',
    ruleName: 'AI Trigger Root Cause Analysis saat Yield Tonase Panen Turun >15%',
    triggerEvent: 'YIELD_DROP_ALERT',
    condition: 'tonnage_drop_pct >= 15',
    aiAction: 'TRIGGER_ROOT_CAUSE_ANALYSIS',
    actionType: 'NOTIFICATION',
    status: 'ACTIVE',
    executionCount: 8,
    lastExecutedAt: '2026-08-02 16:40',
  },
  {
    id: 'wf-3',
    ruleNo: 'WFR-AUTO-03',
    ruleName: 'AI Recommendation WO Preventive Maintenance Alat Berat',
    triggerEvent: 'HIGH_MACHINE_HOURS_HM',
    condition: 'current_hm >= last_service_hm + 250',
    aiAction: 'CREATE_DRAFT_WORK_ORDER',
    actionType: 'AUTO_APPROVAL',
    status: 'ACTIVE',
    executionCount: 42,
    lastExecutedAt: '2026-08-03 06:00',
  },
];

export const INITIAL_AI_RECOMMENDATIONS: AiRecommendationItem[] = [
  {
    id: 'rec-1',
    recNo: 'REC-202608-001',
    module: 'HARVEST',
    title: 'Optimasi Jadwal Rotasi Panen Afdeling 3 Kebun Sei Riau',
    summary: 'Restrukturisasi rotasi panen dari 10 hari menjadi 7 hari di Blok B12-B14 untuk mencegah Restan (TBS membusuk di piringan).',
    actionPlan: '1. Tambah 4 Pemanen BHL dari Afdeling 1. 2. Sesuaikan jadwal dump truck jam 14:00.',
    priority: 'HIGH',
    confidenceScorePercent: 94,
    potentialImpactIdr: 145000000,
    severity: 'WARNING',
    status: 'OPEN',
    createdAt: '2026-08-03',
  },
  {
    id: 'rec-2',
    recNo: 'REC-202608-002',
    module: 'INVENTORY',
    title: 'Penghematan Pembelian Solar Fleet Dump Truck via Konsolidasi PO',
    summary: 'AI mendeteksi anomali biaya pengadaan solar di Gudang PKS. Penggabungan PO bulanan dengan Petrokimia dapat diskon 4.5%.',
    actionPlan: 'Terbitkan PO gabungan 40,000 Liter Solar Industri B35 untuk 2 bulan.',
    priority: 'HIGH',
    confidenceScorePercent: 91,
    potentialImpactIdr: 85000000,
    severity: 'CRITICAL',
    status: 'OPEN',
    createdAt: '2026-08-02',
  },
  {
    id: 'rec-3',
    recNo: 'REC-202608-003',
    module: 'EAM',
    title: 'Ganti Seal Component Hydraulic Cylinder Excavator CAT320D (EXC-01)',
    summary: 'Prediksi AI Vision & Sensor Telemetry: Potensi breakdown hidrolik dalam 30 jam HM mendatang.',
    actionPlan: 'Beli kit seal O-ring CAT original & jadwalkan service hari Minggu ini.',
    priority: 'MEDIUM',
    confidenceScorePercent: 88,
    potentialImpactIdr: 35000000,
    severity: 'WARNING',
    status: 'OPEN',
    createdAt: '2026-08-01',
  },
];

export const INITIAL_AI_FORECASTS: AiForecastItem[] = [
  {
    id: 'fct-1',
    metricName: 'Proyeksi Tonase Panen TBS 30 Hari Kebun Sei Riau',
    targetModule: 'HARVEST',
    historicalAvg: '1,420 Ton / Bulan',
    forecast30Days: '1,680 Ton (+18.3%)',
    trendDirection: 'UP',
    confidenceScorePercent: 92,
    keyDrivers: ['Puncak Musim Panen (Peak Crop)', 'Ketersediaan Pupuk NPK 100%', 'Curah Hujan Optimal 180mm'],
  },
  {
    id: 'fct-2',
    metricName: 'Proyeksi Cash Flow & Omzet Penjualan CPO (30 Hari)',
    targetModule: 'FINANCE',
    historicalAvg: 'Rp 16.5 Miliar',
    forecast30Days: 'Rp 18.2 Miliar (+10.3%)',
    trendDirection: 'UP',
    confidenceScorePercent: 89,
    keyDrivers: ['Harga CPO Pasar KPBN Rp 12,400/kg', 'Rendemen PKS Stabil 22.8%'],
  },
  {
    id: 'fct-3',
    metricName: 'Proyeksi Konsumsi Solar B35 Fleet Transport Kebun',
    targetModule: 'INVENTORY',
    historicalAvg: '38,000 Liter',
    forecast30Days: '42,500 Liter (+11.8%)',
    trendDirection: 'UP',
    confidenceScorePercent: 95,
    keyDrivers: ['Peningkatan Volume Angkut TBS ke Mill', 'Penambahan Jam Kerja Dump Truck'],
  },
];

export const INITIAL_VISION_OCR_LOGS: AiVisionOcrLog[] = [
  {
    id: 'vol-1',
    logNo: 'LOG-VIS-202608-01',
    type: 'VISION_FRUIT_COUNTING',
    sourceFile: 'tbs_sample_afdeling2_block_a4.jpg',
    detectedResult: 'Total Janjang: 84 | Matang sempurna: 76 (90.5%) | Mentah: 5 | Membusuk: 3',
    confidenceScorePercent: 96,
    status: 'SUCCESS',
    processedAt: '2026-08-03 08:12',
  },
  {
    id: 'vol-2',
    logNo: 'LOG-OCR-202608-02',
    type: 'OCR_WEIGHBRIDGE_TICKET',
    sourceFile: 'nota_timbangan_pks_mandiri_908.pdf',
    detectedResult: 'No Tiket: TMB-202608-091 | Netto: 14,250 kg | No Polisi: BM 8904 TU | Supplier: Kebun Sei Riau',
    confidenceScorePercent: 98,
    status: 'SUCCESS',
    processedAt: '2026-08-03 07:45',
  },
  {
    id: 'vol-3',
    logNo: 'LOG-VIS-202608-03',
    type: 'VISION_DISEASE_DETECTION',
    sourceFile: 'leaf_sample_block_c8.jpg',
    detectedResult: 'Deteksi Penyakit: Ganoderma Boninense (Stadium Awal) pada 4 Pohon Kelapa Sawit.',
    confidenceScorePercent: 91,
    status: 'WARNING',
    processedAt: '2026-08-02 14:30',
  },
];

export const INITIAL_AI_CHAT_SESSIONS: AiChatSession[] = [
  {
    id: 'ses-1',
    title: 'Diskusi Rencana Pemupukan NPK Afdeling 2',
    folder: 'Agronomy Analysis',
    pinned: true,
    roleContext: 'Palm Agronomist',
    modelUsed: 'gemini-3.6-flash',
    updatedAt: '2026-08-03 08:45',
    messages: [
      {
        id: 'msg-1',
        sender: 'USER',
        text: 'Berapa dosis NPK 13-6-27 yang ideal untuk blok A4 yang berumur 8 tahun (TM-2)?',
        timestamp: '08:42',
      },
      {
        id: 'msg-2',
        sender: 'ASSISTANT',
        text: 'Berdasarkan SOP Pemupukan KDOC-SOP-AGRO-001:\n- Dosis rekomendasi: **2.5 kg per pohon / aplikasi** (2x setahun).\n- Tebar merata pada piringan pohon sejauh 1.5 - 2.0 meter dari pangkal batang.\n- Pastikan piringan bersih dari gulma tebal sebelum pemupukan.',
        timestamp: '08:43',
        citationDoc: 'KDOC-SOP-AGRO-001 (SOP Pemupukan NPK 2026)',
      },
    ],
  },
  {
    id: 'ses-2',
    title: 'Evaluasi HPP Produksi CPO PKS Mill',
    folder: 'Finance & Costing',
    pinned: false,
    roleContext: 'Estate CFO',
    modelUsed: 'gemini-3.1-pro-preview',
    updatedAt: '2026-08-02 17:20',
    messages: [
      {
        id: 'msg-3',
        sender: 'USER',
        text: 'Berapa HPP per ton TBS panen bulan ini dibanding budget?',
        timestamp: '17:18',
      },
      {
        id: 'msg-4',
        sender: 'ASSISTANT',
        text: 'HPP Produksi TBS Panen YTD Agustus 2026:\n- **Realisasi Actual:** Rp 142,400 / Ton TBS\n- **Budget Target:** Rp 148,000 / Ton TBS\n- **Variansi Efisiensi:** +3.78% lebih hemat dibanding budget target.',
        timestamp: '17:20',
      },
    ],
  },
];

export const INITIAL_USAGE_LOGS: AiUsageLog[] = [
  {
    id: 'usg-1',
    timestamp: '2026-08-03 08:45:12',
    userId: 'usr-101',
    userName: 'Ir. Hendra Gunawan',
    department: 'Agronomy',
    module: 'Harvest',
    model: 'gemini-3.6-flash',
    provider: 'Google Gemini',
    promptTokens: 840,
    completionTokens: 290,
    latencyMs: 145,
    estimatedCostUsd: 0.0002,
    status: 'SUCCESS',
  },
  {
    id: 'usg-2',
    timestamp: '2026-08-03 08:40:00',
    userId: 'usr-102',
    userName: 'Siti Aminah, SE',
    department: 'Finance',
    module: 'Finance',
    model: 'gemini-3.1-pro-preview',
    provider: 'Google Gemini',
    promptTokens: 2400,
    completionTokens: 850,
    latencyMs: 410,
    estimatedCostUsd: 0.0072,
    status: 'SUCCESS',
  },
  {
    id: 'usg-3',
    timestamp: '2026-08-03 08:30:45',
    userId: 'usr-103',
    userName: 'Budi Santoso, ST',
    department: 'Workshop',
    module: 'EAM',
    model: 'deepseek-r1-local',
    provider: 'DeepSeek',
    promptTokens: 1200,
    completionTokens: 420,
    latencyMs: 380,
    estimatedCostUsd: 0.0001,
    status: 'SUCCESS',
  },
];
