import React, { useState, useEffect, useRef } from 'react';
import { Search, Command, X, ArrowRight, Layers, Building2, Trees, Users, FileText, Sparkles, Navigation } from 'lucide-react';
import { CommandSearchResult } from '../../types';
import { NAVIGATION_ITEMS } from '../../config/navigation';

interface CommandPaletteModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSelectModule: (moduleId: string) => void;
}

const DUMMY_SEARCH_DATA: CommandSearchResult[] = [
  // Menus
  ...NAVIGATION_ITEMS.map((item) => ({
    id: `menu-${item.id}`,
    title: item.label,
    subtitle: item.description,
    category: 'MENU' as const,
    iconName: item.iconName,
    moduleId: item.id,
  })),
  // Estates
  { id: 'est-1', title: 'Estate Teluk Dalam', subtitle: '4,200 Ha • 12 Afdeling • Manager: Ir. H. Bambang', category: 'ESTATE', iconName: 'Building2', moduleId: 'dashboard' },
  { id: 'est-2', title: 'Estate Sungai Rungau', subtitle: '3,850 Ha • 10 Afdeling • Manager: Syaiful Anwar, M.Si', category: 'ESTATE', iconName: 'Building2', moduleId: 'dashboard' },
  { id: 'est-3', title: 'Estate Bukit Permata', subtitle: '2,950 Ha • 8 Afdeling • Manager: Dedi Kurniawan', category: 'ESTATE', iconName: 'Building2', moduleId: 'dashboard' },
  // Blocks
  { id: 'blk-1', title: 'Blok B12 (TM-2018)', subtitle: 'Divisi I • Afdeling Alpha • 42 Ha • Variety: DxP Socfindo', category: 'BLOCK', iconName: 'Trees', moduleId: 'dashboard' },
  { id: 'blk-2', title: 'Blok A05 (TM-2015)', subtitle: 'Divisi II • Afdeling Beta • 38 Ha • High Yield Target', category: 'BLOCK', iconName: 'Trees', moduleId: 'dashboard' },
  { id: 'blk-3', title: 'Blok C09 (TBM-2022)', subtitle: 'Divisi I • Afdeling Gamma • 28 Ha • Replanting Phase', category: 'BLOCK', iconName: 'Trees', moduleId: 'dashboard' },
  // Employees
  { id: 'emp-1', title: 'Ir. Ahmad Subagyo', subtitle: 'General Manager Perkebunan • NIK: 88102938 • GM Teluk Dalam', category: 'EMPLOYEE', iconName: 'Users', moduleId: 'user-management' },
  { id: 'emp-2', title: 'Siti Rahmawati, S.P.', subtitle: 'Asisten Afdeling Alpha • NIK: 92038102', category: 'EMPLOYEE', iconName: 'Users', moduleId: 'user-management' },
  { id: 'emp-3', title: 'Budi Santoso', subtitle: 'Mandor Panen Blok B12 • Device HWID Bound', category: 'EMPLOYEE', iconName: 'Users', moduleId: 'user-management' },
  // Documents & Reports
  { id: 'doc-1', title: 'Laporan Rekapitulasi Panen Bulanan (Januari 2026)', subtitle: 'PDF Document • 14.2 MB • Generated by System', category: 'DOCUMENT', iconName: 'FileText', moduleId: 'audit-trail' },
  { id: 'doc-2', title: 'Analisis GIS Heatmap Defisit Nutrisi NPK Blok B12', subtitle: 'GIS Layer & AI Diagnostic Report', category: 'REPORT', iconName: 'FileText', moduleId: 'architecture-blueprints' },
  // AI History
  { id: 'ai-1', title: 'Prediksi Yield TBS Q2 2026 dengan Model Gemini 2.5', subtitle: 'AI Prompt Result • Accuracy 94.8%', category: 'AI_HISTORY', iconName: 'Sparkles', moduleId: 'dashboard' },
];

export const CommandPaletteModal: React.FC<CommandPaletteModalProps> = ({ isOpen, onClose, onSelectModule }) => {
  const [query, setQuery] = useState('');
  const [selectedCategory, setSelectedCategory] = useState<string>('ALL');
  const [selectedIndex, setSelectedIndex] = useState(0);
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (isOpen) {
      setTimeout(() => inputRef.current?.focus(), 50);
    } else {
      setQuery('');
      setSelectedIndex(0);
    }
  }, [isOpen]);

  const filteredResults = DUMMY_SEARCH_DATA.filter((item) => {
    const matchesCategory = selectedCategory === 'ALL' || item.category === selectedCategory;
    const matchesQuery =
      item.title.toLowerCase().includes(query.toLowerCase()) ||
      item.subtitle.toLowerCase().includes(query.toLowerCase());
    return matchesCategory && matchesQuery;
  });

  useEffect(() => {
    setSelectedIndex(0);
  }, [query, selectedCategory]);

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'ArrowDown') {
      e.preventDefault();
      setSelectedIndex((prev) => (prev + 1) % Math.max(1, filteredResults.length));
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      setSelectedIndex((prev) => (prev - 1 + filteredResults.length) % Math.max(1, filteredResults.length));
    } else if (e.key === 'Enter') {
      e.preventDefault();
      if (filteredResults[selectedIndex]) {
        const item = filteredResults[selectedIndex];
        if (item.moduleId) {
          onSelectModule(item.moduleId);
        }
        onClose();
      }
    } else if (e.key === 'Escape') {
      onClose();
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-start justify-center pt-16 sm:pt-24 px-4 bg-slate-950/70 backdrop-blur-md animate-fadeIn">
      <div
        className="w-full max-w-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[80vh] transition-all"
        onKeyDown={handleKeyDown}
      >
        {/* Search Bar Input */}
        <div className="p-4 border-b border-slate-200 dark:border-slate-800 flex items-center gap-3 bg-slate-50/50 dark:bg-slate-900/50">
          <Search className="h-5 w-5 text-emerald-500 shrink-0" />
          <input
            ref={inputRef}
            type="text"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="Cari menu, estate, blok, karyawan, dokumen, laporan, AI..."
            className="w-full bg-transparent text-sm sm:text-base text-slate-900 dark:text-slate-100 placeholder-slate-400 focus:outline-hidden font-medium"
          />
          {query && (
            <button
              onClick={() => setQuery('')}
              className="p-1 rounded-lg text-slate-400 hover:text-slate-600 dark:hover:text-slate-200"
            >
              <X className="h-4 w-4" />
            </button>
          )}
          <kbd className="hidden sm:inline-flex items-center gap-1 px-2 py-0.5 text-[10px] font-semibold text-slate-500 bg-slate-200 dark:bg-slate-800 rounded-md border border-slate-300 dark:border-slate-700">
            ESC
          </kbd>
        </div>

        {/* Category Filters Pill */}
        <div className="px-4 py-2 border-b border-slate-100 dark:border-slate-800/80 bg-slate-100/50 dark:bg-slate-950/40 flex items-center gap-1.5 overflow-x-auto text-xs no-scrollbar">
          {[
            { id: 'ALL', label: 'Semua' },
            { id: 'MENU', label: 'Menu Navigasi' },
            { id: 'ESTATE', label: 'Estate & Divisi' },
            { id: 'BLOCK', label: 'Blok Sawit' },
            { id: 'EMPLOYEE', label: 'Karyawan' },
            { id: 'DOCUMENT', label: 'Dokumen' },
            { id: 'AI_HISTORY', label: 'Saran AI' },
          ].map((cat) => (
            <button
              key={cat.id}
              onClick={() => setSelectedCategory(cat.id)}
              className={`px-2.5 py-1 rounded-lg font-medium transition-colors shrink-0 ${
                selectedCategory === cat.id
                  ? 'bg-emerald-600 text-white shadow-xs'
                  : 'text-slate-600 dark:text-slate-400 hover:bg-slate-200 dark:hover:bg-slate-800'
              }`}
            >
              {cat.label}
            </button>
          ))}
        </div>

        {/* Results List */}
        <div className="flex-1 overflow-y-auto p-2 space-y-1">
          {filteredResults.length === 0 ? (
            <div className="p-8 text-center space-y-2">
              <Command className="h-8 w-8 text-slate-400 mx-auto" />
              <p className="text-sm font-semibold text-slate-700 dark:text-slate-300">
                Tidak ada hasil ditemukan untuk "{query}"
              </p>
              <p className="text-xs text-slate-400">Coba kata kunci lain atau pilih kategori yang berbeda.</p>
            </div>
          ) : (
            filteredResults.map((item, idx) => {
              const isSelected = idx === selectedIndex;
              return (
                <div
                  key={item.id}
                  onClick={() => {
                    if (item.moduleId) onSelectModule(item.moduleId);
                    onClose();
                  }}
                  onMouseEnter={() => setSelectedIndex(idx)}
                  className={`p-3 rounded-xl flex items-center justify-between cursor-pointer transition-all ${
                    isSelected
                      ? 'bg-emerald-50 dark:bg-emerald-950/40 border border-emerald-200 dark:border-emerald-800/60 text-emerald-950 dark:text-emerald-100'
                      : 'hover:bg-slate-50 dark:hover:bg-slate-800/50 text-slate-800 dark:text-slate-200 border border-transparent'
                  }`}
                >
                  <div className="flex items-center gap-3 min-w-0">
                    <div
                      className={`p-2 rounded-lg shrink-0 ${
                        item.category === 'MENU'
                          ? 'bg-emerald-100 dark:bg-emerald-900/60 text-emerald-600 dark:text-emerald-300'
                          : item.category === 'ESTATE'
                          ? 'bg-blue-100 dark:bg-blue-900/60 text-blue-600 dark:text-blue-300'
                          : item.category === 'BLOCK'
                          ? 'bg-amber-100 dark:bg-amber-900/60 text-amber-600 dark:text-amber-300'
                          : item.category === 'EMPLOYEE'
                          ? 'bg-violet-100 dark:bg-violet-900/60 text-violet-600 dark:text-violet-300'
                          : 'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300'
                      }`}
                    >
                      {item.category === 'MENU' && <Navigation className="h-4 w-4" />}
                      {item.category === 'ESTATE' && <Building2 className="h-4 w-4" />}
                      {item.category === 'BLOCK' && <Trees className="h-4 w-4" />}
                      {item.category === 'EMPLOYEE' && <Users className="h-4 w-4" />}
                      {item.category === 'DOCUMENT' && <FileText className="h-4 w-4" />}
                      {item.category === 'REPORT' && <FileText className="h-4 w-4" />}
                      {item.category === 'AI_HISTORY' && <Sparkles className="h-4 w-4" />}
                    </div>
                    <div className="min-w-0">
                      <div className="flex items-center gap-2">
                        <span className="text-xs font-bold truncate">{item.title}</span>
                        <span className="text-[10px] uppercase font-bold px-1.5 py-0.5 rounded-xs bg-slate-200 dark:bg-slate-800 text-slate-600 dark:text-slate-400">
                          {item.category}
                        </span>
                      </div>
                      <p className="text-[11px] text-slate-500 dark:text-slate-400 truncate mt-0.5">
                        {item.subtitle}
                      </p>
                    </div>
                  </div>
                  <div className="flex items-center gap-2 shrink-0">
                    <ArrowRight className={`h-4 w-4 ${isSelected ? 'text-emerald-500 opacity-100' : 'opacity-0'}`} />
                  </div>
                </div>
              );
            })
          )}
        </div>

        {/* Modal Footer Hotkey Tips */}
        <div className="p-3 border-t border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950/60 flex items-center justify-between text-[11px] text-slate-500 dark:text-slate-400">
          <div className="flex items-center gap-3">
            <span className="flex items-center gap-1">
              <kbd className="px-1.5 py-0.5 rounded-xs bg-slate-200 dark:bg-slate-800 border border-slate-300 dark:border-slate-700">↑↓</kbd>{' '}
              Navigasi
            </span>
            <span className="flex items-center gap-1">
              <kbd className="px-1.5 py-0.5 rounded-xs bg-slate-200 dark:bg-slate-800 border border-slate-300 dark:border-slate-700">↵</kbd>{' '}
              Pilih
            </span>
          </div>
          <span className="text-emerald-600 dark:text-emerald-400 font-semibold">
            PalmVision AI Command Engine v3.0
          </span>
        </div>
      </div>
    </div>
  );
};
