import {
  WorkOrderRecord,
  TaskAssignmentItem,
  DailyActivityRecord,
  FertilizerActivityRecord,
  SprayingActivityRecord,
  PruningActivityRecord,
  MaintenanceActivityRecord,
  PestControlRecord,
  FieldChecklistItem,
  FieldPhotoItem,
  GpsTrackingPoint,
  AttendanceFieldRecord,
  OfflineSyncQueueItem,
  FieldTimelineEvent,
  AiOperationRecommendation,
} from './types';

export const INITIAL_WORK_ORDERS: WorkOrderRecord[] = [
  {
    id: 'wo-101',
    woNumber: 'WO-2025-05-001',
    title: 'Aplikasi Pemupukan Susulan NPK 15-15-6-4 Dosis TBM2',
    date: '2025-05-18',
    dueDate: '2025-05-20',
    category: 'Pemupukan',
    companyName: 'PT Nusantara Palm Lestari',
    estateName: 'Sei Buatan Estate',
    divisionName: 'Divisi I',
    afdelingName: 'Afdeling I',
    blockCode: 'BLK-A01',
    subBlockCode: 'SUB-A01-1',
    priority: 'Tinggi',
    description: 'Sebarkan pupuk NPK 15-15-6-4 dosis 1.25 kg per pohon di piringan bersih dengan metode tabur melingkar.',
    mandorName: 'Mandor Supriadi',
    supervisorName: 'Agus Purnomo, S.P.',
    teamName: 'Regu Pemupukan Alfa',
    teamMembersCount: 12,
    estimatedHours: 6,
    actualHours: 4.5,
    targetQuantity: '3,200 Pokok (4.0 Ton Pupuk)',
    achievedQuantity: '2,800 Pokok (3.5 Ton Pupuk)',
    status: 'In Progress',
    attachmentsCount: 3,
    gpsLocation: { lat: 0.8145, lng: 101.4556, locationName: 'Kebun Sei Buatan Blok A01' },
    createdAt: '2025-05-17T08:00:00Z',
    updatedAt: '2025-05-18T10:30:00Z',
  },
  {
    id: 'wo-102',
    woNumber: 'WO-2025-05-002',
    title: 'Penyemprotan Herbisida Piringan & Pasar Pikul (Glifosat)',
    date: '2025-05-18',
    dueDate: '2025-05-19',
    category: 'Penyemprotan',
    companyName: 'PT Nusantara Palm Lestari',
    estateName: 'Sei Buatan Estate',
    divisionName: 'Divisi I',
    afdelingName: 'Afdeling II',
    blockCode: 'BLK-B02',
    subBlockCode: 'SUB-B02-2',
    priority: 'Sedang',
    description: 'Pengendalian gulma gulma berdaun lebar dan lalang di sekitar piringan pohon dan pasar pikul.',
    mandorName: 'Mandor Budi Santoso',
    supervisorName: 'Agus Purnomo, S.P.',
    teamName: 'Regu Semprot Beta',
    teamMembersCount: 8,
    estimatedHours: 5,
    actualHours: 5.0,
    targetQuantity: '45.0 Ha Area',
    achievedQuantity: '45.0 Ha Area',
    status: 'Completed',
    attachmentsCount: 2,
    gpsLocation: { lat: 0.8210, lng: 101.4612, locationName: 'Kebun Sei Buatan Blok B02' },
    createdAt: '2025-05-17T09:15:00Z',
    updatedAt: '2025-05-18T16:00:00Z',
  },
  {
    id: 'wo-103',
    woNumber: 'WO-2025-05-003',
    title: 'Perbaikan Jalan Tepi Collection Road Tergerus Hujan',
    date: '2025-05-19',
    dueDate: '2025-05-22',
    category: 'Perawatan Jalan',
    companyName: 'PT Nusantara Palm Lestari',
    estateName: 'Riau Utara Estate',
    divisionName: 'Divisi II',
    afdelingName: 'Afdeling III',
    blockCode: 'BLK-C03',
    subBlockCode: 'SUB-C03-1',
    priority: 'Darurat',
    description: 'Pengurukan sirtu & pemadatan jalan sepanjang 1.2 km yang ambles agar truk pengangkut TBS dapat melintas.',
    mandorName: 'Mandor Hendra',
    supervisorName: 'Ir. Ahmad Zulkarnain',
    teamName: 'Regu Alat Berat & Jalan',
    teamMembersCount: 6,
    estimatedHours: 12,
    targetQuantity: '1,200 Meter Jalan',
    status: 'Assigned',
    attachmentsCount: 4,
    gpsLocation: { lat: 0.9531, lng: 101.3211, locationName: 'Kebun Riau Utara Blok C03' },
    createdAt: '2025-05-18T07:30:00Z',
    updatedAt: '2025-05-18T07:30:00Z',
  },
];

export const INITIAL_TASKS: TaskAssignmentItem[] = [
  {
    id: 'task-01',
    taskId: 'TSK-2025-089',
    taskTitle: 'Inspeksi Kualitas Piringan & Pasar Pikul Pasca Semprot',
    assignedType: 'Single User',
    assigneeName: 'Mandor Budi Santoso',
    assigneeRole: 'Mandor Semprot Afdeling II',
    department: 'Agronomi',
    deadline: '2025-05-19T17:00:00Z',
    isRecurring: false,
    reminderSent: true,
    gpsTarget: { lat: 0.8210, lng: 101.4612, blockCode: 'BLK-B02' },
    status: 'Sedang Dikerjakan',
  },
  {
    id: 'task-02',
    taskId: 'TSK-2025-090',
    taskTitle: 'Pembersihan & Cuci Parit Drainase Sekunder Blok A01',
    assignedType: 'Team',
    assigneeName: 'Regu Drainase Delta',
    assigneeRole: 'Team Lead Mandor Supriadi',
    department: 'Teknik & Infrastruktur',
    deadline: '2025-05-20T12:00:00Z',
    isRecurring: true,
    recurringInterval: 'Setiap 2 Minggu',
    reminderSent: false,
    gpsTarget: { lat: 0.8145, lng: 101.4556, blockCode: 'BLK-A01' },
    status: 'Belum Dimulai',
  },
];

export const INITIAL_DAILY_ACTIVITIES: DailyActivityRecord[] = [
  {
    id: 'act-1',
    activityCode: 'ACT-2025-0518-01',
    date: '2025-05-18',
    timeStart: '07:30',
    timeEnd: '12:00',
    category: 'Pemupukan',
    blockCode: 'BLK-A01',
    estateName: 'Sei Buatan Estate',
    afdelingName: 'Afdeling I',
    mandorName: 'Mandor Supriadi',
    teamName: 'Regu Pemupukan Alfa',
    workersCount: 12,
    workVolume: '2,800 Pokok (3.5 Ton Pupuk NPK)',
    weatherCondition: 'Cerah',
    photoUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80',
    lat: 0.8145,
    lng: 101.4556,
    notes: 'Aplikasi pemupukan berjalan lancar, tidak ada kendala hujan.',
    isOfflineSynced: true,
  },
  {
    id: 'act-2',
    activityCode: 'ACT-2025-0518-02',
    date: '2025-05-18',
    timeStart: '08:00',
    timeEnd: '15:30',
    category: 'Penyemprotan',
    blockCode: 'BLK-B02',
    estateName: 'Sei Buatan Estate',
    afdelingName: 'Afdeling II',
    mandorName: 'Mandor Budi Santoso',
    teamName: 'Regu Semprot Beta',
    workersCount: 8,
    workVolume: '45.0 Ha Area TBM2',
    weatherCondition: 'Berawan',
    photoUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80',
    lat: 0.8210,
    lng: 101.4612,
    notes: 'Penyemprotan selesai sesuai target sebelum gerimis jam 3 sore.',
    isOfflineSynced: true,
  },
];

export const INITIAL_FERTILIZER_ACTIVITIES: FertilizerActivityRecord[] = [
  {
    id: 'fert-01',
    recordCode: 'FERT-2025-089',
    date: '2025-05-18',
    estateName: 'Sei Buatan Estate',
    blockCode: 'BLK-A01',
    subBlockCode: 'SUB-A01-1',
    fertilizerType: 'NPK 15-15-6-4',
    quantityKg: 3500,
    applicationMethod: 'Tabur Piringan',
    teamName: 'Regu Pemupukan Alfa',
    mandorName: 'Mandor Supriadi',
    photoUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80',
    lat: 0.8145,
    lng: 101.4556,
    notes: 'Dosis 1.25 kg/pokok, ditabur melingkar 1.5 meter dari pangkal batang.',
  },
];

export const INITIAL_SPRAYING_ACTIVITIES: SprayingActivityRecord[] = [
  {
    id: 'spray-01',
    recordCode: 'SPRAY-2025-044',
    date: '2025-05-18',
    estateName: 'Sei Buatan Estate',
    blockCode: 'BLK-B02',
    chemicalType: 'Glifosat 480 SL',
    chemicalCategory: 'Herbisida',
    areaCoverageHa: 45.0,
    solutionVolumeLiters: 1200,
    operatorCount: 8,
    weatherCondition: 'Berawan, Angin Rendah',
    mandorName: 'Mandor Budi Santoso',
    photoUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80',
    lat: 0.8210,
    lng: 101.4612,
  },
];

export const INITIAL_PRUNING_ACTIVITIES: PruningActivityRecord[] = [
  {
    id: 'prun-01',
    recordCode: 'PRUN-2025-012',
    date: '2025-05-17',
    blockCode: 'BLK-C03',
    treesCount: 1400,
    pruningType: 'Pruning Pelepah Sandang Tiram',
    teamName: 'Regu Pruning Gamma',
    mandorName: 'Mandor Supriadi',
    notes: 'Menyisa 2 pelepah di bawah tandan buah tua untuk menjaga asimilasi daun.',
  },
];

export const INITIAL_MAINTENANCE_ACTIVITIES: MaintenanceActivityRecord[] = [
  {
    id: 'maint-01',
    recordCode: 'MAINT-2025-078',
    date: '2025-05-18',
    assetType: 'Jalan Utama (Main Road)',
    assetName: 'Main Road KM 12 - KM 14',
    blockCode: 'BLK-A01',
    volumeWork: '2.0 KM Pengeringan Parit & Grading Sirtu',
    costIdr: 15500000,
    contractorOrTeam: 'PT Alat Berat Kebun',
    mandorName: 'Mandor Hendra',
    status: 'Selesai',
    photoUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80',
  },
];

export const INITIAL_PEST_CONTROLS: PestControlRecord[] = [
  {
    id: 'pest-01',
    recordCode: 'PEST-2025-005',
    date: '2025-05-16',
    blockCode: 'BLK-A01',
    pestName: 'Kumbang Tanduk (Oryctes)',
    severityLevel: 'Sedang',
    treatmentMethod: 'Pemasangan Pheretrap',
    affectedTreesCount: 85,
    mandorName: 'Mandor Supriadi',
    status: 'Selesai Treatment',
  },
];

export const INITIAL_FIELD_CHECKLISTS: FieldChecklistItem[] = [
  {
    id: 'chk-101',
    checklistCode: 'CHK-2025-0518-01',
    title: 'Checklist Kesiapan Alat & APD Tim Pemupukan',
    category: 'Pemupukan',
    blockCode: 'BLK-A01',
    inspectorName: 'Agus Purnomo, S.P.',
    inspectorRole: 'Supervisor Agronomi',
    date: '2025-05-18',
    itemsChecked: [
      { question: 'Penggunaan Masker & Sarung Tangan Karet', isPassed: true, remark: 'Lengkap 12 pekerja' },
      { question: 'Takaran Mangkok Pupuk Sesuai Dosis (1.25kg)', isPassed: true, remark: 'Sudah dikalibrasi' },
      { question: 'Ember Ember Bebas Kebocoran', isPassed: true, remark: 'Kondisi baik' },
      { question: 'Piringan Pohon Bebas Gulma Tinggi', isPassed: true, remark: 'Bersih radius 1.5m' },
    ],
    photoUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80',
    signatureUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="100" height="40"><path d="M10 20 Q 30 10 50 20 T 90 20" stroke="green" fill="none" stroke-width="2"/></svg>',
    lat: 0.8145,
    lng: 101.4556,
    status: 'Lulus Inspeksi',
  },
];

export const INITIAL_FIELD_PHOTOS: FieldPhotoItem[] = [
  {
    id: 'photo-101',
    photoCode: 'PIC-2025-0518-001',
    category: 'Pemupukan',
    title: 'Dokumentasi Tabur Pupuk NPK Blok A01',
    date: '2025-05-18',
    time: '09:45',
    blockCode: 'BLK-A01',
    takenBy: 'Mandor Supriadi',
    userRole: 'Mandor Tanam',
    photoUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80',
    lat: 0.8145,
    lng: 101.4556,
    tags: ['Pemupukan', 'NPK', 'MandorSupriadi', 'BlokA01'],
    aiDetectionPlaceholder: 'Hasil AI: Penaburan pupuk rata di piringan (Confidence 96%)',
  },
];

export const INITIAL_GPS_TRACKS: GpsTrackingPoint[] = [
  {
    id: 'gps-01',
    userId: 'usr-mnd-01',
    userName: 'Mandor Supriadi',
    role: 'Mandor',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    isOnline: true,
    batteryPct: 88,
    lastUpdated: '10 Menit lalu',
    currentLocation: { lat: 0.8145, lng: 101.4556, blockCode: 'BLK-A01', address: 'Pasar Pikul Row 14' },
    speedKmh: 3.2,
    todayDistanceKm: 6.8,
    breadcrumbTrail: [
      { lat: 0.8120, lng: 101.4510, time: '07:00' },
      { lat: 0.8132, lng: 101.4530, time: '08:15' },
      { lat: 0.8145, lng: 101.4556, time: '09:45' },
    ],
  },
  {
    id: 'gps-02',
    userId: 'usr-spv-01',
    userName: 'Agus Purnomo, S.P.',
    role: 'Supervisor',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    isOnline: true,
    batteryPct: 94,
    lastUpdated: '2 Menit lalu',
    currentLocation: { lat: 0.8210, lng: 101.4612, blockCode: 'BLK-B02', address: 'Jalan Utama Afdeling II' },
    speedKmh: 18.5,
    todayDistanceKm: 14.2,
    breadcrumbTrail: [
      { lat: 0.8100, lng: 101.4400, time: '07:30' },
      { lat: 0.8180, lng: 101.4580, time: '09:00' },
      { lat: 0.8210, lng: 101.4612, time: '10:15' },
    ],
  },
];

export const INITIAL_FIELD_ATTENDANCE: AttendanceFieldRecord[] = [
  {
    id: 'att-101',
    employeeId: 'EMP-9081',
    employeeName: 'Supriadi (Mandor)',
    role: 'Mandor Tanam & Pupuk',
    estateName: 'Sei Buatan Estate',
    afdelingName: 'Afdeling I',
    checkInTime: '06:45:12',
    checkOutTime: '16:30:00',
    checkInGps: { lat: 0.8123, lng: 101.4512, blockCode: 'Kantor Afdeling I' },
    selfiePhotoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    qrVerified: true,
    status: 'Hadir',
    isOfflineQueued: false,
  },
  {
    id: 'att-102',
    employeeId: 'EMP-9082',
    employeeName: 'Budi Santoso (Mandor)',
    role: 'Mandor Semprot',
    estateName: 'Sei Buatan Estate',
    afdelingName: 'Afdeling II',
    checkInTime: '06:50:00',
    checkInGps: { lat: 0.8200, lng: 101.4600, blockCode: 'Kantor Afdeling II' },
    selfiePhotoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    qrVerified: true,
    status: 'Hadir',
    isOfflineQueued: false,
  },
];

export const INITIAL_OFFLINE_SYNC_QUEUE: OfflineSyncQueueItem[] = [
  {
    id: 'sync-01',
    entityType: 'DailyActivity',
    recordId: 'ACT-2025-0518-01',
    title: 'Input Aktivitas Pemupukan NPK Blok A01',
    createdAtLocal: '2025-05-18T10:12:00Z',
    payloadSizeKb: 420,
    syncStatus: 'Success',
    retryCount: 0,
  },
  {
    id: 'sync-02',
    entityType: 'FieldPhoto',
    recordId: 'PIC-2025-0518-001',
    title: 'Upload Foto Bukti Pemupukan Piringan',
    createdAtLocal: '2025-05-18T10:15:00Z',
    payloadSizeKb: 1850,
    syncStatus: 'Pending',
    retryCount: 1,
    errorMessage: 'Koneksi seluler lemah (EDGE), menunggu WiFi / 4G.',
  },
];

export const INITIAL_FIELD_TIMELINE: FieldTimelineEvent[] = [
  {
    id: 'tl-1',
    timestamp: '2025-05-18T06:45:00Z',
    category: 'Inspeksi',
    blockCode: 'Kantor Afdeling I',
    title: 'Mandor Supriadi melakukan Quick Check-In Lapangan',
    description: 'Absensi terverifikasi dengan QR Code + Selfie GPS Koordinat.',
    actorName: 'Mandor Supriadi',
    actorRole: 'Mandor Field',
    lat: 0.8123,
    lng: 101.4512,
  },
  {
    id: 'tl-2',
    timestamp: '2025-05-18T08:30:00Z',
    category: 'Pemupukan',
    blockCode: 'BLK-A01',
    title: 'Memulai Pelaksanaan Work Order WO-2025-05-001',
    description: 'Regu Pemupukan Alfa menaburkan NPK 15-15-6-4 di Blok A01.',
    actorName: 'Mandor Supriadi',
    actorRole: 'Mandor Field',
    lat: 0.8145,
    lng: 101.4556,
  },
];

export const INITIAL_AI_OPERATION_RECOMMENDATIONS: AiOperationRecommendation[] = [
  {
    id: 'ai-op-1',
    title: 'Prediksi Hujan Deras Siang Hari di Afdeling III',
    category: 'Weather Impact',
    severity: 'Warning',
    blockCode: 'BLK-C03',
    recommendationText: 'Aktivitas penyemprotan di Blok C03 disarankan dialihkan ke pagi hari sebelum jam 11:00 WIB agar cairan herbisida tidak tersapu air hujan.',
    suggestedAction: 'Geser jadwal tim semprot ke Blok B02 dan percepat durasi kerja.',
    generatedAt: '2025-05-18T06:00:00Z',
  },
  {
    id: 'ai-op-2',
    title: 'Peringatan Risiko Keterlambatan Perawatan Jalan',
    category: 'Resource Optimization',
    severity: 'Critical',
    blockCode: 'BLK-C03',
    recommendationText: 'Collection Road C03 berisiko ambles total jika hujan malam ini, yang dapat memblokir 80 Ton pengangkutan TBS besok.',
    suggestedAction: 'Prioritaskan Grader & Sirtu ke Blok C03 sekarang.',
    generatedAt: '2025-05-18T07:15:00Z',
  },
];

export const FIELD_OPERATION_REST_API_DOCS = [
  { method: 'GET', path: '/api/v1/field-ops/dashboard/kpi', description: 'Metrik KPI operasional lapangan hari ini' },
  { method: 'GET', path: '/api/v1/field-ops/work-orders', description: 'Daftar Digital Work Order & filter status' },
  { method: 'POST', path: '/api/v1/field-ops/work-orders', description: 'Buat Work Order baru' },
  { method: 'PUT', path: '/api/v1/field-ops/work-orders/:id/status', description: 'Update status Work Order (In Progress, Completed, etc)' },
  { method: 'POST', path: '/api/v1/field-ops/daily-activities', description: 'Input laporan aktivitas harian mandor' },
  { method: 'POST', path: '/api/v1/field-ops/offline-sync', description: 'Proses sinkronisasi batch antrian offline (Offline Queue)' },
  { method: 'GET', path: '/api/v1/field-ops/gps-tracking/live', description: 'Posisi GPS real-time tim & mandor lapangan' },
  { method: 'POST', path: '/api/v1/field-ops/attendance/check-in', description: 'Absensi selfie & GPS mandor/pekerja' },
];

export const FIELD_OPERATION_DB_SCHEMA_DOCS = `
-- PostgreSQL Schema Blueprint for PalmVision AI Field Operation Management Module
CREATE TABLE work_orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  wo_number VARCHAR(50) UNIQUE NOT NULL,
  title VARCHAR(255) NOT NULL,
  company_id UUID NOT NULL,
  estate_id UUID NOT NULL,
  afdeling_id UUID NOT NULL,
  block_id UUID NOT NULL,
  category VARCHAR(50) NOT NULL,
  priority VARCHAR(20) DEFAULT 'Sedang',
  mandor_id UUID REFERENCES users(id),
  supervisor_id UUID REFERENCES users(id),
  estimated_hours NUMERIC(5,2),
  status VARCHAR(30) DEFAULT 'Draft',
  gps_lat NUMERIC(9,6),
  gps_lng NUMERIC(9,6),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updatedAt TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE daily_activities (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  activity_code VARCHAR(50) UNIQUE NOT NULL,
  work_order_id UUID REFERENCES work_orders(id),
  date DATE NOT NULL,
  category VARCHAR(50) NOT NULL,
  block_id UUID NOT NULL,
  mandor_id UUID REFERENCES users(id),
  workers_count INT DEFAULT 1,
  work_volume VARCHAR(100),
  photo_url TEXT,
  gps_lat NUMERIC(9,6),
  gps_lng NUMERIC(9,6),
  is_offline_synced BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE offline_sync_queue (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES users(id),
  entity_type VARCHAR(50) NOT NULL,
  payload JSONB NOT NULL,
  sync_status VARCHAR(20) DEFAULT 'Pending',
  retry_count INT DEFAULT 0,
  created_at_local TIMESTAMP WITH TIME ZONE NOT NULL,
  synced_at TIMESTAMP WITH TIME ZONE
);
`;
